fullnameOverride: renovate-operator
route:
  enabled: true
  hostnames:
    - renovate.aknuk.dev
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: https
webhook:
  enabled: true
