apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - argo.aknuk.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpkU2JVTGpL
        YnNjUGo1MktrTDdhTjI2UkwzQU1rYUVRWjBLQkFhTnozRzBCWUZEZ1FPbGxVWXIx
        Wjl1Ym1vUnhTTHdKNlErWGdpa2hTSGx2UnV1QlpxQlZPYUN3ZUtCNjE1cFVEMEFw
        eU5YWHp0a1U4aC9ycStIbHR4ZW5KV21jejVUMTI0b0puTSs3Z1JaMVZseHV0alhs
        S1VCSmgzS0JMeXNZWURlSXIyMytYVThmb0tFT2JNZU5vN3c0TEY5Tkh1eDNGSTZQ
        TW4ySFVxWEI0eU9jNTB0TG9MWldQV29GTFZ0ZUhMSjB0OVhBR2tjS2VPTDZZQ24w
        T1NiaEt2SlFramRtczRmQm51bWQ5T05EWHVFeVZZaDZIcURYNWdWWXZVbVR5UHFr
        SFpQTWxVUzRYNUdSMHpnT3F4Qi9jSzZTaXJxVGc1WDRjOFJUZDJmcXQ0MHVlclh6
        enMzaHJ6b3RDM2JmSnRmR1VYM0Q2bW1QTHNzSlg3bHllQVRaeGpDNVN3VTd2bnRz
        S3FQSDZuclhsZVRFbDZLOXNoWWVTYllxTzB3QW90UkhZRVJxWk9HdWlBQ3VFazdG
        ZzROVGF2YzB1bHlpaDNCamtuZFdlYW1Tcjd5Y0VHZGczTjRSM0FGU2grYmljTFR1
        OWh5c2IxMEFsUlVqZkM0S1RFSExZaTVpUzhMbHc2Um9hNUNHOTc3RmNvczg5T1Mz
        NEp3OTg5VzBRRXVQQThGMWdlS1liak90QVJMSXBnMStyMVFwUlgvbXFPRWhJWjY5
        c05reWw5SVdNbHRkYmdhczVBRW5lclpVUlJDUnRjdGpKcnhYS0tHUHlYczNkNlhK
        VThUOEZxdWhDRkhSV3dwOVRHYndlY0RLcHRJV2hEUUdudWkxZnUwM2xYQkovM1A5
        dmpHS2JBU21aTTZNRGk4aXN0RE91Vnk3Rm0vTEU1WFRHcGg3QU4zbFZJbkFsek1H
        T3pHYXNwQTlJTWVYa0YvN01LdFNMMFhmdGk5V2M5Z2RoeGEvTTRnLzZ3RTcwSlZp
        Qk83YUovWkVtNUpYeDJNWHdQOCtVNERJbzFsN2lmS3cwZVVlSzBuczArTS9RWllG
        TzhFb2ljS2I2MEdqOU5GVURuUFdhOG1kNHlhYnJUdDRsRjkxVE91ZzhQUU0rYnd1
        WURGbEdCWU1RNXdzRTVxc3VLQzlaLzlsNkpTcmM1Z0lwL0JEM3VXWUQrQXRsUWsx
        T3A5NGVFNERsNE9kWHZyZURQTjF3UGxZYWJMRGhqMGZWSyt1TFlUbHF4RUtKSzlw
        dEYrMEsvVitXc0taUjZsVWFoQ1VGVFI4cTA3RlpSMEo0bmZQRytaQUJGbDZoOEZv
        T2RzdWp4WGNWYk1WQUxITkVEcnhUSitvMjl4SlpNTk5Ib2xoWFB4ekJwTFMwOVlX
        UnJZVWNKQkw4QnVnTFhhTHNwcWppL2lGZ3JlUGoyOHRQWEphdHIxN2hwWHFndUw3
        cHJxaU9MVVhDcXMrTDFLTTF3b3VFaGZuODZPN1JSK05zekJuRnl2QmtJRmZxOFpp
        Vk10YS9lcVh5am9QbmNKVTg0MzdJRFU1Qjhma1BEYk5tbGRXRE5PUFNxQVJDUHBO
        RjlqeDBUY1VwWDVuYXd5b2tmSlZvajJxYmVOc1B5WlFSbHlmTnVUVnRLUUZKY1kv
        OUdsSWNpTURTQ2s5UHlUejJrZ2FmeDFEU0FQd01ZeGFhTkJrZnBwMkhtQ3BtSWpK
        TkRwbWF4Ny9BQ3BTZjNKRC9DNmhxbk9DYkVFYlBlWkdBa1NqS1lYUnF3VDBsc3Jo
        N2J4SU95WWFGSEt3VUR2eFFpdlZvcVh0U1BnSG9FZHpZR0RybEh1Qk9OTTV5NnpY
        Q0pQREh0TjBJd2txSndVb0k3L3BoNkRMUzdqWE9Lb05YK3RSZUVZY2dNQ3FGMHpG
        dEU3SEducXFYNUtTRkVDL2ZpdW9LWGNxWnNKSlgzVzBNRjNXNG5JclcwOGVHQQpt
        K0RseVlIdTVKQ3NtVmxtMGFKWkdYeVN3S0tGMGJaTThOZHJlamtpSHFRCi0tLSB6
        Zi9yTGpuZTN5YVRlUTF1MjNlenFaeE5ycUdSZVZRQnZGbTJ1ZFcyaXVBCmT9Db0Z
        O+SYgBplNXyhJZFX8UPW1PQ2uQRN5jFw85Bz5TNwqKumHS3tQDXFbLnPbWj/8gPI
        +LBK+7b7uv3/OCo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T11:54:00Z"
  mac: ENC[AES256_GCM,data:b2+9PpiYtFoDkklBdlNN3+176VaZdGtzdIvQ3nyjmnB7DPIi91kDcqI7rNBh50Fnt3ZshMOpXKqzlyQsdRjUSLcoljajhqBX9kqDhsH3KVlDIvxOpDsEygDtuWVKIdvawx53evhrvReyCDhwXRq7yTFynGFj2p6eNZs0XL7aGYI=,iv:J8bYEXagGFKsIwkXiLlLa54TFJUNJjr6v+4Ep9SA6N8=,tag:4SypXrPfDDpiYYmV3nwURg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
