apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: network
      sectionName: https
  hostnames:
    - argo.aknuk.dev
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9GQ1RHV3RR
        bzJUVjVYZWJjRTJ2UkxWcFpyY3N3clU0bGtLeEdRN2xmZnhjWDZkdjE3SHcrVnJF
        Z2M3bys2UGlTS21TdGpLeDVvM2ppS2Q1V3hPWXhtZmhnS212YXRCNSthdEtjQ3Bm
        RmNXeWYvbzY0RmVtOU9GTXVJTXpQc3FVaDF4eTVZVDNtbjZFaHhMeDhyMTJRK21m
        SlNLSnI5OUF6M1ZzZCt0enI5bE5rcGMxWHdENDNDeG5WUDkydkQ5SlVyOXZQTE5Y
        N2YvOHdIOHlURG1Gd2duTFNlNmxBYVhCcytrNDJtOTVXMEtsNG9FeFJnRmlMWHJY
        NHVVUXYybHI2ZnZjTmlQU3Vnb0YvWDRPcWhtdktmVGNpN2IrV25UZlFnU1dEUnQ0
        dWh4QVZMb2JCa2EyMThRSG03ejhSR0paemRDblR4NSs4U3BPSHYvNmJvZ256cSs0
        U1NSY3QrZkJrUy9xUWg5WGxTSDUzZWlTUFRDSzhpRDZodEtIeXR0NU4xeElSazBJ
        MDU1NVZDM2JKak5aeHQ5Sy9jRGhKdHR6ZnQzVE1mYm9kVzAvUUs0akVKdDRKUjlS
        Tm5US2M1a3I0K2ZZRXI4M3pQWEFuK2MwenFoSnFlWjBnV1h4eHRxKzBHQitiODBL
        RGlleDgwREVMTFRuditCZmI1SGNEKzdDRHVzQjRqcEE1K3BrV3EyOWFoVzl2Z3p5
        SUlVcXRvOGJVTldjZWtBcWJ6OVAzTFA3QjVBU0RkTEdtL0F1YTdtWFQ3THN4Zm9S
        SVdQSzY4WFB4U0c4Vkg1UnVSdjk2cjZrNlhVT2NEaWR3d2tBNzY3SXdLRXNHb3hi
        QnBBTVozRHRqcEZoTGdHeU4wWGdhSi9tSHV4Qk00TXBNODZ6N2M3eDkwdU9xakw5
        dXNyVXdkS2VHRGYybDdrVk5aZ2FlWnJWY2dkcVE3cjZzZlBIYUFFaFk4eDM0S2k0
        NDFRblZaSDZ0VFlRSUlMakM0OFVqVzBtK21uNFIzbkhLaGRDSGdCSFJYMGF6SDJo
        Z3E0WG1Zem1rNFFiNlpQNno4cGVGUk4xV2J3RStTSlBrZi83QmlTL2ZITnhiL0pL
        V3JGMUs0OUdiK3dudE9RSmFiNGE2Y1NDUVBMZzByVy9jYWhZNEh5SEdJbHF0bU9I
        TDdpTHVQR0czN1h3OGdlY1NCdmJ2TmNPS043NFJDbTRSTFYyRjJpR0l3T3NpcGdR
        eDhXNCthMWQzQVVpWDAxU2VoNmVJeHVCUCtoSnY1SnkyWGtQd3k3eFJOcFhLTVAx
        dDVNZ2FhWlB6dVBTbFI3WXN2Zk0rbkNZdzVLOVl0WWZUZTZkSytKakt4MXpEY0Jk
        eEZHV1JSYUEzZW9IUXFQWGo5bXdCdHBxdGNJVGpMUGxpd1FZNWFFNi9YTTdiME9J
        aWRjY3ZsdzRaYkVZbzZQYjdvaXpPVHhmanBJRlREdk5CRHlXWE9CZ1FXbjhpeWVC
        UW5Sckk3cFlHL0VKMHQzTjcwYTJkTVhMajBIK3lXaVRQSUh6aVhjNDhvYWFzN0xq
        dGM3WklXV1htN0F1WXJBbUFNT3hlSXhPcWs3c1hSWHJJcmJnWDJXcS9SOGJjdU1V
        VmlCYnlwYnc1M0lWbmxPRnRMbWJOTTQyNElSckcrNExkeUhTN2NTSE53NmE2ZEF2
        d1hZNC9xWk5CRWJ3L3FuMHJWdy9Za1JHR2c3S29uSG1nYlNHSk9SMEc3UjYvL1pn
        OGV1aHNVUStqckZuNFQ2N25wUkRISHB4M3I2L2xkTG5EamRrdm1kR0hhRmFsN0pv
        bVdKRE5EMGJCcytHTVBPR1l2NmtwL2lCeXNVM0x5ZnQ0UzNGK2xXMGhsQ1B0ZEdj
        WmZqbksxV0ZlSU9pSXQ0dWI5UUt3eGZJV1Y5YmVmbkdOUkY1djhPRmZ0bHkyekZU
        VzNiaGUxRDVBWThRNU5FWFdPdHBaK1BFZXd2bmdha2xJZ25tVWcxUTdlenZCZwp1
        M0lKUjQ5U0lPMzhVVzhadytUU3ZFakJDUTBqZmJzM3BGbnlBQUIxUTVZCi0tLSBh
        c29lclFrUzVTNy8zUTc2ZDJYZ0RUUUdIRU82S1VydG80SG41NFpVNldBCpXrFIFc
        wHJAr4qd7klBJ6S6G2YSVo2yj8M6XQw5pTezd3H/I7vltYi8HNS15IURkaxUfyXI
        5zgh7E5lLSE754s=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:14:15Z"
  mac: ENC[AES256_GCM,data:QYbL6jY2NlQ79tAzdCxuXbjpVjtsvjYUpYg5aUf/GNvKTqOwTnuNXXq5QkgZcXYEbbmRcuXw4iHiUe8z7vZIzp5wYwjsEHBD67e8PHTtP2Lhvkv0/FuOPeg7AN8aML7EbS1JEpqSGhEer/FqzZv/i83g5BmTYaGJufMSZSLdyFY=,iv:OtUTRlfArSzNxkyhX8/5dyOxgiccbMMndGa2niT33xU=,tag:rNQRaq0IXuXJeUGV+a/8hg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
