apiVersion: ENC[AES256_GCM,data:05zCAubmOoWgqfYaE4Ly28bJWqtg3WnA/tY6xQ==,iv:6xHIfyZn/zn1F//1xhlA5X2kthb9D9lnN/x/2st3ROc=,tag:A2g4mit/sHapYey5gcEQ7Q==,type:str]
kind: ENC[AES256_GCM,data:OteVeXuCO70o,iv:C/GUNttcBACsGfUV1DlC7blMbZ7RHZ2+MlN9nEZt2Go=,tag:bj5k0MvcHar/CXZmL0BU3A==,type:str]
metadata:
  name: ENC[AES256_GCM,data:KIu2qQ==,iv:CwA5004SSOjndZao9QhOjcyVDeVSN3QeLYMez/t8qGY=,tag:E9tKnro3C5qwwpUR6dwwZw==,type:str]
spec:
  parentRefs:
    - name: ENC[AES256_GCM,data:2jHDMkc8iAiQmvUuU34=,iv:B+t3ncCiTgJijMwXVn1/MspOw0nc/L4uuMo4RylXyak=,tag:viA4VNNqCRvCi1BvFAofBQ==,type:str]
      namespace: ENC[AES256_GCM,data:4UJfbwUiTw==,iv:csStyy7GUU4kH5xIQHpjtGF2yH/bgkLxx0GbzCpMCBg=,tag:y8HOZo8Qsz0EolD55N69RQ==,type:str]
      sectionName: ENC[AES256_GCM,data:dVspuX0=,iv:HJTqZG70uv0QYlFYyF8ht2KxxT8jFfka29qug72hSsE=,tag:raiYn5AAzmmqRp9C6y7Qug==,type:str]
  hostnames:
    - ENC[AES256_GCM,data:fqMl3/jKxBd5SGRDu9A=,iv:Xzg7sO7KCjOSe590ziY94OtsZhOLD2bncne6E4fH1Sw=,tag:v7NIHMyGmRIHho7ns/upVg==,type:str]
  rules:
    - backendRefs:
        - name: ENC[AES256_GCM,data:ey476ppl+sp7+SHsqQ==,iv:tH8H5cCgO84vWWhBreaNzy2esyXL6H5LggfKtGpb798=,tag:eVzd3hJdk2u5RHGM9Cfopg==,type:str]
          port: ENC[AES256_GCM,data:RgM=,iv:qJio+Y8uws59js4GoKYftbifd/5CpAgScbRs1PfxzAs=,tag:K8dLkpV2NlkhUenh4YaC6Q==,type:int]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDdsd0R1bngx
        UjNOd0NpeHRhZXVBcXlOSUYvbkxrTWx1MGplYWgyUFpLVjMzSGNpTGMveHRCbUdz
        bkVWYU9odXFteEluMHdUNm5xVjhoNnpsTE5WM3hncTYwalg5Q2R5RXpaSjJCeXNN
        WE1hb3FoMmhBeEhxdjhrbXhDbStxL3JIUGhKd0RIOW5UMzZBcEJtOXFnTFg5WlU3
        RjgvRXhFcGl3aUhpemEwaXVzOGJabWRyd1pBM0JBTGN2czFkTTQyVXJId1RxTzk1
        YU1yRjNEcS9WZzFRbk9rb3VRT0RDR0haaTRzUmoyRm1iWGFaSUM1MnlickZYWjFG
        ajRsaU1CVnhxUzYxWHZROWNpKzlaeDFYZmhrSjB6a2w3OTIxeEN6cHU0MWVCRC9y
        OEt4dkpyc0FqekhzbTR2dythVVVyWXd3WW05N25pVEpxTHVOL2tnMUEzeHh1ZHdm
        TXYzN2tsRElxOWNxbmZ2cWlkM2tlVW84eG1IWW5NL3g1NCtIdG5Jb1RXd2lRdTNL
        clovcEV3MWZhZm9DN3FRNFRSeG1Qa0VyUURDT3ZKYU1JYzl2dk1pdHBmQUxnVlhE
        V3psQmxjYXUrRmNpUGNEMVFyWXhKQk5mVFFTR0tBL2REMDBMNEdOQWxuU1NaVXNi
        aUZBbUhpTVk0Y1BZYUtZOXJGMFJHNnJYOVV4bGNqN0V2bU82cWg5N0VmeUh4Y09O
        Y1UwbmZiR0Y2b1A1eEJjT2JqK1RSL095RnU4WjNNTC96ZzIrRmlPd01tY2xIN0xI
        ZStFMzQ2cnpiNWZjZ01jNWxtV3lGR0ZIVy9GdkJadUcvLzRRbnplOTdPZkZrL2p2
        LzdmOEZyRDZ6ZHA1TkhPVktKK0I4ZXBXbFh2eDlGeGQ5dys0REptKyszREJ3dXZW
        VFIwbUp6V1ZFcTUxRUQ1UUpmdlJnUExtRThuTUxvYzZrcEM2TEdhQzFzb0JlclZk
        bW5TdThySVhHTnI3Vmk3NzdZS0xpREIzVG55R0RjcHVPTlFaTVB6R2ZDSFpqRXZR
        OC9ZUmZFRjBlcXU3MG5rZXJOVU1WOHlMQmQvSVR6Y1JnZzVQTGZFaC9mSXZBQldo
        Nk54aUViVFpLaFR0Ymp4c1FpQW9DMnNrWGhTeWZ0dFNWcnFmSHZSdUFxWk1LRW5P
        cUpnZDVUL1ZwRDRUTG1naVYwUVpDcy9tbGY1K0wra2ZRVWFKUWhhY1AwUFRBY1hw
        d3luNmVwcDQvTEFEa0pSN3MreXZZREtIWG0rVHluL2M0disvazhFSFdmZjhuWmd4
        Q0xDazNwdnQ1RXZxNld6R3l3bnhXQ3F3ZGxrS1hsTTdDTklZOHZDNFVqMDh2aHZN
        SithMTZKcUlXMmZ4WnM4dTJHaWxSR29SdE5sNjBEWE5XZ1gvWndZYm1HVkk0STFW
        VEp0YWxXUFM1UUdBNFBvR1BSNkZUanRBd3QwTjIzQTNTNCszWU5jRXRvVGxlVXVD
        Q1ZXY1FnS3EwcHMzV2g2WTJybHBIZGFPcUF2c2p4Tk1aeFlXNkcyUklrY2lNdjNz
        Qm5LT0pqWXFEUis0TTk1ZnZrZVJaZWlXWWtBTXRiSXRwc0d5TG5IS25YbzBFVmEy
        bVljeDl4VDlJcmJudFJPM1VNWW8xMlBXYW1kSHh1REU1WEhYQkptQzFWRVRsTXZV
        NzEyNERGbWdGUXg0NG5odnh1a1FaaHhPT1hRL0h6cEVSbE43d3N3aS9lZGptNUJr
        YkJIajZiWnlmR0RobkxzSUhST1I4cDhJSXF4Vk5hRGJqYzlZbitRbFp1NGp5M1Bu
        aFZwOEQ3dE1YRGorWEY1M0ZyaXJ3d2NVTzM3K1oyVWI1QUxCYzdUQ1EwRXVtSlpx
        WDEya3k4VGlsZndXbktiZEtpMDJ4N0dBckQvcENoZHVBUVF0SzAxQ2dCZVZUM3B6
        azMvaW9GdXEydjNCVTV5QktKUVNCRFlITFpsemRFYmlFU0J4QzFVTWYzVG9Tdwo2
        bEppdFNGaW5ERUxobVJrU1JUc0U5SDM1Q25tSjhjbFJpaEpmSXFnaEd3Ci0tLSA1
        OWY5Tnk4d2tFVHVRaitOV0hnbzRtWlZWV3FKbGh2ay9PeFJCbFpKR2xZCjNadADY
        pB3/Pou2kPlGnBidHXeE50bjwn7GqElGXuwanRWesQRZrqjGocRiVDvvGYC3klE7
        TTKfPx2ohunz8Rs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  lastmodified: "2026-09-22T22:19:00Z"
  mac: ENC[AES256_GCM,data:zCf7i2YmPSbNbfvUM9kWD8Qa3N2WXwpbq7onJm19pHYe0fZR7E5+K2Th/186PAvBsHTXTPxZe5nE1pTeI+v7FvRdWZy76kTDtrf46lE/QhZIs26McFk2+mhZhR6JsZ1A+aF5bU172HX0CG3zXyIVELQM7umv00SoYQv/17nApNI=,iv:OooJtgTE1mUQ3M55HWAZkJjvlnN4CP0Mm7nKMg+Niy8=,tag:JTp1NoorYm691fwAw05iFg==,type:str]
  mac_only_encrypted: true
  unencrypted_suffix: _unencrypted
  version: 3.13.3
