apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aknuk-dev-production
spec:
  dnsNames:
    - aknuk.dev
    - "*.aknuk.dev"
  duration: 160h
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
  secretName: aknuk-dev-production-tls
  usages:
    - digital signature
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5ICtDaWNLemNs
        UFlvazREaEx3alpzbnpMbUFWZmFQUGJuM2U2MXZzRFlWRlhMMjNxTFozRWdjdUU1
        RDFrblpsbTRxQ2QxZlNIN3p3dGxjQWtGWEtQQ3k3N0l1NTFPNUE3UlNneEREdjE0
        eUdLM0pzQnN3ZGFpejYzbFk4UHdPblpqN1dCTnJ4UGlubVZOVzRRK2RGRWdHMDdK
        anNyUnZrRGlpYVpObXJkc3ZWZDhFSGtYOHpxZElnS2xFckRlNTlzUEMxNkJsbll1
        Vy9tNkVwUkdUL01TTmJoTWNoazZTR3V6TThLa3B4U3NCTTVUanVwZnptcGVTV01u
        Z051cnRRRU4wSWxBS3d3M2RpNGlOQ2w1d3JJRFZrbGlJNFhQUTVtbU1FRHBrWHhS
        U01GZEpXYXZ1Y3g1NDNOU2hZMEh1S0ZldUhrUklucEtHOVBJelRJZGE3UlNDYzVy
        TnNqcWRQUnJYcU81Sm0yTklWUEdqMllOdnZ1YURqQTl6RzNEdUpTTzFkU3pTWTdW
        ajEyVHBxaXJmOFAvY2tEVE0rYnpWOFRDT01TQm5SMzlMNkltNzROLzczSVd2N2tX
        TU9ScitMMS9lMXVTNUxaWkhCd05ubHBremlzNzF3bFJLUXd0azlSZ1JDWlRSeXR4
        N1NSQSt0YTdaajdYekNvbVMzNzFlMENmV2d0QThxTzZCNDg0bEtWSzMwcWp1c1JV
        SnV2bllaSjQxZGNXdVA0VC9rR2xveE9VMkFCaWlKZEZLTXE0dWMxNGdiZDV1ZlUv
        NGxKOGlxVHBsNVd6a3NnWDdnRzJEcEd0Y1BRbmtUekhYUkhwVDRYSWlEUnBwNG91
        YkVKZEhZa1o4USthYTY5WDc5TzMzSng4YXI1RlJGcEtBWU12VW1GbU5FRDV0NUFR
        QWZGZnpDak05NGxGS0JmREl5YjlhZmRBQVJPSmtLY0VUbFA3WkNOVlVteDFManFh
        VjhvUTQ1Z3RXSmptQWtuS1JtcHlsUldNMWtxdUtNaHBzcGZPcy91TUkwK1ZRVEV5
        dm02QVJjYkZIamhCSmdoaS84U1VPdkFhTnVqQkl6bVBFUlBDd092OXpjM2JzeU1M
        QXJJNDk0bjlkU3pZNkRta1J2N0sxOUN4RHMyTEtPaTlhM2NyTWc3SU41QkV3UkFY
        T3NoUnU2dlZ3U2lqVGpKcDlmNWJHZURETURXNWo3RTZ1RlJYQnFDUEdYTjl1bGdj
        a3dEb2drY053b1lYTEVBem5WZ2s3MmtBemVZcG5vV2RyQmRLdVlKVVhFYnppa0w5
        Q2tVNTRwMUNlYktTNFladi8yY0JIc2MzMTZTeDVNOHg2MVZlSzlSK2s3YkJOLzZn
        QkM0MXFBMTJiY056YmR1WEhiaytmdHBzY2wwVTAycFhyTlB4VkdHZEdQTlJSQ05N
        VlROMjBxOTVibGVDMGFGUFZYV0FhbE9VdVJtTU9NWTE3WE5yRlJ0WGtINU9YZHFR
        SjlUenZSeDlPSU9iVkdhRDRMY1NDRHpIeWlZckNvOWJqYTQzWitTZy8zbkswQ0Fp
        VkhVWUhud29lL3hybFNrSldGTHRJeE15Qks4UkFLdFg0VG02bzBQUmpoODNCWXFJ
        RitGUmVrM3UvWC9LNGRBVDNZc0dJQ1pGQmQyQkNWclpGNGVhRkJrcmtmeE5JU3dG
        ZzhSY0dVaHk1VU9nZVRDWXhVNTdXOU5HR2RSb1Y4dUJ0dzFHUmg4RU5SSGxaMmZK
        Rk83alEvSTlQaUNmWFVRWDl3ekhUNU5UckxPLzR3VnBqbUVCQXVhU2JIMEovYllQ
        SFl6a2pncUhESUh1ZXVsOSt6Y3BEYnVYSkFjZzVxS0VFT091NmcrcW5RQitaOXFK
        SnZxbG9oWkZCRS90UXh1VzY2VWtGempzN0Y2UmdEV1lFUmZmVFhQQWZpb1hIWHJR
        dSs2UXRyZVpKdWdxYWJId1FVTmF5NUx2ZlUrTzFYOWtrSUJpaUVEMUR1c2RiZwpq
        eWViQW5xQ2NrSU44dXRjZWd4Rk9xR1VzaTIyUWRCQ242dlBieDlQaDVRCi0tLSBM
        Ukg0d0hMYVA1RmdGMmNCc3F3VlBPVjFwVHlySHBSZVlRK2hPRzNLa3dRChp941d6
        MmHyfLyoir2HqraoV7hhskBkQDLwb9iCjKKPFwDrMVZ8L+HO8zxXnz3FsyPsuWZX
        99mJZLGlFSconz0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:14:15Z"
  mac: ENC[AES256_GCM,data:p0n3pRHj/yBaKxjsgeVIgofVh1wywfy5ynUrA8jkN8mhVWz17CKQ3T08BStuDwapYcz/OGfjZ4Dsp2xY52XxCRMYbGoWJP67MurvmN5Oinz7BtsapU953reDVGkQ49ntWXRS+tfedOr/6rXVZPxiV3nKxZCEQcItT7OQ/iVB7Jg=,iv:bEK2Zq79sdHB4Zrd37Q1b6qvAYYfogcTmPcFL8/ymbk=,tag:df2H/b0VKkGroPwbJqZ7aA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
