---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~1.17
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.0.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/onedr0p/my-awesome-k3s-cluster/master/deployments/flux/flux/flux-values.yaml