helmOperator:
  create: false
git:
  url: "git@github.com:onedr0p/homelab-gitops.git"
  branch: master
  path: deployments
image:
  repository: docker.io/fluxcd/flux
  tag: 1.17.0
  pullPolicy: IfNotPresent
registry:
  rps: 1
  burst: 1
memcached:
  enabled: true
prometheus:
  enabled: true
syncGarbageCollection:
  enabled: true
  dry: false