controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 39
        env:
          HTTP_PORT: 80
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    ports:
      http:
        port: 80
serviceMonitor:
  app:
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.aknuk.dev
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 80
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHp0ZlRObzRX
        Lyt2bWZ4YVpEdE5vU09wL3dDU0NZRzU3WGM1UTZjWXl2NHdKdUlWWWRzWFJqNXRJ
        V1pvQmZrVVJRVmFBdjE4WEtCTWszVGpSK2REQVdZZmoxSEZNeVZLbnZ5TU54Mllz
        RDZzU21DZUVHQUxSRXI4Y1NadklmUGVTVjN4dldQNDJ3eTRuclE3c3V4a09vZUF2
        Tnd6dng0K0NCeTg5ZjcxOVZWYS9FRmhpeVVNR3NtZ1JUbGFZcGJDcVBQT2xwYnRt
        QnJzTGVmeU1rU1Nib1NVOXpHY2JVNWJQVlVlUnFqSkxVTVJHWDlxL0oyTEZWb256
        ekN6cDN5R1pFNHB2QXZPNXl0U00xK2FuU3ZnZFFiVXpqR0Y0R1ZwdWFsZytJL0k0
        aWFTQXVxdUJQVm5uOEF3bXM1QWtwL1d0dTN0Z1VFbm55dUdFN2xRcHZ5dEVEclZL
        VjMzbGRXTmZUMSt3ZWdNOXYraE5tem8yckRCK1IvWERMUDVUd3F0NzBtZExuR2FK
        NnE3MjdMc3hUZ0phZUcwaUZ3RG9Sb1RjRXBWeTkvcStJSG1RVUZRYTZpQXVxNkNM
        dUlYN3NSYklSV2dQZ0VJV2JsZk1yN0VIbWFNOWlhNklFZjdkRm81U1N1M0xsNjFr
        Lzc4eE96Sk9YMmRXcFpCRVF6RnQvd3loamNjNkFINlUyazRSWWptcFRJMm45blBU
        a3ZtNFFjTXkySVFpZktSR1BEU1VPOXVYSkVzMlFOdWJzQW5ZL2pmbGpsdDZWZm0y
        TzRrVWwxNDBUSFhrcXFtYzIzZjlrQWtIVjA5c2EzaDdQbnBzcWsvTGhySkpzWWRn
        UVNWd2VUWU8zekY1NlRvWTJ1eTFpU2xzZ1FpVXBYSWJFck9pbHJscG13UVlPVmNL
        OFZHQ1VUUU5FN3NyNkZDOWZLc1VrTjdnQUVTbEQwS01lV2cyaVA0V0pJNXlrUk9y
        L00rcjBjZTdSbUF1T1V1RGdYTEhQUUhac0R1ZHczWGZMaURlNTVrMkNtRTY3M0hw
        Q2V5NGdwRDIvZVlaUDVDUkRNdDV6cjd4aGNFYVdzQThneGNZa1JNTDFOYUhpMFph
        N3JISUlZdGZYYiswNXNJbnhiVDFVRy9rRzNNUkJnTTNuUmRaZURsUjgyQmhSTTh1
        ajZSRHlaQnh2Zy80R1l6UWZ6c2ZkYWNvcTk5T0drQUc2L0hJZFJRMVZ6bWh4MTdN
        RGt5bXB4Z0s4eWEyR2QrYVhQK3Y5QUUzWFFiajErTmFZR2tFcGxZWEdkZFZGV042
        bEhQQTZKYTlTaGo2S09lMnF5SWJZVjFRSHRBOFpicGRPbzF0MEJJWFpBa1diYmpS
        a3ByTU9MYjZvaFRXeDRMd3V0dmFoajc5dXpjeVVMZ3UzUEkvZUNZUFA1U2lGd1pv
        bEp6ZEFqSjhPQThrM3RsTUFtSmVMNTNoTnNWZ2l5UDNYbHVDbEprSVZHY29ldTJ3
        U1h3RHpqSE1DelNZa2FYTjdvNElnRlpJNjdsWGtNSHdzekZmYm40UXc1bHRmWU1M
        UTVoRlpxOUZod29FM0hjNy9PUDFFTWFRS2h3S2x0SVNRUldEVU1DcUdHdFVySFJt
        RHN1Ui9ITHpDM2VtY2pnSGZDdGFhYkhqYW1ZSVhVd0dPUVhEMzVEWGdnL2ozRDhs
        YjBTTlBaanRtdlZzZERYeHZ1QXQxcDdjQjB6QlAzbVppdzdxUkZ0ZEVEbHN5M2gr
        TWQ1SnpKbmRmT2VydXRxT1A2YVFWMklHQkNkMTR4SVJndXFrVzQvSm5mRVBoRzdy
        VXVBQzl2NUk1U0I1T2xFYllmRW9haU1xRXRnaElveENsRWVtdENPZGpvOXZXY0tB
        WmVJYkxZdFRKcCtScmNHTGZ6d3UwL0x5Zldqd0FsYzRGOUZhOTc2Q1RoSUtNTUVW
        Wk8velF3bzk1V3B2Vk11U0FKYkJxdTRlT0VDd3hVUGtaNVJQNm5XRTNDQ0lOdwpn
        OHYzNitybVliRVU5RVkrZUxKc25vaGYvU0hGV2VqVkJiUjNZSHhlVzZBCi0tLSBH
        QkZLQk5TVHNycGZkeG4xZTg3YVBWTmpiOXNXK202Q0Q2ekptQWF3aHV3ClbCldRq
        6EUN8TJUMBM8PnsewnWHB12n1M3F/JBj0o3k4pbPdA12bBsP0HQZTAyzFbSiUa9B
        h2G8P6pNTJSWoOo=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T15:30:58Z"
  mac: ENC[AES256_GCM,data:z5kCBA0tMpa8JfbOt3D3ttATWCmiJhE9isjJmQLVy0fkfBK0NB/EVxfK8tVW9hR/hhv2xeOOrMVfgbFXKzpXQFsorYm+fmBI4lKHhoye6NGFe+pxuItHn+Ej8kwg5qJwrBOP6rwlXbaJPA1ku7EhZmOzVdELPt8k6Rwf/1PLtDg=,iv:Fpe1dzf92Yx3LsK4wDelfueuU37LFloObnyumwxkFP4=,tag:CKu66qUL2soxrwurfBONLw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
