controllers:
  echo:
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: ghcr.io/mendhak/http-https-echo
          tag: 39
        env:
          HTTP_PORT: 80
          LOG_WITHOUT_NEWLINE: true
          LOG_IGNORE_PATH: /healthz
          PROMETHEUS_ENABLED: true
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    ports:
      http:
        port: 80
serviceMonitor:
  app:
    endpoints:
      - port: http
route:
  app:
    hostnames:
      - echo.aknuk.dev
    parentRefs:
      - name: envoy-external
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - identifier: app
            port: 80
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHltSjdRdVpS
        eldFejJkWnhJbFZkMGdja3BkSDJGZFpyS2QwMjd1Nmo0Qms2bUFVUDNreHk3Mzlm
        MWlvMHFWbGJlSmw3WEIweGg0a2xiWUg1ZXMva0RsN0xCWGF0WUtTcFpVZFFqcURI
        cEtuK1dlNkY4UVgxRFFaVmo3dkM2aXNjbktIU0Q4QSttOVNkVi8vdmhQN044K3NZ
        QWlJbnRXa2xjZ21XR2gweEFSb0t1d0Fla3ZMY0lERVZMK0FEeVJCMlduUVZjNTl6
        allxaFBORDZ1NTFFUlQ3Z1ZjK1ozNDV5YU9Ma21LYWdIYjAycXlxeVhOc0w0Ykcr
        VmlRUStLVzhxNlRnVnJmUEsvczhVZVdLTWc4NXMvSlAvdEJmTEowekdBRjJjU2w1
        bXViN1hKTFQ4U3lzWUdRTjV6SkVzQU5ZNXpjYVlzSlVWRmhBaVhXV054bzB0MXhW
        bldoM0tFckpUdG5qR2hpZVhJYnRUOW1aUDkxdzJyOWp5eGo4QVVvK0xQYys0cmRw
        ZUtTMjVkZ3MwbzVvaFdiclp4Mlk4aUpaNGtFSEQzTXJ5UTFvVFBmSWErcEU2SEI2
        K1Byb3h1aVV6WWw0Um1tK2pld3RCUk9ZNFhMUlNiQm5qTkZnSUhJMUxsL2Z0OGd4
        THFnbWpPd0k1L1BQOXFMSnprZWhPWmlsQ3kxaVd6aVdDS25vTGQxZHJXbnJndC94
        QWt1VTdwak4wblFxd2J0aENIbUI1ejFrOGE3VXl5TVJ3Z09vTmtZaWY0R3drNis3
        QXBCY1NGckowbkNPc2R6ZkZTcit6OUR2T2x5YmtaNWUvTzBzdHNGSjl4UjUycFRs
        SkpDYWJaWTY0eGVTWVJlaWYrWXhFWG9JS1haU1VYeEd4eWs0eUExRENwUjUvZmll
        TTNIQ0RGYk9icDFtMmJHejlMVEZwQ3JXb3piREJOVXlqSkhTUEpSWTNNMjlPWEVF
        QTNRaEYxKzVKelFCaElFNS9iaUc5VG93S3FzU2wxcmlHOUF5WDdmSFZPTDl0MUhu
        YVFSOGNSSzRPd2VmQXVTSkE2cFRPUUllMHJZY1MyaGxPY1pCWDFMS1hqRWtvNGQ4
        K0VzRTRuVFI2UDdqMTlub0lyR1dEclovVmdZY1FkL0FmZEYyNmxTamRxNUQrZVlW
        WGFlRzF6SGtYdFlMbVdCL3FCdnYxR1VCcVpEUmlTZnhSZzFYeGlHNUc4ejlBZHlN
        V3plWWhBUWY0L0FPYnFSOWpWWlFKSU9KTVB6UXFGNzRXN080ajFoWGVRazJGMmxU
        NXVLTlJXZjlTdVBMMnhhWHFIM3FtT1pOd3c4WWNtMWN5RjFCM0hJVEpGRFhHMUlF
        TXp4WHNINFVoY3h3ZVRiNWJEQ0tQOWRqekd6UGR1cDlCZmVicnRTTFhwL3ZsMW9N
        TkJLeGhOd055S3VCNEdKb2lzWUh6ZUJzSFFYYVhycjhKcVdnMUJOdFJ5aW9nT01H
        T3lLWFgxZkIrSzROT3BoMDJTNXJDOGVYSnFIWUpZcjZRTTd2elRRcjFNRFUxZDcx
        RUlMRGVCMlhMdnNyR0lHS0RPTVFpY2hOUHRpTGV1TUVybC9FMmV3ZHY2dFRIR1VS
        TE5pLzZMaVFuQU9qeVByVmZOSm9hdFdmZU5wcm53K21pMjVLRnYzZWNtcFc5RUhG
        OG81QnJvc3hvZ2lidDIyamtHdWxGQW1DWm1nSG9tOWhDa3JUZkQzQWp2UGRLN21a
        V1BGZDQ3eTllbGxaRHFndjQwLzFHR2t4a2JRZDBIQTBnejJpNTZsalV5UGJDd2pk
        YW1wRkg3YlRFbFBQRTQrM0NodERsRWNCMDk4enN2SWE1QWI5MGlYN0FpSlQ5OUJx
        MmRSK3JvMzYwcHBQNGFUU0hWTWVFWG0wRzVlQjR4aHRaOEExYUZPbDV4VDdnWFJ6
        Z1RqUVlTbGRWRTBJY0VGZU5lQXh4b01YYkFJaVU3SmVLSGwySkhoc2pVU0VHUQpT
        ZEJ1eFlPemVFSG43VHprcjJMWVJRaTJkQTVMY0hUVC90MzdDUThHajVNCi0tLSBR
        Nk9JcTYzUlhYNGZiVHA2bGl1bjdmc0xPZnhmMnVhY0dVSTA0SGt3bTNBCrN1mVBj
        P20IW4rq/RTfv3PBYmQUlGCjA1av+wpiz4usjdYrhFDlEfljzquXweJLNLyG7WeX
        gFVrGxjOnKFmwSc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T11:54:00Z"
  mac: ENC[AES256_GCM,data:L6s3XPa4fFmxWTAg3olRSfv61cvABqLgRZSwzJLF3/b2mFdl9v6ibHiiOOpGktddxBLK39hZqndcYnG65NOv5arhf9O+5eqYAh1D0hjXOPm1gXfR4w24m981UjW0KVbBk85PofZck0z34C+BsjW0h4hcNpp9beD6i1KO70j61fo=,iv:IOkRI92s0raJYcAtkNYxfuN6rNLX8xvilv8zxaNpUEo=,tag:UMwnhYrMK+mwTWyY9CbtNA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
