fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - aknuk.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHp4UFh2Rm5X
        aHhxZjA2QXRzaEc5d3RkdC9sOGZrc2x0V3pLZ1ZheVZJRDJOTUliUmFhYVk1WUM2
        ejArRzFIRTBEQ1J6MzlXUk1YdFpXNnMwdnBIUTFvWGc4d3QwSjdQMjZ6VlM3RUp2
        VmZkYVM4R1Blcm5CaUIzNHV4TlpTdUgyMTlHVkwybjJDUVY1ekdVVWZwM00weGc0
        VmNaV244MG14azlnTlJXdUFuczBFcUR3cjdHWFRzVUF6dGUvby9FSnNVQjdQaXI5
        U1FqZkUvemwyeHpJSklpOTl6WW5TRklBSXRuMzd5OG5Cc3orRmtVS1BZbEFHT1hL
        SFBsblVCakFKd0MvWnBtTFcrZkxveERsbWFLclBocHdOdnpaZWZRd2pDb0JHMEFL
        eUxINGwvU21CTXdwSXkxWCthSmVQUzliZW5Xc1AxQWlUVnFmak9oVkpKTm5vcjkw
        bUU4cG0rR3czWmNycTNLY2w3MytDamJ3a2RjRXB3bGd5WUNrT2lCazRUK2VWWUlC
        R3c1YzNSWXhacUlFWThJa0JPdWtSbmVmUG16bjJoK1hLTkZsOWxPejFLR05JS2dH
        Vm1GYzc5WlBzb2toVm1RZFlwRUJRQWdSbTk3Nkx4K0V2b3hmYWFmNjhJQ3dJTjhn
        dnBQeVZwaTAwK2cvQVNxc0JRRHJvZy95bjNreUVHQmJSL3FHR1dIbkZudTU4eXFn
        eDB6ZzFxZDQydXRFRGxCSnBiNzZZYjRNVmhDNnhGV3lDcTU0UWkvSmZMdnBHVStv
        YUFkalN3NmhNMFNxQ3NtbER5c3BBUm9Ecm1xSnExUWJIdURHRFczd0NYMXlGalFZ
        YzdJck1KUUhKWk1CSVpVYmtUVTc4M0FQWTBHYlE2K2gwRUhOdWhia0RsVUtENlVB
        aGJ5dmV5TWVvbm4vVlAyMjlpOXpnWkdNMXV5aHVEQWtFV0dPcjVJSUJOYzh4Z2NQ
        VHY3R29qKy9YaHRlc2w3SEJDUFpCeDhTWVJKM1dDNkJXcXlOeGg2WEU0NlhrLzgr
        NUNBc2xXWTdhRTRCY2dEOU1MNXRhVWRjNVZHN3llN01UNWVZMTVJdllkcjQvYVBt
        ZHJSeFFBUzQ1eVNpcXhqWkZ2ajZabmJZamYweHh1SDdxdUxMMG1HMFV6R0F6Z3dy
        WjBrNUVUeTVzWnNCVHJIRkd1em9NRUNockJNMkI3ejNZZ1ZacWVzVkpoY2Z3cm55
        WmFJbXd2amxONHdObWxzYzlFbXB3OTU1N1RkRTlaeEtEMXh1azZ2dlpEazVxZ1BC
        M1dNM2lzbWMrdzdmaXRmT2VvYlRJU2lQaEtvRkpwVFduRGVHWmVDWkZleVVLdmVl
        MDBJWHRxRUx5OEJQOUtOMWR2TEQwMWRwOUh1QjhXZ3ArVHRXN0Y3cm5qNFA0U1RW
        VGltMk5vVEx5MWRaTVNDT0M1RnRpWXRUVFZPWXVLa2RiSzRSeEVHK0tSNUZiQzJD
        SXRIQW1CclNKYmwzdzhLK3JJK0lwaHZ6RWNTc3U0QmY3ejVJek9ERWFpRFJxWE5U
        Mm90empLNUhwU2liS3lhMkJZVk5BZkttaGlGbXI5ZnhLY3EyZ3h3TUxSdk5wMCta
        eFpLMzcwSVVqU0dvNDR4emttZm9IL21yT3FQS0FBUXYrRVZsNHRJMDJGemVQb09G
        UG5oY1dXenBTZkxBRVQxckxIaXk2Ump0RDY0VWo3bk4zRm9PVXhQQ0haWE44ODhS
        bTFxS01KaGhnSHdYcmd4TEFvQUhEdkRlN1cvSWQzOENrUW5lSnJHVHNaOWk1Qjgx
        WVZrcEY3M1dQWXcyMkVsdmZwRk1nQ3JBRVB2MjhZZHozRGdBRXRqQWF0N0QzeTlM
        NmZFMm12OHJENktaVGRYMmN0WEFqYm1GQ0Y4RXZ6YkRCM2JMc3dxOEgwQ21EZ2gw
        MTB1SFNkOW9BUHFrUnFudFptTnRQVzRxNk1NVXYvRW1kUEYva3crQ0JJbjZXZwox
        T21salBYZ0pUNlg2OEszRzBUZ0szeVlrWVNPaDVKUTE1c0RFanJuQ21jCi0tLSBz
        amVIYVlMK1U5akluUW80akV1YzZZYnJTWmhSak1jRUdiblBOLzhEUFdRCmlrsbwm
        hwmNy7qVyiJWDTT/gZ2iq5iK9ZDBvhLZjdl7iHK4lWfGq5KvrkvBwK7s1dX2sZvJ
        RX6O9x+NsoLQ59g=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T11:54:00Z"
  mac: ENC[AES256_GCM,data:2LjlN12v9W8ecpBghuhgpgdPZL6U/I7f+d6HTmMcQzuDFWRoRwTwQSZ00zZE3GI1NKnfc9QLQCgd5ReUkQUiP0X/LJp26+fOJf1conwSgqgmlyihg6OsW+iwnjCcXHtSZrJqKEugG8Hcy16+3KuqcK/ZlocFMCfjRWuP8Yl8Z/4=,iv:E1FFzWFHxgH/3LSq7MvDNmJZCIvHm9DrZ5Vb+yaRbtE=,tag:NUMPOdek3e9YFeJzI3g8qA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
