fullnameOverride: cloudflare-dns
provider: cloudflare
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-secret
        key: api-token
extraArgs:
  - --cloudflare-dns-records-per-page=1000
  - --cloudflare-proxied
  - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
  - --crd-source-kind=DNSEndpoint
  - --gateway-name=envoy-external
triggerLoopOnEvent: true
policy: sync
sources:
  - crd
  - gateway-httproute
txtPrefix: k8s.
txtOwnerId: default
domainFilters:
  - aknuk.dev
serviceMonitor:
  enabled: true
podAnnotations:
  secret.reloader.stakater.com/reload: cloudflare-dns-secret
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGgySmd0WUJ1
        WUlEd0E4cTJSdkhRR3U4ejFUZjBabk44UVpyS085MW5IK2krSEhxanAvS2FhdmZY
        NWJFRHJGQWQwSTRETTROVmFtRHVZVm1YYlBIcloyUUNEUnZacjVORzRKL0kvckpy
        c1duU3AzelIrWlMxNENwajVObkxJd3k5K1JOK1k3bXFlT090TVBqSFQyMm9hQ0xt
        NlgrSFM1cWd3TGI0SjJKaDlnMTJGMW55QTltVkNpYnBMSDhZclFTYjA5Z0xLd2tD
        cnFVc0RXMEU3aTlITHIydzZ4Vzl0Qmc2eWxFRkphTEo5NHo0QjZ1WExST0dEam5Z
        QXBmZlk3Uzk5VDNuN2NrNDFYZTVnZm5EOEtkT1NENGNKZVZPNVlpTktJMVE3c1Fk
        Q21JeXN3U0RHbUgzY0Z1ZU8vU2pDWWZrWldXckJqcU1QTXNPQzVmV0RFc0xoSUdr
        Qkxaa1Q1dEd0K2VpbzhaMWlPNS8vck5jNHo2Q3NTYnpsNU8zbGlVbkNLc3ZtUHVN
        M01JM2RPOGhhcFFlUUU4akhhalZKcktwb0ZqU2V3OWNGWFdlNlBHMFhyUTRORHJq
        aTlFbXhBa28xdmJtcFFxVTBPVFZXT1ZweXNIdHF0Vktmb0k5S0lNSjZPYkIwWXhM
        clh2cjRKZkZSekpIKzQrTExNV0xZREdjWU9uUVp0cEh5eFl0Ny9sMWUrMkR2Y0No
        ZWNmTXB3clJ2K0kydnhJOFJMNDRzVzFqTGRGYTVlK1BGeVQ2dkwxWXU4VExuMWJx
        Vk0xM2xRVzg2cnJZRXQvR2hFZ21yV1hHUWx0ZDU1UnFKLytOWnVEdUt0TFNBMUgz
        Z3dCanRITGltYkdYQXA2TEJkOHRqa2dDZytMRFg2U0Vja2ppSlozNHpuNVJqbjNR
        ZXp6dStPdnBwT0VhN01NVWt4bEJhZVdEZkU3d0NvZVNXMjd4ck10RVA0Yk5KcUFB
        ZUxkZjZtci9LTCtUeVhDZkVXMFBXOEV5d1BRRkpxd09PalIrQllGSzBLUXRCbzRO
        d0djVWxSQ1BkcE1PSTBTK3I0WENKSWk4VXlsTForandDWTVESDdFS2kxaE9wQjRQ
        YytISDNSMk1KZ2ZZRXE5NU13ZXVaQ1NBZkV6M2pFOEh6U0IyUlNRZExUbE5KaVhp
        WmVHejJvWkdkR3lNaHhNYWRreTZSWmppc09ZcXRrQWpBWFJpdjRRam8rQTk1bG5X
        WjE3cUw5WjRKUUxvZGo2c0ZyTUg1VVVZTlY5MVd2VTBvbHhyTGJ4aENoTzBxNDJY
        QjZMRjJ5UTY4eEZ6WnUzYkRjRDhCdWtRZ0J5MllPanhDUUdqTkd6TkZSL1RQdlZV
        Y3pGMW1KLzJEWnhNZGlVcGtOV2U1L3QzV3IxQnhXbWkvekRoZ3pyUUxoS1pjS0Ex
        UjRBUXJpUTlueGRuRFJnZ2VORVdrM1NMQmlVdW13ekJxNWVrQWtoamZVRHN6NFh2
        ZWlMRUxkR3RQQzFuQkMvclpCaU0vWU1yT1JKazFDbnZWcDRXeERnNGxGUDZJR0JL
        Qkg1Q1N1ZG1wQkdaOXRkei83Rnl2VmVSN1dKckpRMU5VMzRReVdUcVpyTXYrRElq
        S0ZwckJ5RHdoYmsvWGZMMTdkejE4bWw1d1h0K3V1SFlKTUxEdnRWR2hNRnN2dXNx
        RG1FZzY5WHZ4MHpITCt4NGVTRDgvTUhuWWlrOTlhZ0FYUjV2NzgzcGF3MVBRMlhG
        ZFN1TDJoUWdHM3dzNDhzWWErdFBaZWFPdXZQbHQ1bmU0K3ZkL1VsN1picHpuK3B1
        SGtmblQ3OThJYVNydFh2ajNYZldzV0pKRXNSTG03TWNVZGV6SGZBTmszdXNUQ3k2
        Y3RQRmgzLzM1TUpFUkRSSjZhNlhUUmJWZlJCZGg1YmhhSVRMZURGSWlFTnJtbUN2
        aTZQaUMwR2RlVXlxaDZ3dVhEcnZJTjBNUHE1N29VNzU4b3NsYjhjQWR4bUxlQQpj
        TlVrT3FvUTVKOG9rTTRNU3FLRFRHejFPeDZlWEkxMmNvZndQZ0FET0UwCi0tLSA4
        MXFhZ09hNWx4eHMrbUhnQng1ckUrdWNsRDhsb1FjQ3o1OEI5M1RFNk5ZCu0tpjkO
        B8afyOTIrTfpD9haHf6UvWl81LASVswCJsyDuFteKT5Py4x+ujWsH728fMoj3hTJ
        9UlvMvFAOkbl0JQ=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:27:43Z"
  mac: ENC[AES256_GCM,data:xOR0RTxO9DS8azKRBnCR5TMWo+jDYj7AYn3wSmEkylR23Z0ElXGxQPbfCxva188plWmgv6KGNad+JWx+J21NqCldLmkbGkGs20RcBSEEezuQ/1u7Mhlc997yNTXWfEoIhFyx780lgZRdFFxMRDIom7fYW98wa/+xwJgo2owwZzo=,iv:2gf5IpP05l1whPmHpGJLiM6h2l3gg9NPUwppciGqah8=,tag:wmvIEvA1xz9q6n/6HBe6tQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
