apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:j2Jd,iv:tPgwPyfDcAJTBQNd6x0hiblk7k0tG5+OJ8vxlY1Qvn8=,tag:JzAOMxG45qefxdFwdfKx3A==,type:str]
  url: ENC[AES256_GCM,data:SR72vLWsWrStHwPif0cXB6DLL73Ie1fDUVFwuWWcVFZVI1ZO5GQTzsLf,iv:EFDxo11tZ8TFevkSiioO9tNQzhhWFKF/Pn3KXKfF320=,tag:x7VMT5+u1AURD3ub1c1GUg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDJzNEF4RXIx
        cEtZczlhWnpNaHgwQkU0SThYNUZvZG94dElucU5Tc2xVM3Q5ZlBTWTdqRmVYSnN1
        NnE2eXM4enRTem9ZR2ZEWDU0azlkQnlpT1hVYkRHc1E5ODd6TWRWUVF1YUpJZTlo
        TkV5WWxUbExtNEIxb20wWEczNDAzb1R3cS9meTFJcGRWUUljNFJmWUpXZG5TdmRu
        VWNVZnZjdUtaRjhHUU1xUmxvTGxzeFppREYxQVRqZytkV3FpQk1xbEtNV01UZ2t2
        ck9NUUtiQmxqSEJLeGUzNWdrd0R6eit2UDMvV3lhb2xCTXp2N2dUVGIvVG5oVkY2
        MWJhbGxTbEJndmV0d2RxZFpxZ2lKdjlqdDBqRy8rUXFNRmRjdnhqQlFHMCtET0hH
        NFBNVTFOUFd5WW5ieUFDYnduRzBVK0dNNFlVQ1JVWVJrdVdNdnlXVHdzWjVjYnBQ
        c2U1SGkvTnNUeE1iVnlPUG1YU0twYnBJZEtvSThsZzcyMDdKRFg4WkYwUnRxaGFO
        Y0RlRlR6V04yVXFCeGk0b1M4akY4cWRETURidDNaWGVBbkQ5UFUrazA5NGxBWDJt
        emV6VTkzaFpkNFY2NTVlZ1liZ0NsQU13RHFTVElRTXZHUEdxTC83Nm9FVnYxcnFu
        UUwwNUo3czFqc28zRHhmSmloRHRqYy93Q29hTEhxYTQ0bktZVXIyRXcvaWgxSDFu
        ZzZTSVVRcnMzMHdFUC9UTmdjZGVURUpFTmtaNWx5enNBckduemNzVDlhK3pmTU5E
        bnBXTWRNdHNmRCtlYnZxVjVsK202NktNcGw3U21acm8zMmtsbWhuU3JIWFY5QVM3
        Z0E3V2VnOEtTbG1wY053OS8raHBtbVYvTXpXM2hqdldDdWM3WmZ3eS9ESGlhT0Va
        N09FLzN2SE9VZCtMb1dzdFB2cDZhaUhJRWhaSWRpRzA1aVlLZTZrZEtKcjZBRG9B
        UStrZVFjU2xvN0tjS3NJUmd2TmJpc0RzVjhwRThOZERsc0pGaXBlQ1VYazRodkFk
        blRSS0ZBeUt4NUE1a3JUK3FlNnM4b25jMUw5NHQ3cDdIZDQ5bmlKcDZMS1V3bnBx
        U1FYZVhLZVk1Qm1vT2l4cW5DMDVyaVFzaWRXTU1teFdNZ3YxQTVZWGhnVy9qLysz
        M3drQlVJbllRUmVzRzNWdlpnd0JuZFRiVnh2QnJndzNEMFNTSUMzbnVJL2UxRWdN
        dm1WSjNwZVlKamNpQm9kZlV5OG9aYTdDVUNNTEJ6WXIrcTVLcmtaaW52TVZFeEJU
        VDIvdW1zYnBJYmxIVDBOQW55TlVKYXBoQUlrb3ZDb095cVJaMUg5RFpEZG1qb2Rp
        bTJreENMQ2p5R20xMGJqd1FFNjRMNHNLRnI4TGVBZWpwam9LaEgweHorM3NrUWd5
        RnhVWXE0eGhqZnVlaFFJNGlBOGVRVmloSzUxVWZ4dTN1NVlaVUFWOTZyZHZ4bnBG
        WENOTDlMblJRZnh4RW5pZENReXNSMVptNDMxR05uNGd4SGI1SC9kbVAvWEhRbllj
        d1FDYkhZNFUrbGJMdG9QQzMvd1F6WU8xTUQxSUg5UVZwYWY0NFpMUlFKTXNqQVFV
        OGwwbmxKamNsZlZvTXBIM00yOU9EZ3o5cGlIcHhQTVRsbytkR2FNS2FpenVBWk1P
        OVFiR0dJeGNRWE5oaFZPbFJDb1RiY2NWbVA2N2E4SGNwb3VPWThwalArdVdtdzFi
        VGc5NnAxZUJ2SGkrbDhIWHpkQ04yY0pOQW5MKzFaS2t3ZVJFNUxpbVljbk9tRzdw
        QmxieUlxL1kxODE1YUcrZWdkbUx6QnVvMVRhUzY5Vzc2dHplSjBabXkyZ1hTOTJB
        RWE3aHFFTjJWWkZCc3c0OUdYbGswZTY5RU5pbE5qOHVmUk4zTURPTi9Dd3IyOXZD
        TDYyRUc1Y2ZiYUJlSUVzdGNra3M4OGN3RDlJN3Z6WURnZmtFRWFMNHBNdE5CQQpY
        d2ZDTzBEOThUUHdFMmxpbjdPWTZPeWVja3RTckZFSFZvTmtLN3Y0dU5VCi0tLSBS
        dnVYMDN4QjhKYWRrTFZMd2RPWWJtTlJNcjlTUk0walBkTEtOa05zUk5NCnZya2CW
        6tIwu8cO8C4NqVk8R5fy80Mm7PRC6mHAUNHG7j7tpSVJpeotOLZJFvz0uyqaRXNX
        t9TF97D4z0ijsS0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T15:30:57Z"
  mac: ENC[AES256_GCM,data:iruMiNX7TTtFWvchRbre1GX3Y5t8Yo1mM62vtOOuYPIyYLW9vnZmNF0EBHpkO5Zrt6pRXjVQAzlNTmXKlY8GL+AKV1lQI1zn7CmrLin0J9FVdwUxX5tIXtexA6OEUbYxzxFx5btwJS4NKpLC7bi60oTuClBXDkBELiDvQVtBkJU=,iv:SjgkdSFylZBkZWFSFRcYcbp2mYALA99sSVpa7gTV5tI=,tag:fZTNlohsqFDwN98Exm5FmQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
