apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:kFWv,iv:IOOt6WbwPIa20LRJEiWBXr5juafkJC5vx9xB/pu5rnE=,tag:dQ9HAzepmzkIgfp4Uh9mYw==,type:str]
  url: ENC[AES256_GCM,data:ExflbWBoOS+07cJ4ynpsaqe3/TMzTDXIbfjv9Nku8CasNtd2G+83h99s,iv:U/G9FRhwr0qi7PtGlMPTADdKHp5e4XPl4i2u3QDPh20=,tag:PLLKzp5SLnzMcRUZYBRg2g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDZEQzlNNGlx
        Z2NRRnhmMmNEd2MxYjBTODBXbS90ejFCYk1sL3BDVG5kUU1rUWtad0JqWWdFRTRL
        dEhMcW53N2VqV2phWldvNzJjVnJ5K0x6NVUwNjJiMkllVktSbFNPemQrdTEyb0Vr
        a3RXN3hnaDdOU2RrSG00S3NRZ1hwSnJQK2FHMCtoaUNnWVBmVE9rMWwvZzJpcXhy
        QTVYMmE5eWtGbGM4RzFTKzlDaVh3N2ZYdDZVUmovMUtwblIrdE11Um1OWXBybUVw
        Qk53VFNDenFzVEpyRWplSE9NcUZFeEZWZFM4YTZHN05Pd0hJd3hKdG8vank0dzJR
        U2RJTTNuaEtIcWFWOG9BdXBjKytoSzV6T3FkNHR6SENPUzlRdzUyL29pZmw1dlRz
        RHN1YW5nMTViVHZENUdXN2YrZHA5Wmw3bCtLSGp0eWJYVTkyMmlwdzkwWEFPR2pM
        dXIvQ1dYZEU1Z0ZtaXBWYVpwNUlDN3pkVFNyTjhDaUxKeUhZUUloNEUvNE9qeGpB
        RjNoOGIyS3B5SmxpbjRYWkxHaXRKYkJFMXRYVHlRek5VeXVXVGV1WGg0aGE1UnpD
        amFJS1p6RThPUVdnY3ZWQUhmZlZhRm83SHlwVThJYXRDYWQxNVZ3ODdLS3hxQ2Q0
        M2ppT1RGdGJnNENOS3gwUnRETXY5VWMvS0VmalFzYnRCZzRBcE1XS25uSXB4Smp4
        MzAyTWdoWTZ2T1lweW5JVXAveTZkd0JZY3QvQnZCTGR3a3FkY3FySTFWMDBNeVlR
        U1FpTC9VdHRsVWp4OTV2QXU0MDdFbDAyY3BoOXdXRG1TbVJPd2ExZklrMXlPbktJ
        RGNUMytDTmlPNkFIcVpHclJWTTZhdnQzeC9SRzNPcGFwUjd3NkIvK1NxejNkUTYw
        UGRSRjdnNXRZSTU3M1p4d3BWSElJVVRjeTkvOFJ5Mld5RDZCNWZsUDl3UU4xaUJC
        YThYT3dUNHBSYzA3RG9JeHRsVFlpVjdmU25hc3UwMy83TitQSHpicjBwQWhmS1Fr
        M1kxRHhvWGJVdEszTldHOVBxOGdWRTNRMWUvWFNET3YxSG5tdG5CUkhSajZyOE90
        ZVdhdkVDZ2Vnc2xVczNLSWhoa0xrZFBWTWM5Rkt2QlpQZEVjWktEUTF3Q0UwZDVS
        cE43N0dkRFFaV1dWM2F1YysyNzh6NitjVWg1aW1uc1JPbGtNdDJpZisrWUF1Ykxt
        b1AyNitlZXYyMzBHMkZnYUNPUDBSc0dPc09lczRVYUNhNHFHaG9XeWhkRFowZXpw
        WmhYVDBmb1V1WHFKWmdsb01wbW1aUEtCZEU4dG5vSW11V05Xc21DVTl3UERkOEdl
        YXUzSTVaUHBkNWZYLzNLZm9NOVg5TzhDZm1kenVMTy9WNE9UVDJqWnovQ0RGVVkv
        bzRzRldYQTBlcmlTNEVRQVRPOC96VEVtRy9LaTBoWTRyNklrdXVCWCtkemFZOEdJ
        SnVQYXptREJmZjRCWnZpaUVxWEFaK1RNNnl0NVhBM3o4V1BZeTJjaEZMVUMxRk1F
        Q3ZQZjhwTTVNUjRoNzJ0WWJ0dTBOOS9rTjRVRXU2TVMvOVFmd0pxVDB2NnNwQzcv
        UTJhWjhtRlZIaGhzWjFrTzcyMnJYM0oxay8wZkU4RGFvbExURGhxSjcrTjExb29R
        S2l6ZFNSOUNBNlF4bEtjY2FQZGZ2UkdiNTZUb0lNV0s3bmZtdXQzeFBYc2JUcXRw
        LzNVcW55bjJiUkNuOUdVeEVkekZzK0pFVnphc1FEdElCM2JncU94L2tnVG0wREp0
        S3VLNityNUh1U3oyYXRJMTNLT3RDejFBYlJ2cUlZVjJSNC8xNWJ0dXlDVXFNSG9j
        NlZzZXBuSWVMUzN6RE1vN0dOM2NUKzhYV3RVRE5PR29EdE1EU1BVWG9IVzFTWG9C
        SzJUdXpFWDNWMk90ZWFrVXg0akJTSEg3aHhPUFdwcmxETFk1bWIwUkpaT0RHZwpD
        aklCcURWNlN3OFVib1R4cWQ4NXhaRFJoOG1zYitBQmNEZ1Byd1R3YzRJCi0tLSAy
        WC8yVlRodWY2bjk1TG42Sk1pRW41L1diZ05YUVdKRGtWVlVPOUJHTFNZCuFt6fMp
        MIDDrRO5dzoL7h0LAPR8OG1ux2+bNdJvt5cCxseX39Y975s5VZncxwH47ksg7VLn
        3Cuf0xcXuUTs4P0=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T11:53:59Z"
  mac: ENC[AES256_GCM,data:bGaUmILh3hq0akK/qAxlWXhcyKvH7qcs/iWIGY4kI96cVkAJPwuWqANX3B9qMBu2kAHXQO6I7bOKl728Z+evrTyhN5MtYkj6VGmKRAaRSPaUocaeS3+Xj1D1KYxEKE0aWHbAi7NFNqEr/AJz2Zmhbjf6v6xzPzOoKXsKfD6FgSQ=,iv:fz9DHxS9jfUzs9cxhKnumAK5QMJnYYuJXvv1cixZWtQ=,tag:+2zpUIQzCyfVAN336BLGbA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
