apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFB1c0pRYU1i
        NUtraVZQSlhDakJzZ0pGcnYyZHllWjFJTzdlNnFEWnZsYnRldUVoQlVRT3BpM3Fx
        RUhlNWZEczVtVWVVUEFsSGl2SGdRTU9Fd2pnSWo5NTdFZEQ5cEo0YXpIbWZyazZ6
        L1kxb1VCMEhwb3NwVDRKdlNxMDZjaURodGdSdmZtN3NnVmRYbmtxZk9IT0p1Z0Jj
        OUNEVlNZNDM5am1qVytQWnVZcTFxNksxYU9NZmN1SmM4UDhyWWR4Q2tGb0VzZjZi
        ckhtdnh1NyswdVFEb0JZOTVqemszWHl2cHFxam1NVzBjS2c3QUxwQTdHMjZ3YWxN
        N0pvejlEeUlyY3hDTHZqWXZwWW9BaVBrRDJEcThpZWhINmpnY2t4WUF4S01GaHIx
        b3lIaFNnVHQvcTBhUjR6dXNVM3lhd2lnSTFiVTVHQlRZMW5PdGYvZUF6Nzk4eWNl
        UGgvME5mSXpOenppcEN2d3ZCMUZOcFNHMzZEcm1LZ3V5NHFxZ0c2RGNodUtqK0tY
        VnNsM0dodzNEVVZhTGo3b0ltQlN6RzM0RmNsbjZXdUR4dmxnay9PU0JNcHlBajVV
        SE5VOXZ5eUNlenk4QjdNSTRVY09kdGdKeHZRNy9IbkhyQlU4QUNrY1R1RERkR29h
        QWIrTDg5VGZxQVZEbTlJODErdGxSTWlEOHl0ZFNXWjZONkd1WDBYUUFlaGV0aDN5
        Tk9wUkpobGNjc0NqSTVtMzhYSVdxdnpTa3U4RGdSb3laUGV6UkZMYmdWTUdkZDRv
        L0RncFFwY1lJVi8vNzdqWnM5MDhRcUFHQU9LR0M5dDBab2Jtd0JyOXNPOGVJUnda
        QS9sSE5XcVVmcDZjNHB6bThsZ2loVnR6VXZkL3o5dnFPMVZYbHJydmd0RUxYeWl4
        dklhMzJQOHdQRU1BR1hXUnU0eUtjY0Q0ZG1xaWQzVjh0RThoWGZ1bFB6ZUlkY3Ro
        cSs2Ukdxck1QYzMxOU9lSW5jSXJIRGlrNGFVWm9vRXpWUE90RnBxU2NqMmVycS9q
        UktQa1ExOUR6WVhCQTJGbGRaQThNaFZPckxLQ014bHpPeXJrZjdSdjNrZmVjRkJR
        Lzh0WlpGelAwS1FWdHJYaWY2cGhkaTlDYTI0aC82RFdoZjJ1VU42Y3YzYWdZYkY3
        dnhRWlRGZ0hTVzFuL0R1SmdOeGtWUjF0ZHZVNGFNbmZWR1ZBanZLQ3EyR2xMcGpY
        dkVLcXZ1KytEK3NKeUk3ZDdibjRCR29sOGJMcGY1OUpkbDdnY2RSTkxPNG1DeWFy
        Q285TXVTWEc1am1IZURHWXZ1a1JvY1ZjUlRlTGo1SDFTaGJmbjRaRGIvWWhxZkpB
        NEg0bVZOQVA2RmpqRmtVSWR4Tzc4NENlTTN5dUFxWXVLV29rOTBMV0k4U3ZGMloy
        bGt0cE5mc25HakEzOTZiY3NJZFFkVFlFQTd2U1JuaGhTSVNZOHpJaW1jbUVZbW5O
        ZjdiTEJZei84dEFGNkQ5RUNDamNzZ29admtFc3pzdlhKdHpIWU9CcmpJY1pFUS9O
        NlpiMHNOOEhDL2hLQnhJTzNaM293cWxINDdTWFd6aTNsTmw1UTdHVlU3a2IrMUND
        cE5wN0dWK0JkMEpvVFJKNWV6N282ZFZ3OEJNSHZ1S0ZkbGptVzZEOHcrMGFzTVBY
        M0hrLzdmT3dwb0MzTWNIKy8zcHMrbXh6SDFEaG85OUF6ck5mcHppYlFhSnN3RDZ2
        Q3pWTTUycDA5SlR1aXhIUEsyeTBscmU0dTFDdFcwZ09Zc2Q5TXhQeGFVRHVIa2t6
        ZE1VTFVVai9zMkIwTEQ2TXluVEtHZ242dUdobk90MGFDQUticzZ1RnNZYzFOMXlv
        QmpZMkEwbjVJVFZHaHJwOWprQWl1dGR0eno4QVhVUTBULzJnbk5LWnU1WDF2TmJq
        K2R3Skg5YVdhSDM5V25BU21yc2VkR3RBWlpXbWsrVjBSR3RFNC8yb3ZWckNYUQox
        QWdBNXZUK3dDTmc0c0ZIYTJVdmN4OFJzU0d3T3RVUDBabUN1Ylg0U29nCi0tLSA5
        NXQ1TGtHY3h2R1FnN1I1MjFUeERIeWltcWhWK1VuQWtjMzFLd2trbGxBCippOdRE
        7fjmJm4jAfLoT1+fPcOyzOowXl1WEcTx+ExDcC+N5aJ5iUKbPHd8VJTSdeRkEL3+
        qXAltO1gCSZkecc=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:14:28Z"
  mac: ENC[AES256_GCM,data:TcH3W8fAu0LCIt+e8e3M85wKRbj7SKgr9M3wb8GQdB+T/ZUjnaPIQXX7AS3NsRqC1bw107C5V8fb7YzX/H3u6ZNMGiJgwdo9+3F1+9KCzGdGuhYC+OOkHdXtmympz/ybKpky9E93YM8CFPBn047gdL2PrMxpy/mcVniINiei3pI=,iv:45MP1gr3fMcAs+GnpaMWx80GH1BKj96xi9F2/QRwUb4=,tag:QvvfAVQ2D8PcMdud5By1TA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
