apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHpPS1FDeWJT
        dlVxNFZvQWRjUFRsTldJeUU2UUpMVkpSRTJtL3QvMUxPY0ZMd0twVnBHVjY2QUlm
        RzNHczhZSzFzNVpxYlk3S2RvWWFzYVBqak1RU1JvSVAySWYwYmJVRWtEYTBXWEdw
        UkRzdGp6SUpNQ1lDUHhrelNXcVY4MmdSYytBREJVVjl2YStHYmpLNXl3Rzg5VXJT
        NXlSb3NGQ3JsWVdUV2lCYzJaeXhyRVA2b0tRTVVTa2dtSTQvZkk3SGN0TU85dGRa
        WUhKVjNUUEhKVHd3TkpwREhrUWhDN2lXQ2xoSmdMU3MwamovemdJUWJkcnlVSUQ4
        V1ZtWVBDQWIwQW1QYVFzSlZBcUdIVEd6MlNMajVKN0tobWxvUzlDSCsrRXN4TkZH
        aVRWQWllU3hjQ3FncnBtOW52VWkxMURHQlpWeEVkWGtRUW5jN0VIbzRoNTAyK3ZZ
        VHZabC9lbEJBaTExNkRpdVVzSU0rNDZsQjZCWUJXWjhIK2VPVm0yZm16OVJGWmRo
        WW5KS3dHV0UzTTVDc2pPQ2ZpZFNFOEdoam02ZlNhd0lIeU9KNHhVOGwrZDQwR3Vl
        YU1BRkthakRiQjdIRVc1OEZTbjh2L2pBcmN1SDJBWTlrWDB0anpTNTRpOXFVMEkr
        M3RXNitjUkFTZENCRkhpNGR6ck5nZGRLOGhxbU1rSzV0V2tDUS9CZUxhZmZNZzVV
        eXBOMU1lc2VNdUhmdDcxVWQ2bGd6UG42dlF2MzVmb0theFlQdGp4anVUVmpzVnFi
        ZVIyYjloRStMNmszWE1TSDQyTkpkLzBSaUNXcjZueXVLdFZjYlE4b0d3N0xERldv
        RXF5OU1yb2JYKzhtWm1XeWdXMEZ5Q25JOFlyRmZ0bStuS0ZaT084QWYyN0loNWdz
        MWNjMVhqOU16OXNvM3FmUFZqdFJwTTRaa3lzSDVaU2Q3ajR4YU5aOHh4STJEb0c1
        L2JLRWcrNmphSDdycFNyRTY5K2Njbk1DZ1l4b20yTEY5ZGhySUN5c3padnRRRFRx
        aUxOK0cxOVh6OVhPZGUxZTNMbDcza3M3UTZCTThOcHpJbFRtek1WZGNPdXNjbDZC
        RHl4UzdDcnh0UWRnV0pjUG8vWGY2a3pNQVNRNlExT0N6QTRzS3FndVlmbzNIcHAx
        cXFrQjEwcGNEZzFpWS9Uc1JwaDlJeFFkZ042Qkd4L3JDVmhlbEltbEJPVVdhK3gr
        KzkwZnRSdHJPQVNBMFlDdCt5UlhlVGRkMEk2anJwdFFsY3RQSDZDTEgvbnNjaU1K
        V01aeXpDaW1MUUJibmx4R2w1ZnVwVjFNYjZQYk9DM2FidUt2ZmoxN3I0VnVtR3dv
        V0hlTTVpZ3dnNEZiS2NmWXFLeE5xQVQxbW1xcVF5TWp1cmRwVTRjcDZ2N0ZJNDkz
        NlpiU2ZrUS9YU0pPQXBUSkJRWmxzU0JQOVZQaTBQYmJmN1NzcjdoY0xOWU54bUlm
        RElMY2hqaHczZWpvbU5nNHVKK2xYSEsvMktHc3ZyZjVpUUtSTVRmbEtmTjBuWGc2
        UW1jNno4dFpMbXhTMlA1Zm1KbmJDM2xneTlncjBYVmx1aFZudWI1bm50WXlWd3dP
        bXQwbnZFN0toQUwyb2RmS0xQUExWV2lUa3V2OGZIYmNYVmE1cUt0d0NlVUc5UTYw
        ZFQ1a3BSU3UrY0VBWTdIQUdwNWVlMjQwVnFOSzlubElXb3VxOStXTTVlQzloM3JK
        c09ucHc4U1FOWVU2VGhBdlpMQ1VGdWIyYVhpbU1OVURCZjQxMGV5WmZLR2lGL28w
        dy9JSi9mRmNmTzRyN0lJMFNCOGQ0cC85TzM4anFrVitUajRXM2dGL09aTTh0QVdC
        MkFvcDlXMjRWeUpJeThVMlo3OTMwTkFrVTVRU29uQWNLei8yL25LM1lYWnA2VlEy
        T3A4QXJncW5kdW1SZHBBK0tFNC9mOGFyOXJ5MVhnYjJvNFpVK2FvanVNSnZLUQpx
        bmkvNm41dUxySC9pOFBEM0tuSmZiTHhGTy8reGV2SlVETmJ3V3hkREJ3Ci0tLSBS
        R3pCOCtjRmxnSXFSL2xsK2Y2VSt2SWRZUE1jN2pQTFdLOWtGdUs5aUZrCsAwHwWW
        CfC0Jz2F6gt2w9/GCFwbyZc/UYl73hngmjLPSFG1GtrH/DvLbM06O6IFioA3A86X
        u5i+ObY1EUKqFqI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T15:30:58Z"
  mac: ENC[AES256_GCM,data:uhXn4wFjdzAfq1BuAkiPZr5+7KNZWlgJ8As6RDYmhja7mT+xX+xIrbWXvHEGiFi9+YR1WMWizes1bQ5AphVZSDanSgUtimo1B+q4/4AAQQuwQFdXv1BxAQMGufq5xgGQTtQOJ9K5z3Xs/uMCy33wWMKyL3zU8//9IOyl/xH5NKw=,iv:jQC9dgr5kpr9aoiHBDc68yC7m9YZNkvAdTJM8CeIo3s=,tag:r+Vqo3Qko4zd2EDmeiRYgg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
