apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    privateKeySecretRef:
      name: letsencrypt-production
    profile: shortlived
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - aknuk.dev
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZVK0JHbHhk
        ZWRHOVhBVlZDWjJpOWQ5akFhUkZJL2RVeVFqSkNqVmc4UGtTcG9keTJmZURIcVd3
        MGNFTXlhUTR0ZnlvUG02eDRKMS9WVlB0NWMrZGJEK01wN08zeHIzMlArUG5FTkFo
        cFhuOVh0eEtFQVR0YzlLaVM3cTNUZzlUQ2R0eHJCQUdVU25sdFJTSk9wUWcvMUFX
        WnFNdWx5WnVqOG5ZV2xPSWg1QS95bHMwNklZYjQxNHY0U0djKzgvYUpkSUJISWtU
        UkFaVVV3bGJpTmJTTWVheTJWQXdZOG5nZUg0Q3lkYTY0UUxnVExIUVNkblM1bDFj
        bFVsUjZJTFQ4ZUk1TUgxdytOZnJrczJwK2lVeUtuRVozSzNkWmFCVTJxUkF5RHJY
        UjFQaVp5RXJBakRES3hxa3AwOVgweVNLYUVEclB6bmhBc3hpNWVzdDhEMmxqMkt5
        ZmZUdXhFZmYyNG9PZy9lZlZaVXZLMjRtcnRPL2NyMzQ0VVRuU2NTV3hrQXZPMzNq
        RWkzeGVFcFBHRVJYbnM3TnFzT3lxVXRKWVdZVGdXRThyZUJKTWF5MkNmSTlLN3l5
        QklpWnh1ZkViU1dCNkZGYWdEK3hXYy9Od2NwKzRuOE5ycnRCVTh0TXBZc1I0UnpX
        ZXFqaTNUL2pkek5wT3A0KzVjWjQrTTNkbG9rSk1TQmUwdHlmOEFLSW9YREtxTEZz
        WUVRTml4YW9DWWFwaTk3NHJCeTJzeEJzYU1aMEJjT3U1R1B2bnRPcnZ6TzIyeGtr
        TmhPRWxOS3cydlR2ZUg3MmJNVENBMkw4dVdyT2t6dVl4OUpHNjZjYURmM0JqYTBQ
        bHl3dmtUOEgrUFNvMDhjM3BNczhrRzJramxIQVdBUGg5dFF5YXozeDJ6Q3ZNaXBk
        SFVBRERDTG0vNjNqbytqTlB2S2lJdENrNjNKOUFTYUpjTFFtRjlYMWxLSjRvaysr
        bEc3ajVPWnpBazVGZkppTkhNSVc2VFJOQ2x0UE1PQ01kVGJvcU9CSWpNQURlVnNS
        SlMvTno0YVlQV3hQS2lEblJCVVNLVlFFalN5dGQvdmVaVlFRWFlwa0o0eCs1dFdT
        L1NGYWc1YStEREp0TGQrblg0Tk5EVVFRUVlOZGQydUtqaS9hQTV3aUtXeVBjNUQz
        YXpGWnpoM2dUSUdmRGt6WUw2UkhQdWg0ZnBHS3BMK051amlJbnNLaEZmKzlSMTNw
        a3RvQ1V0MlhFQW1ua21kSmJyOG80Vno0MkFmd0xmNkNrUDREanJQaGhiS3ZjeSs5
        T3oxRmFjWVlST0RuSTAwNTlCV3pwL2U1T21GNS9lTHZXRm9nQnl6SlVYeVY2b1h3
        QXV3Ni9uNWVWWVcrWndWLzBEMVM1KzdNaVNRQXFNZk1vWGhqT2FubVpwaisxYTBT
        RFhkU3E3QTJTNjduWXJBbVF4MzAxdkhPME12YWtPRWkxblluWktrUE01djVIWXFM
        YmhWUzVyNmc3eGFHY3Nhc2xhRlhYUjhsUkNBNXQ0cVZLWjRwRC9CNGdVVGl4WEFB
        U3VoVmVpZ2h2NGE1NURmeFl5Y2JnQzN5NFhRRk83eFh2QmtkeS8rRDd2bUFVUmha
        TWhtRkZNeXFVejZxWGdSUFhyejZjTnBCcGMyQjhWRzUyV2oybXZxamV1TUFrcHM5
        Sy9PK3lIRzQraTllMjhVU1ZWTEZBeTEyVGNVaWhLaUw2L2FNLzBVb0x4Z0FwMWN2
        d2x1SVdiOVpnTlNleW14YW8xOERTUGFvT3NLWEd0RDJSTDZ4OWZVN3lzRUtVV1Vw
        WThPVEhtcmo4WCtJSlI3c3ErY1JsUGVOQjNNTFFNdnU1cEJEYUlXd2oxcnJ1ckJ0
        TnFhd05CTnc5WDBDODdQTFZ1VXl5V2k5c0Nja0wzY3FFMkh4TjlKc1BaUzNtZFh6
        YlovVDdpZHYxZTR6bmtnZmc1djRuUDQrZXlwLytFekpwWEM5ZHdMVXNRUlBjZwoy
        MS8ydVIxYkFZOGVZWkI4ejhHRTZ1TUN5dUhOMHhtRVFhREE0dWNJVFc4Ci0tLSBD
        S2E2RS94QW1OZlVuSHgrVCtxL1hSOHAvSEFJK0JMNEtrRHpjcC9IdUdRCiODypyS
        XYJO2KT9kO9JzmaeNlOI9a28wXybHq9xIPrwHe7G1tIpOB5CGTTCep4oY6pFLg1W
        hyQ4Agm/SugcknM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T11:53:59Z"
  mac: ENC[AES256_GCM,data:eThvzcvNCP4kuyX2UMhX63y2jrrWAeTyt7dg/dCTNLSkPUVmEFbFs14po8AqQuNl33pbwKu/l1msP8d5qFGbt7WX4sZLNNWkcsLPgbeuSXdbuvkLRR4Gw5lpM4Jn3QTt+Vlq/wOU96Ak/u4i1s7EoAis60MXWVlqquTXYTHzvcw=,iv:iHyKSFsSwZcq/6LYRZ0iHky+npddgmejuA/w/ogysAA=,tag:K4vuGO0KU+NDyck4Fh/FBg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
