apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:wYzpyNY/Z2dUbX/IfyfiqkAXaHQXX5JmuVsqYXsPcsqLrjvp/USomA==,iv:NZo3sPjVPJv0Nyy/l71BXU7307x1yYMrAAq3eXDkT5g=,tag:tSjyBGOBYUieJ3reLxOV2A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFByQjh1d3dj
        WWp6bCsvNVk1ZHJtVmV3MytENDFLaWF5YmF4TUlWU3RoQ01tcnJDT0luK3h0cWdX
        WHA5WklGdDUzVUN4K0xSa3dvK1ZxL1ZUKzVSeHZhK1U2djdEQVZzQ01ZZXJGNCsz
        aFlPZENYeGVUVDNLOXdsemk0Q0plNURZV0lCcnZXYUJ4NXQ5Qkc4SnpwL1dqeEFL
        eWtPcVhpR0ZNdEM5NFJBcGxyRnp1OStRa013aFNCUHNPRG9vVmVVYThHQlpZSHJq
        YnRydk05ZFNLY1Q2TE91UDNlbmpHRWhBcEloeUVqZUp6VHNxTkozSXBhUkt1NTcr
        UzdxWC9mUjhnSmhJYjd3UE92RXI4K2xWcE1qRUZPamVFMmpCV1JZUkpjWUVMbDFk
        M2U4TDJzdEZqb1IxcVJhYzVyazl0K0tqNUhzTmoyV3ZTdGttblE0eWtQMGdSUXlr
        Z2p5WUpDdnYxNWhCT205NS9DS1p4NXRCYVFLVnR3NGVlV0x2TUE4MDhOR3hwc0Q4
        cEhKOGNwRHdtMEYvYktWeDNMSkRTWnM0TUR4cGdTZGtqWWJ2VkMrcEJoTDlqNU5X
        bTY1bGlBRjllQnZueUhKaHJvcnVoSGNtVStLTS85VnppcXN6ZURCY3pyR0hoNXdl
        NmRSeFBiVG9yWDV2MGZ6Q3lsU01tTjZFSjNReVI0VUJLdENjaXZCMTB6anBhZ0VE
        dlVnNGVlSFF1NXBRenFnVTJSd0lCcG1UZ2tPWE1tLzhQRkk4K3lLakEveGdlS1Jj
        TUZSRzU4UVVuUDI3QUoybDgrU090dWV1WFRJZmFIZ1ZwMzZLUGZNNXJYNFowQ0lk
        ZUhDSDVpTDFzSW1tZFd1R2RzbzhpcUN1TGZHdFA4YlgyM0ZGTHVNMFF4bW4rVVdq
        VENaS1pJa1JmUzlWYnk5WVNLb1ZvZy8rNEFob0UyREt2aldLUU9FZ1FDR3E1TENM
        Q3FaVVlKbXRyemRrYjN6V2F0ZGtoOVZJRFpXUjI1N0tNblZ2S2RZU09GUEt0NHZs
        cjNMTlM5U2grbjM1Szg3bnZTZVNhVkU4OXdTSVA2Z2lDTXFBbnQvbUFoU3ZsYnlW
        eFNBMmQ1ZWdDYzFLQ1hGYnBRZW9BUGZIOWlFUENoWVE1MSszckhYTEVmNncyb0dk
        V0lWaGZnV2NjS0g0bWpqR1pmNm80TTJKTkJaVFZ0eE4xVlBYdmw4Q2lQYzk4Znox
        Q25MSUlzdmJ5eFgwcjB3ZUhCVmZGNGhUMzJlYjUzcmdob0w1eFNiZU1vemUyclBX
        czU5ZmNYdGlKakVPL3FUaTZuVFBoSjFRNjJUeVpoTC9YSzJ3blE0SWFxVWYvRUlW
        YU5hZTYwYU00NUFBY1dnRktsMWNLcGtFZjRlOXp6bEc2U3hZeTFheStMS1pYdmZn
        QUc2Q0Vzcmdzb1FpY3ZzczRlUGcwNkp1TlJ0R09OQXBEekZDVGNtK3NUYzVKQlhl
        K2c0QjNieWFBWkhIczhxeVA1akYwZG1NUURkM1JMU2w2VElzRi9QZXBPelJzT3I1
        Ti8vbG92YnNNbWZBZkt5NEErVmtLNVo4TktFWkdOeUpWenJ1ZmoxMmV5MFJNbGJN
        cFVFNEo3Zm1rSWtaOXh0eU5aYVBVWFNrK3hDb2J1K2FLa2x1eTJxZ0c0Z2ROOC9i
        ZnltRlZDSm9LQlJ3Mm91ajVWSDBPOXhNZDBza2xvNTNDbWh0WFFSNnJpVlUxb3p1
        VVlIbXM0bWQ5MXB1RjFUaUxkSnA2SUVrdW9zZUpPUWRaZ2g5QXdJUHE5eWpON0hv
        WFBoM2hZdkp0TVBsanJMU0RJaVB2VnVZNXI0VDhEdG5aNEk0dHgvd2lJR1lkT1Vv
        Y1lRLyt3QmdFZkNSZTlvc2xvYVZUOUw2MGRWdGsvTnA3L2g4VlF4MEgyd2orNmRT
        YjRMTkRtR00vRzJHVzhtZEZlTGRpRHErVG9zUXYwRExCUWNGbE9EWVE5SWJKUQo4
        ellFMGZSM2FGcndSTVd3TXN2VUk1TFIvcHlpdTRmc2Q2VWNnTHNtUlo4Ci0tLSB4
        T2pzTzR5UUJNdkdwK2kyVnZhV2NPY1czQS9UV3FlaHBVVzNPUEFVemtVCuHR7Ds+
        YulZ5G3Yg2UUQs4Qa0/JvZ1CXvLca5NqLg2QyJIyDGx0ilht4hV1cjhwfM8vPzBu
        Cwumc1TT+H66YM4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:14:14Z"
  mac: ENC[AES256_GCM,data:Jsin4ibs4sT8YFWsMU030Mx0x0tAvrs5t0c+pdDvI6SE0sICBONl3x9k2LdkcC5wA9HIVdyBJTaxW0MJvbRiFCuBTQVpn2r4CMa/P/39H3zs5YvzREVCGyPWD+YGvs7KcY/bjYbYLNCnnuIMMCuZqnnWhFt0uDl/UEftiUlVC0k=,iv:+UExz4QQH6r9B+M9lNKbCjDzVFE32jk8yMnHgXF3tfo=,tag:7HYj6wNLtwKc4L8ou0Z1uA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
