apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fuw0dhmsjYuslmHCLgZdyhjdYThDuKlrD7LCVxzXQ5ybkLxDfgrq8g==,iv:J5Zps/SQZinghclZraNb1wnRMn8VtRDa4APnAAStUs0=,tag:8JuvmeaLlYtqKOnoy/voPg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHFLbU8zeWMv
        R21CVmhqZlRxS0FZcVVsaWQxaGpuanhSM3Vpc0docHA1MmZkczcvNmg1OG95RzRn
        T0djeGlidlM3Z0VsWTdiYjVndkExLzVFQlg2T2J3SlM1cC91dXgxcndRM0laWXdj
        eXViNUJCODN2MEhqa1Nmb0dFSnJPSEIyV0ZCd0Rwc2xRQ2tyaE5DSTJYdlBxejRa
        ZjR5WjQ4VWNSR1NUL2JDTHVRSWJIMloxZmtIM0NQOVpqSTJ5WFc1OCtLSzk3U3kr
        dEdtUG1wMGlhbWZHUERQL2xheVQzcDh6cXhKc0ZKYjVvZlA4WVBLQi9tdkNuU3ZN
        M2UzVnRFT0R3UFZqb25rcG9JVmNVVTJxenpHY3htbXg1WTgzaUFzY1hXUGE1VVFI
        SEZJdXNaWkJ1R1l3cm5wVFJIclE0eFNaL1NPLzJqVEZkWEpOMmswR0UzamNIRmxr
        a09GS3Z1cjEvclJkcU9NRWVnKzVLNENiRGlIWjJKWlk2SUhkaGFESlJwUzgyUm5v
        aXdLWFY3RUJZRS9DeEFyK3N3blJjSGNUMkFid3dxN25NcVcwbjJMRDFqcUtYUGtm
        aXFMbFpXQ25idnVURlo2ZXpJdUJpZHV2S2NTN1ZBRGRoVHJLSFNPSjhxditpTVNG
        eFQ2UzhuZy8vVU9jQUFZUExIZnVQLzRtaitTNXZUYzUwVUtSQ2VVYXdjM0NiaWtW
        dEc5R2d0STgycVZ0UVNCWi92OStUdTQxbHc0dVAvUHhVUW83b0Rkbys2a0FwMUNG
        OHFNVDNEWVpXT3Z4K3d0Z0JXUWlsU0JmSFI1dUZtWFBiVWRlRk80SkQ2OEY2b3l0
        SC9GU0Jmb0ZDb0JXT21yVUJYZmoxNytnYTJWbTB5ODV2YUIySU1uUFYrQWFBT3ls
        RzVjZ0g4N3QrbTBucHMyVSttQjF4YlRWaFRhcEpsV0Q5RjdSSWdMSFlmRjB2M2tt
        N0NVUW9DQUZudnAvbjVCS25WZVhsZy90eFhWRDR4SWZpdmtuTUVselNsQzVoaFpN
        bEV3YndYRTNuY3BjY3dEaHZxME1jRytUT3RWaXphelpUU25BaXBGK1B3L0xrUFU3
        VlVCTU1DKzU5Sm1yK0owamZ5aUY4SWZSQkJCYkZKbzNWVDdFU1IrcjNTWDYzMTBU
        aGNZRE9qWHJBbkZLcUVwTDNiUFFrQTR1SHViS1dmVUg0dms1ODVtdmJWRjZ2clYr
        WEp3eFRWUmhIT2ZoL1ZLNUVpTmtPN0F0ZFhhbFpFaXdPTiswbUczSjZyc05ENEts
        M1BLdVJDWUxSOExTOUFpSDRscytnRzE3blFVRVdsRWxiM1RqRjJqcStZTDVIblVS
        eHJ4N3lCU1QxUmtCdGJwUDVnSHdHbzQ0V1M2SFpCQ1BJV0IzekJrSFg1U3Z3L0FC
        SWJ5VGRnWjhYWEhtZDNDeWNRdmJRT2wwaDRYQXhCekdZczQ4eU9tRnJNY0o1Y1Vo
        cHpFLzh2UGtrN29QbmRsNG90Ym1lOVNIVmZ5VjNYNUw0NzhhcEd3clBTMkltTktS
        RFo3aG5SdE14bDkyNkVQNVgxazdEWGh5NXR3aWdFMHgvU0pJSVl1Zit6NVk0RHZE
        WHBtWnpZcXpYU2w4MnNMcGdHL2dmUFd3cHpFWTZNV1NuMDk2UVJNaE9XWS9ISXhU
        QjVob3ViQnArRHV6WGNBYlVMcmN3WktBNmh1bWZrbmZTKzR5OEZrVVB6VTVSTGox
        Sm1Vay9FUVZIWHprcmxMUjgrZ2NyTFZCRGRGMmZyZ3ZwMjBuK0E0b2p1aHJtTC9Z
        Z0hKVHowZktDK2c4c3g3Zk4wN00zMDkvbVB3Wm15aVg0UkVqUDJ5VE1hc2RnWllE
        TjlpNGFQYi90dTdrb0hxZ1QrTXM0cnRGWjV3dktydXc2NmRBeU42VWRkd1EzMGps
        WTRHNWNjN25hNlAyWm1pVi9DK0VMOURqNHJ6MnRuT0JpZ1p4VldPbE1nMzZIUQpK
        VFFqOXgxUTBXdmhXMStFc1VFZXhObkU0Yy9UQVBlbFlUUnV3TTMwd2JBCi0tLSBs
        aHlWS2lkVlFGeG4zLzlXaGdmYjd2ZWVDd1JhRlVSMWVwam1oV0NWcXcwCm54NNuj
        qeSlpueQTJDNpTJqIGhIwGcRByJ0IiT/OSdWRjHhBVThLeNnzzXtPiNCN5NTY8WR
        P93jvTSb/VGacw4=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T22:46:38Z"
  mac: ENC[AES256_GCM,data:q57BNR31l0HdPWXJzIiJtAFqnf2Kw/UoWgmag/oXIMOrv6liHS30bOaaMSvsFgFmg2Qq6FAeTR+6eqleJw3XxpXsoNkoHHoBKBYbnyh4wSXI6K2sCG0XIHipBakH3dXYGDxW1zB1xc6DFqNIwQW7S2P036Se0j5yZQLTyEhgNvU=,iv:eomYpEJLev1CsFav+7PJk239JnTYg0ipF8ajBPK4Gdg=,tag:V9hHxk05DI0T31jDsCQ3Lw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
