apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:rOOD5GJp4I2/jndAynFvhsL76fxdJFU9csDv+e1OBNQiI9Wvk3dpRg==,iv:rsPMsWFS90h13/lH9rGJD2CkVB79Ft/ZJg4vwWGzAmA=,tag:dA+VfSttF1igZ5jOUvMopQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFZZR0xkTDNS
        cnRDL3V0UE1MYjhLVjEyNUxoa2RYQXY4Vzl0YWlSWGd5NjlxSjJGM1F0WThxZTB3
        NnA4ZTZzT2o1K095VmdzdkVWTjduYk1vSjB6KytUdlhZaWVYOTBvUENtVnZ4cU45
        aHl5aklJMDhGdStzcVY1aTl0emU0V2ZJV002N1pVcmhOc3VSOXRQMTIxd21rVllt
        bEYwUmZmUUpTWFhnc0FOUktrRm1NZEM1Y3BrMmtrV0UyaWZnTEZzaHhacno5UTdW
        b1JpNDI1MEFwMU01bXRFbjJRSFJqM282alRoMEhudldnaHVFRnlDQ2M3dXZsdjFm
        WitNVUZCc0dHRmdWcWpqQUhHekRKVUhRbG85ME1BVXJrOVB3Z0RjOU02a1JpV0pY
        WFFla25PVnBQTXRvb2FtZHBNTFRCK3poTUxPZEFPYVhuWTNOY2plK0hxaDhhK244
        dTdhN3NjU21XYlQrNTBEVjBLbUJibk9veXJWUzVHdWpsdm1obnZJckJXV2h1T01Q
        ZUZpZ0dTQ01lVWJuUVhSZ1NDa3JLZklPNHhXWmIwWFVFZWNlNk1jakhyeENUTndN
        VkdGczNMTFZHMzk5SzRFREhpK044MHl3Mm51OUU1cVhhK3ZRVTlNZXcxOXRRRTY4
        K2JqaGlIZldHR3g3eVFhc05UeGRBamt3c1Y5UmNGelNTbzA2NERqVVd0Sks3RGtR
        by9CWUhmK1Uyd21QZFA4dnZmN1BSaFdTRXZkazFnbHg2eks0QlhIbkVWNDNVNzBG
        ekgrNFVXdkw5NVZoamgwbFN6dnVWU0dIWmtsVFJxRGwvdnZWOUJHdllhMHQ1eTBW
        WG5HMEJVTHVJNHU5M2hDaG5CWlNLZ2NZcm1rOEx6K0gvUDIwUlpjOFRuYkhvYnZP
        S0t4VFhZVXprSk9qOUxyODRURk84c1RlbUlQMGRTSnMyM3lsYk00dXo2RzlHWVFy
        cHJnc3hMRnoza3VuTjRMaSt4eWVhK3NIUEVRTzIyVW9NQTN5S0hMVTB6anNuS1Uy
        ck9BWi9wQW5UVlBoWnVycFZhTEg5NHNjYnd3Q1pwVDJwelZhajNoRllrSmdNc2hx
        bGU5eDg4UTV5Wit3SkFiV3pPdXVzZmthbWwvd09qK1dUZFpsSVIzN05DdlM2L25O
        SVVLQTROWTRBTHp5REFHckxhMThYWlM3aFlqMmRpQWxlMFhGTTZIYXI2TUJtaW5H
        VnU5ZWYzZnp4VnZzQTBNdDBwWmZNRnRVMkdRUlBCTWlXK09pZnBmMGQzUGowN2Q1
        SndVY0x4b3dPVE5DQnFhMC80NjZFd2Z5QzNmUU9QZmY5R1drSE92YXJRTW9VOGJD
        UjU5di83d3dLTnl5andjWktWMk9qT1NISVNyNktpWFdXSXBrV1htVm80ejRiVGpR
        OGVGVTE1OHhWcm5NakQ4dzRJZFJOZUlndURFdTRoVjZLZ0ExZmVhamtBYVorYWdI
        VnJEeEVDeDNPekthNktiNkczN0F6ZnhhZi9GeEtTZnhiZUttRzllTUJkbUcvSHd1
        Ni9ReWN0VjY0Q1hOcVdVeWpzV2pBWjByc1NJZHU1MlE4SEZkZG9nRmFSR3pId0tk
        T3ZEQUhyaXROQVF6dkhyL0lXdUFNcWRNRGdURFhvSHZlcVRUOGl4MXJoTTd1MGpR
        a1VhVDFZNGk3V3NsVTUva0VWcXRBdytXVGRkelE0VVdGbTF1STQ1UGdiaWw5SEJW
        aFBOb29UWk9oYk4zb1FScFZOSlVIeTY0Szkwcy8rU0dzb0dOUHhFZ3N5c2NySUZ3
        eWg3TGVpZmxCLzlMUWdFMENkS09NVEFQZEp4ZmNwNE8zNFVRMWtUL1ZxbEt1bTBV
        MlRNbzN3K2grSGtRT2ZaNUdkZitJakJBbCtQSlZhdEF5ZGtRT3g0azM0KzN0cDFa
        QTBOWFBadzRQb25VQ1ovTmtRK3dMMzd1MEY2NnJzYkxvNXcrYlp6M1Mzd2FSZwps
        NWh1cEErOUpuRWp0R3BaNHR5NW1zemxSUTMvYUNLa0pPNlAzM3M4QktvCi0tLSBR
        N2JOSlRjNTJ6clI1bnUzeENrV0dhZ2hmNnJ0RmZOd2RLUW15TmYzVVRJCmEosbxj
        3Cd+5LHE21SJLvlMU5fkexzGjOWYJuY1ykYLvZoQen0WM19ad9/uykkKhJWoDRYx
        cDiWrGnyg+d3c5M=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T15:30:58Z"
  mac: ENC[AES256_GCM,data:ZVKEUMtpDARPUK6i1czHpk/beVcofHMdFBvABLUgybjK30vzvaA5NOM1HVpbWNHiPvnFFg+LlicvytSgWdfdJJougC9kWOsMhCfg6Bc9Or/OIRRfmqoBWMbtJraujx6sCpSMvL+i5xKWSOFdukCMeW3/Tq86GETt94LfKxpRz+M=,iv:qLe7C7J2OCRRAzkU2iRF/5ng4zphn7opbs3HALuj5Ik=,tag:cx30ILsoqoutwg61uDsOwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
