apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nginx-basic-auth
  namespace: rook-ceph
spec:
  encryptedData:
    auth: AgBMMuLI+KrFhrT1sOCTbyNDbhEb4OuuiyAB2xsOoRisuZcGCsxBXSVJiqtoVN61X1XLHUmGuIv6p+x07s4iPqEp07XVjegFkCYN+s/pk71BukV+ZJ1Su8W9sDSLQtLBpStUIGpO4Yfc4hzYVRFLt1YLwsoQe37cuh6S+iV/o3PTltv+5xeDeGHTyTNFL0G1V74aVwSLXcNrofSHO+Hadpx3cD0x+MJAt54mPPdiX0XiYAe+AUJgq68E4jDdweSxstikgwd4Hc8dPmSyBCHgoWHsqMfPZ7lJH2BwlNj+iw77+54599/RNIsesn/xow9AapSZeWf+MX2Td28t6F3ffYdSco/3Ppc6dRdFZzIneQXuydffDkRF3U+/4nk7Mrq24ADw0IPpxBAqBTPR0qth9c7VxcaowoE1d7yPnK1R75yPnEr2woqvaUeieuyCZcjvuG6Foy63nq7vD1OKNHYNBGmE0TGZQteRhpOkpDHp+Y/VGUkIH05TpVT09KKj6s+6rsSfN9yYySpHqyF6o9ytzdn1e+04+FrAVNPIJ7y//EItmS0lNXVRPqwphL6s1GbZrCNRn4cpQZSAeYyjJmOnOa7Vm+0jG34JjOPrPtBhE+fTC+zv1UxLlpKrUPPhxSnavxaHj+79sJXEWx2SbB9f7FSbd9zLtjnju8pS8S8ir9O7z/KZmISm9Zk+eauA9fAUoA/IGUeadSzqMGjkEevDc+VKvIv5q1Nm5gfdAO4ZuobqSf4DI4zUkf/8USp5
  template:
    metadata:
      creationTimestamp: null
      name: nginx-basic-auth
      namespace: rook-ceph
status: {}

