fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: ""
    githubSecret: <function webhook_token at 0x1090cd590>
  cm:
    admin.enabled: "false"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IER6VDFxNzNZ
        cUZkV2ZRNmZ4cUVRU0YzZmhaR3AxRzdRRDdYK2pMMlBGRnE1S2pPU0ExeWFyVk5Q
        T3A0cGdTWk5UVVZ0UEcrc0laMDBwbnNJOTJiSDF2bklESzAvOW1YNEFWQkg3aE02
        VllTTGJlYjQyNGNzK2llMnNZUWtmd0R6WUduR284U1ZMT003aG1kNTZPNEprbjVh
        THlSbGRFeFF2OEtBV0VoeXd3VStoM2FSNFQwMUhlUDd0ZXlFQmMzWStKd2dJT0JU
        bzNwOVorQjVEaXJoY3lHS1R2dGxheEU4Z0x1TGtza2pKa2RPRzN2SWZmdGFwcDNz
        a1UvM1ZkeHhETFJoNnYzVGtuODJ4MGowRW1jMzYwcEJZNFZVRG14QStmOXVRQndj
        ZGFVR2JGbVNBT3V4ZTFFL0JuZHVYQVY4UGtWUytCa2pSVExvQ3pUcXA0UU1FRkxw
        L0dMRnQxYXFZNHhtVHJBaE9OWldGaW5xM0NSNnRLZ0hNUjZVOWU0Rmdwc2s5cVFE
        UXBET1N0ckN4Rjd2UkRGYlRlSGFuM2UramU3OXBmZExRTFRzV1hQMzVySDhjaXlU
        bEFRUkZLdDh2UGU2YTRMVFdtdXN4VjlLTzFSdThqVVhrUFl2ZGJoK2ZEdkoxWlJz
        cXM3Q01hbXdDWW4xbWNzTW9FMzNtczNkS1ZtL1M0UGFOMkVJWDNWYTJMajAvV2hH
        NDhRMGhsdEViWjFBc1J5UUdoUEJ5cGRxRVJnVndoK05TWEM3YlV1M0ZjQWNRWTFC
        Zi83QlZ1bnVXcndmMG80dU8vYncxVTlYajM3UzlCZm00cEszazRrUXFJZCtsSmZs
        QUJ3Y3luRVdlK2VJNDZuSVp3L29KNnU1dk96ckRKVWlzemJnMkI0WWhMMlJrblZu
        cFUxZlIrK1BjSUVkNWQ1NWZHODJxbjJLbEhEVXFVc3NzaUpXMk44TkhYZkQrSW9Z
        QkhQUy9xckZ0RkRTOXZzMlBuWlM0aXZrVitvVlQvN2xEUmlUWXk5d2pFU3Q1KzBK
        MTREc1BYUEpLRkpVOG12SWk5LzA4cFFMd0JYWDVoSmNLUkNDbGJyQkFBT1U2cXY1
        eW56RjRCbmwrcklScmk3MEZUTHVOa282ZFI4VmpDVXlzRjVsRjAxbTkyT1RPbkM2
        Rm5Fc3M2MWt5Nk5PdFc5ZVRQYUVTaUZ2RnpYN28xM20zWVF1M1V0L1Y4ZGd3ZkJx
        K3ZLdUVFSWNQbGl6a1BEU2lmZE1qNGtHWGJvWkNwVWtLOEl6eFJSbTZzZ0F0cnJX
        SDhEY2h2OG56dlNxUzVnSlRnT2h6RUh4QnFtUVV6bVJWWFh2SklSQjZqTmhMQjlC
        K1ZCSzNBOXRaSVV1Q2x2cm5TbXBOVlNlWlNYa1dkYVRQNHBVdFdSQlc5bktKaHMv
        S3gxOWwxcThhbC9vKzJwM3cxSVJOU0QrRm13Vlk1TEVTaUphZDNuNDJTNy9Kb2NH
        ekR4RmIxSzlpS2t2bDNlQTRLZ2xHVzNDRlE5MHNrTlRxZjE3MFA1VTh5a1BmbVpr
        MktEQXl0YWt2UHVjMkY1YWVhMUtjSGF5cjJCMWJqUnF4NlJoQXE2QkJvY05uQzFR
        WG15bHVUYkZvbU1kVzFPRnlhUllGMzJtbFF5UzBROWs4cHY1M3E0eDRmZDNRWXBC
        Smw3MGJybjRVbllyYjBLMUtjWFMwRi9hbUZ5STJqUkFnaVBJZ0dvRElIRjlneU15
        UFY0YW82c0pscnZpVFRQWWVtRkw5NzExMzZBZVUvSXRqUDBqRC81R3piTVhxSjMr
        eGFVY3R3aUQ5enZOL3dkMHI3R3BTL3NENUYrUytlZlpqSWQwWTRHZnZhelB6aVNH
        dkRwVDNWeTg1cnVjUGJOclZJUm8xNnNQK1hreUNVajZVVFFRNUxlSnVVckZrVnd0
        U3lHcXdZNFJaTy83ZjFQRksvenFma3pNc1lXZWhzVktQdzgxSlNHemxFMXJmZwpK
        Snl5YW9lODBxaGFBbzFUSlJKWDAwZEtoUUhkUUV2UW9SWm11czdoTlpzCi0tLSBs
        UVJONXpPS1dQOUpld0drdU1VdTZpencvcXJxOTVlY0lpVjBKYWYydkYwCo17hhxN
        UcKwSJO+jpU4YsECKXD75w1idTo6mHumkiRio1fR5XVgivOe93FtMw97/42A217s
        YIg5CXmpgR+/p2M=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:14:15Z"
  mac: ENC[AES256_GCM,data:/gCZ14f3ujjaMMdbw8XZzj44aPTpO7PxxO2NbqsRgVfujG/WtYKDXogRcJDXgdixMsxzmDJKp1HBB8s1dVEePkJuT2RRc/hQhD1bpFKSFPlEculOgNbIlcl5U0kIrAeW6BRPpr/prWJoGHlnDqPjmKJVud+ILN6wAFFn0BVHaFQ=,iv:B/5oNG/liM9hxqgjZAbKAx8dX+elq/RwnYYXinhJndY=,tag:HSi68HQ7in3ytDtEsKef1A==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
