fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: ""
    githubSecret: <function webhook_token at 0x10b6e1590>
  cm:
    admin.enabled: "false"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDM4bEp2L3lj
        ZDljc3YzSXNWbEphUDVXWnFZWU9IOWkwMnZRaDdGV0MrUkIxNlhzYTNCTForem8v
        dmpHQit6YlNscFJLYmJrUDRYQ0g1RUZheUlPR3haaFk5Sk5kTVNRc3RKUEtWalhO
        RjU3M1dOQUZRaWZHemlTZi9OdGdEalNuQ0NtRUdLT0N2REtFT2t6Y3hNREtKaHpH
        WDBZdStybndCelIweU8va2NKaWs0TEFmK2taYmh6R0VIRHNFc0xndjNIU01LZU5t
        TUtXY2NOVGhJVUw5VnoyVVI1QWhXeDh3dExQTVhzRmh1SVN2S1paaGJ4OFQ0MmxK
        N1dpd1lRZmhuSzlsM1FESXBEakRqdW9lakYweUdLWHNXdzFXaklvcGdmdnlFK2tI
        Vk9MK3NwQmVxTkVuOTFMUlVuUldNTlZMYThaRzZpelRuU0w5ZURRMTV6VlpXUHFm
        UytJL1BWNGFmM1ErTWF4NlA5ZWRDV2VqdWhHMEJ6Nkc3d1kwckxnU05ZZ1VNTnZY
        eTEzRExPY1p5TkdZazhQSEIrWTBKMXhVbGEzVUk0UUhIeC9oYVJLUzhzb01NNGhM
        RDV2T0loREltRncwb3FRVndFMERCR2NCdXBQOHFwWEh3Y3Z4bEppRjdNNlIzZzdt
        RTg3R0VxYnZLckVRb0Y4R0VZbjg5NG9mWVpYMjlJNUtCc2h1aEpDVWVIN1haYTBw
        a2I2WXdwNXFINElFbG5QL3lENitJZGJmOTBvaXVYbGk5R1cvejR4QjlhaXJia2s2
        ZDZ3NS9RMmNCdjB5L09zRFo5UjE4eTB2T2FTQm9kVjg0aml5dWV3TFNxRlJvVlpr
        R3NralZkc281K0I0STcvUXVtK2RMMWFjNXdhYUNXQ3Q1SmNqYnhJYnVIdFdnd2Zv
        TXlZbWVwU0JZZkx1Q1VDSGZsZllVVDBsU1diNlRQSWwwRzRVUmNQS0wreUtGeHZk
        RXAxT1Jhbm9IZ21RUEFoZTFyUGhBc2JRSTNOdkpJYlRXZjlqZENLd3dmNWJ4TUJs
        dVdUY3NIUUpmam9ZazZyeS93RExlQk5DREU5U0ZYc010S000Y1JEaitBV2V4UTk1
        bi9zdTB1M3R1OVdqSEJWeWZnNytKclk4SWI0d2hYV0ZMM1d2T0hxQ0U0a0Erd0VZ
        bi9PbVI4cm1QWi9tb0QxZCsrNkhCRStudllTekpIMHYvdzlMWVlqVlBMRTdDY05L
        aXErNE9kTnI5aE9KSUV6YnpHMUcvWVZTa3k0c2t2OHNLNTd6M2QrdEF5VG90Z1Q1
        TGUvSEtqTjdHMXoxOGtraTlRdU53Zy84em9zRmZMNGNNQUNXK0tpTnZoSEtHOXp2
        aExZcnl3U2FqZ25KTlhsYVVpNyt1aTNhTXk2Q2xYYVM0RHFQOWZlMWxtdW9zQ2VG
        QkxNdjlpb2pZOVZhNjBYWWFjMjBEVi9XS1JXM0Iranh0L0JnbUppa1o4V3JscS9O
        YjFyMkRIck50eTRmbzB1Zks1UFhyYTVRRVJTQUtZbWtMODRmS1pXV2JRbTVtUDY1
        UWx2MlY1bEFjWjZlNW80QVJZR1NLVEVuYmJITFovK3ArYXkwRlZkK2RqNHRlNG1I
        MVljcEFkaWdjOGpSRnZFR3Z2V3BIcndBY280RU1rbWNPd2NNV0lMcGVSL25PcWsv
        cG80QWRWUGdJVzB0RWVNT1N5ZjUxZVM1RzZXc3JHTFRVY0taSkJTd0pzYUtEQzl2
        ZHpmTHFBVHNHU05hL1JnSUtnb2V2TWNqZ1dYQlhJL3ZicGhpYno0c21oWFBtMTNs
        ZEhCdzhNYzhLcVhhdkQ0N3QrckFteW5URWJxeENISjdkYTNNZlJqQ055cU9UTUpv
        dzZxZ29JUkpieDZ6VzVZb29VaFgzUmdzNDgrcnhqdnZXUysyNC9INW9oUU95c3By
        RS8vRklNNit0MW9Fd1dUOGJjUkt3aVdxMW9WMDBZN0hwMzVzOFc1M0xjZDhJdwo4
        N0JOa3Z2QTFKWWlDT0d4dDNOZlRwOHYvYXdaeks3STZBdnVabW5BZ3VZCi0tLSBv
        dTAyZS94bHZnQ0Q1Q3JtaWw5KzBlYjN0bVczdW1PdENoc3p1WTBNL0hzCtC2IcBf
        3RqSjFIqahgTKug3AUIx46BXQcHWhYPE2EuU1tcJkq5kQ3U9E/2xKZeiJ7Jfn7QM
        nq/59xNQHDRs5io=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T15:30:58Z"
  mac: ENC[AES256_GCM,data:KXoQqS/iZL7t8MuY+4qIZo27AGHKs4iJWCl8e229jmWMjg1uLzrrNImZXVNDQbTzueKjX1LL9rLUqXqgrZd4Dq99UBlJJUa4mz8XhLpIYHmQbheaNaMjGeIoKSpLMo0cE4qcNGx9lbd8cErMYY2IBoK5IfXd6z8adURLhCQ3mqI=,iv:EIs5PGC+NFB1fDLizJaqMg2a+t31LoQ4W0Qjx+aKef8=,tag:A46QbP7I5f9or8hDkaFPlg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
