fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: ""
    githubSecret: <function webhook_token at 0x1094ccb40>
  cm:
    admin.enabled: "false"
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFZFNDZEZk93
        K0xGUzJJN0ZuV2FzTFRWYSsxaDF6UzZUeTE0eCsyTjlFNnhzWHpkYVVMazVKaXdn
        Vnczc1NCWGlyOEZFNmc0RUR5QzZSWXp3NFFzMUI3enA4UGdMam5tdG5McG1Rcnhw
        d0xMbHFBQWlkYkllSVY5MkZlR01kYVBJVlh3Z0RmSEVJaUxsVDJtWE1BSHBJSGlk
        TEgxUmdWVWpwczlTWFVtNGR5SFdQK3hiY2U0ZzFqRmJ6V1NtdUxPQWlaRVFiWVJy
        UXVNNTRPSGFqZGM3a0NRbXZJcEk1eHA0WEF4MVNBZVRReDBYVmczVVVPeWZGWmgv
        NXVQTWJHVzdrVUh6Y0k2NDhLbm1UVmNqL0RrVkxKajk4bFBhM3NJYTAzenU1cHFu
        QmZFODdrckJoV2tTY3FSOW1VZjBtNFVTVDJxdTBwUFVGYzdRc3J5ZWpHWnY1ZEQw
        bk03dHpRL0FWc2xwTTI5bitPanB1bE5MNGJCeVZvemRMa0dROTFkdVpmUEdiYUsz
        ZFV2M0REdjBsNkE0TnB1VmZCSmZaaFB0SmQwWjlVK3ZxckdPTVFENm9BVHhhclhZ
        NEgvamo1TDAzYTJhRG10SEczZDVJZWJzc2dCdmRFT3BNeWR6b3NmbGRSRHFhRXhK
        RGFEU3JhVmsrd1JxYlpoekRVYzAwOWNsWHlXUkNGZ0d4eXJ3UXA3Tkh4MFVhUlpi
        YzJKVit1WGVDVWlZRmVTZ2tPRGRCQ0d0d2xPN3E4UVQ4NjFFU3NtVVBjV09obStt
        ZWdqaHVHbG16cGlNa0hjR3BrY1RCRHVUdGlGOU5CczRtSjUyZSs3ZkxnNE5Uc3k1
        UlhCMnJNcWp6eldSVXFhMTF2UDF4aHBQZG9tb0Y2V0RLcUtJMzV6R0k3eXFyZFVT
        eHVGQUNZTEd6Rm9ZUVNIUlViVDNjYTlXcXhWN0tNdThsbVhHZXBhYWZXVk1kaytw
        QXBoZ0g3SEhZUDJQdWJndHBORkV2NE02N2dlR3B6RnJTTDZhbzBtcWx0Vi9KSGc1
        ektzM0dDekErSUZ6cVM0K2tLVUdnNm9oM08vQ2NxRjJBWS9QbU5iMzA0NDEyNExw
        bDNTeVQ3c3d3Tk4wanZLejlMVHZrUWtIZkgzTno2UFpLZlN1cjBLb2QwakRmTVVx
        V0wrdWF2aTVnVHRaakJub3JieHdFQ09ZbDJ4ZVZybGFTY05ZVG8zZ3g5dStOeVJ1
        bkN0OXVJTE5XSjlrZU5UVXdWVDJUbFVaOHFBbGVPRDJyM2FLUytiSTZCRlZ4K0ty
        cUNBWUc0UmxCcVIwYkF6d0d6eXBWMzdaRjRUNXN3d1lMT1dLU3lhQ1R3MVRXeENB
        VlNFKzhJd0wzTmtLcittL0VqK0FKMDhQeDFLbkVBcmlyaTA5RFlaTFpJZGhXMjM4
        OTFiTU9WZzBrYXBLODNzNWRKc2xiNWp5OFhMaDlUR3dJZWE5ejUzQjZvZkxieE9F
        VWxFTWwxMGxxMFlqNWdFd0RpVHpVanhMODlVYmxVdkhGajlyQjJLUEd0RkRpRDlr
        dFNNTlF3TXhxTGgxNStvTFlVMnlPUzI2ZFZvNUdlQUVoY2pOeno3d1Q1VitPT3Ex
        eFpDdHd2RFdVTGlBVkdaSWJ1dkdHYUF3cVFOcGhDVnA3ZndjUWdYTnhxelBBWGZh
        NTlQVngxQVpGc2IvWFdGaktDaVlQRmtSMXBHZlMvRno4ZU8xV2VBZWhCRmxqcXo1
        d2ZmUkptNnZKMlRUMU1XTFNyS0xOalYzMVgwcG9Ibm5GZlQ0ZXFYMzg4RUVJZHRw
        WGljeTkvUGlXOFJEbnpCN3B2YldkWEwvdjUwbkJoVDNjcVBNcDF1VUMvUC9OSjVC
        QWw2MzhMU01tMThvMS9rVHRJTzhqaUdRRlA5TUtIRkhjcnk4MnJPOEVtU3YxZ2NW
        MFZzblRObnNxanMwNCthbVNOZ0dzdzZtcnJvcEdOYi9QK2g0TWhZMjVpaEpjQQpI
        VHhOc0pGTmFGM2c0bXNwVlJoUVhkR2x5bUp6Rys2VDZWR0p0WDNqZ0tRCi0tLSBy
        TWdjRCthRmVTVkdqSnNlYzlLNWdCQTdmODA0eUxwSXN5MllneHZib2tNCksfzyXj
        v5xq4KlY+SS9mDdBkW5H2sdGuIkqrFA3jgCK1859uJe9gDXPZhc32JW9kNIqIYJN
        s3m4z1ZXzkfAnUw=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-03T13:20:27Z"
  mac: ENC[AES256_GCM,data:L6uYhOjibULWgRzypd3wgIK5REJl1LVpoQnPAlSJzMy/u4nlI63cqtYQyHJt6C6FTs9CZnbRzlPbkbmpUmiF8RkyHR2v0Ji1WWXVX9Qlbe9s5KcFGLPHChrWaTrsdxppNNhbyuycxWiCSWNIUuE9D+U99RJUpUCyd3supTgRedc=,iv:apBc2uAmwGM0KP3clwbpyaj5c64mBRzEn6PO8DZMr7Y=,tag:1/RuJh26NlpyucAXJzDeJw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
