apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v14.2.5-20191210
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
    allowMultiplePerNode: false
  mgr:
    modules:
    - name: pg_autoscaler
      enabled: true
  dashboard:
    enabled: true
  placement:
    all:
      enabled: true
      tolerations:
      - key: k3s-storage
        operator: Equal
        value: true
        effect: NoSchedule
  # cluster level storage configuration and selection
  storage:
    useAllNodes: false
    useAllDevices: false
    deviceFilter: 
    location: 
    config:
      metadataDevice: 
      osdsPerDevice: "1"
    nodes:
      - name: "k3s-worker-a"
        devices:
          - name: "nvme0n1"
      - name: "k3s-worker-b"
        devices:
          - name: "nvme0n1"
      - name: "k3s-worker-c"
        devices:
          - name: "nvme0n1"