controllers:
  cloudflare-tunnel:
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: docker.io/cloudflare/cloudflared
          tag: 2026.3.0
        env:
          NO_AUTOUPDATE: true
          TUNNEL_METRICS: 0.0.0.0:8080
          TUNNEL_POST_QUANTUM: true # disable when using http2
          TUNNEL_TRANSPORT_PROTOCOL: quic # or http2
        envFrom:
          - secretRef:
              name: cloudflare-tunnel-secret
        args:
          - tunnel
          - run
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 256Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    endpoints:
      - port: http
configMaps:
  config:
    data:
      config.yaml: ENC[AES256_GCM,data:ELg/i2hIgNGdwoCqhXEHXSukWbaxIMMl7y9GI73uIQ7La5Z3D0AH/fBAl8s++my1ieq5T4kSOOSARbuhttiNLLYNu0sa3dT7F42SRybJTbzZFqqGG9kCy1npiv6ZxNxDyq30OMbMdnFYLAQWEY74YWbzGo3wbqNGyrPJBHF+dbnAbbiTMVO9KBEzxht3eC9mCSBJbckm5VRVTSa2W+29sh5Mfmo2Et9+f2C0XrmUEpu20TouYYjgcUis+XNfE0ouWzigjc7JXdJGcb7nWXfrxaKPZYK3N7aEnjUP,iv:z4g4IYNoQ2MJi12J1gHBDI3JsT4VlXY3wLNZkUcqCVs=,tag:HR848QpDt+GWu1ynaAdbzQ==,type:str]
persistence:
  config-file:
    type: configMap
    identifier: config
    globalMounts:
      - path: /etc/cloudflared/config.yaml
        subPath: config.yaml
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHF2Wml4d3RL
        Vjk5MldhU3QxN1M2OHVSQzRtUlJ5akhVRnhzODJXWFJ0WFhMekp2eStRVWVlcHVl
        cDJjcVZYWHhuOUV2eDhyajFGajhsOVRGY05ZOEc0dlJKVW9odVM5amlzK0oxaHlN
        WjYzYW5nUUhmVlM5S2dZNTN4M2tYRXJVZEhRclQ4dEovQmlITjlNTmpXTnE3REVT
        eUFZcklvRE9wSFBKWnYvekROMVNjRUpsRUpBQUU3Tnc0ZWJyZWRFYWJnOHpTQitV
        SnlmRGFPbHBHbEJaMGVqN0xYM0ZNVGZjcHNUS1NYL3BQOVNsc0QyQkppL0Y5YkI5
        OVk4dThYTXNyVjRKWXFaUVRPY25Zd2hkU0lFVnVUeWRUWWhJQmUrd3hMZ0dwd1hp
        YW5uc3JIVXpMek8rcUtMcjZpbUlBcUlZZmdWWkNFVE5ZVWJxekVwQi90NHBFd3BR
        aUhQL2RkblFuN0d0ZGlodTZtV3NEOTErQ2J6WUJnKzlNYlVNa3ZrcmM3VEZWMHhU
        RHBCQk1wNmlGaG1GUXNjb1NLU09udmhXM3E3U3lvUnNTWlg1ZkpQdDFKMFBlSlVm
        Rm5uSW9OZGNEREU5Tm5DWXFybWM1UFFPb3NPZ0VPMTJxS0pmZkVvQU5GZDJFait0
        L1RQVWJrcndoeklrckgzZGgzQnpydXlhYjVjRWZ1NjFFUEkzVkdtV3RncHJYbWc3
        K00vNWo3YVRmWXRUU2Q4VVpLT1MvdnM1di82akZyZWRkMVA1Y0daQ1REbk9TMUNr
        czZ6YUZhMWpDL0F4L2dad092U29namoyL2Q0bVI2em1TZDNvN2lWWmpGOTFnbFZK
        Vy9uK2x2aW9HWXI5UkFMTDZQQnFZT2hHQkdQdGhBY1VsZE5vSzdBNlptSG1zMWZa
        aDJNMVllMDFpOVdWTi9sOXozMEthVW5tTWJSREpBbm5vL1hGd2hKak91cWgyZWJJ
        SmdHeUJjZUtEZ0l3YXdZR3EyNUsrcVNtY1RiNGhUT0ZZUG5YaDlYYUtaN0sxWCtp
        Z0ZMKzFORnovMXYvdEk4amlZUUliM0FWbURIblNYcXdxeGM2empwY3poTDcxTkxw
        VTNhQTU5RDdQeW55NHJuQWY4MGkrWlFtZU1xL2IwOE00WS9MRkRKUjVrSW5iMElX
        M1RZdGFrMGRUTzR5TWkvWUFqbk5tSEk5TTNEK01JQ085andzaFBUb3RIZFhBemg3
        MHBmSUxOVmJJdkZiSUxPY0M1ZzRvMStLcmtxREt3ZkFvR05CTjlzQ0JGZ2ZTRXFq
        TXdxQytmaCtxcWtJY3lJMVhCMkt4RVlWMjNYa1NYcnBDZXN3ZzZ1RUpLWEhmbUhz
        RTV4ci9lRk1reitSbUo1Qi9LN2EwMWY0akI0RVc5cXpKMHh1aGhER0xRY1JUT214
        REpWQThSQmRISVc0dE9SVys4RXlhTTh1YTNvSXdNWmt1VTIxK1RkSFBzWEdvVFdQ
        TVQwYS94Zmd1UElmMHF6SldZKzI5VmFHWkZsbUxPU3pMSE1HUUZJUjVVc1dnS0dO
        eXczS0VUYmcxbzZ1T054Q1hMYVdwSTd3dis4ck03aEhWVWtieDMyZDVkWmJka1dl
        VDNKVEx1UDNPYUh6Uk1KaTdNTzk4eXBJWklQdE53bE1YZU1YMnNQdnNkTlRUWE5E
        YmxrR3pOSk9XRDBLM0VDTTVRN0pXcFNDemlaVTdRdFNrRWY5dnZlVlo4Z3dXZ241
        ZTZiTFdTSitkUTdVcFZxTVBYODlHWDh3N3doZDBpVmRLdEJqQXVmZDhrem5KWDFs
        V1M1YWJ1a1FEbmRWTmtMU2tIdGJLWFpYVUtPM0pXUG1zQ1VtaFlDVy8vZUQrT3lz
        QjZ3QmJNbkxnM2NMQXh2YkRjaGREa3p3UTUvNWRzUnQwY0ZrSTE0enljV3BTNEJL
        VWlyUEhnRjRyRUZncjBnN2xyeUVRWm9aMFZvZ29nYUpGMDBleVk5eEhSNWhhZwpJ
        bis2M1RZRktXbDJOaHJTZHFmaFVzQmpDbEVPdGd1aFJ2b0hMaGxLc1lFCi0tLSA5
        YkJkb0FlcXpBUUtLdjVxMmJRR09EelE0djI3bVppN1VWL01mdWdHc1VrClZSS/Cv
        4pFCM7hr+FnrhI+WyD0goM7QHkFJ/QNkqQIrCNlCASzkzpRqKG5Q8dQ3MMxuvV8k
        qzRtscnKWQ3lq+s=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T11:54:00Z"
  mac: ENC[AES256_GCM,data:6NO3Co111vL6fJZw9dcywsN17x6HgPTehcqVa1bv56DaM4AjgmtY/q7f0yNpnARnQEiKyWDuQt++/2Dsao/4SYm3JBjPoUmQPdKG1YmdsFQ9CyaLstpLHvEllKfupnxbg4Hn9CtTv2gyzSY49eoiAjHxT+cD1aO8gSRapNFF77g=,iv:sYPEGRl/YtXWL5z1dhppneTQTgVhh8bPN266TzRJfRo=,tag:9rIVrwTmPiFm7FYEeiLolw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
