controllers:
  cloudflare-tunnel:
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: docker.io/cloudflare/cloudflared
          tag: 2026.3.0
        env:
          NO_AUTOUPDATE: true
          TUNNEL_METRICS: 0.0.0.0:8080
          TUNNEL_POST_QUANTUM: true # disable when using http2
          TUNNEL_TRANSPORT_PROTOCOL: quic # or http2
        envFrom:
          - secretRef:
              name: cloudflare-tunnel-secret
        args:
          - tunnel
          - run
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ready
                port: 8080
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 256Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
service:
  app:
    ports:
      http:
        port: 8080
serviceMonitor:
  app:
    endpoints:
      - port: http
configMaps:
  config:
    data:
      config.yaml: ENC[AES256_GCM,data:6+DFqUK5fcvbzn7RkyKgYTuc+sv3XQA706w8MkdWpQtTHqI2wLDZa2Op64G0/dnuQxZKGLrFjrXXU0BTTH312jo6sxTRdeT9CftmPhHFZ/No0/1t4VCM6R+vNmeR5PZZoyguzUjWi6Gz+84AZqLvQvme01k6OnwU63F5zaN0gCQbxd8lgDO0LPofAZ7omlQBwPl75XOLLaopCsVU1HLTG3pjjIdKgX4+0FTgrdJPLCvrDUY6mLAdcuVU7nlLIUbaaZZOlJTUjeUm/paLmwE8XMM4pgcGPUYFH/2Z,iv:/4ImWFEydM9SrGqwpfpdBI/+bnA24qn7A9ulJljgTOo=,tag:LmYuVBgiLDR0h8B0Tm0V8w==,type:str]
persistence:
  config-file:
    type: configMap
    identifier: config
    globalMounts:
      - path: /etc/cloudflared/config.yaml
        subPath: config.yaml
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDRqaXBDc2Ex
        eDlXaUFSRG1lSW9mbXZBUXY2Y1FUK3I4SEIyMFRocWN6Q0YxckMybGJIWjB5ckN4
        TUh6aTZvTzFFZFpUVEdRM1RXOWlBNUluSk1ocUFRUHJNU05LSzRKV0FVWFhDYkpv
        V3B1NEFEc0dEVE85VHlkU2d1N0pvbUROUnJmWWJFN0h4TGtKRUFFYVFpcGxjN1ls
        SUw2VGlHcFBKdlVxOElBZm1SSXVUK1JBMzJscU44V2VZQXZNV2NTcHR1RW1KOCtF
        RzNuMmN1Mm51UU5kTTczZk1ZTVBqUGRnRGtQbkRmRVl1SEhPM3dWbWMrN3daZGRz
        TWthYk9XVlREZHNGNjdBWXZoU3pna1kzYUJCNTNpcnh4c09aRmxvdXhHcSt6ZzBv
        K0tXMXFiUHFNMlFNZDdTQ0lSWmxyWVdqTU1rRHNqQlZUbUk0WlcrMTRoSDBBNU5s
        T3JRWThicWFFTTJTM1lMaVBMZ3E0cjIyVWk0QmVJWWs1bjMrYmt4NVE2Z0E5aFV1
        RUJCZUszSTgxUkwrWVZ0bUZyWjZlWGZzTVBNc1JEc2dYeEdvekM0ZzdkRkJicllo
        VGZrQXJPbGlkOUhxeHZpZHJxM1BnQjg5TEpCTlNpZGhGNzJYSDFwbUZnaWUrelZK
        SHdLTzBIcDZkcHN6a3NFaGVGaFBUSUhmNTZuUFBpdG9nMjRvTTNwSWV5NEZadEM5
        b0ZxZmVaWmd2N1hhTFhwR3h1bUZLc3RnL3k3K291bVc2YlRIMm1PNGdpNk1LNnQy
        bEdseHRUeklWdnp3WFo1TnRRMHNFZU1IcTJ3cFRINnlJb0dFc1JTU2dQZFhOeGxF
        TW5VVHlXelE0OVJqVFNXY0ZqWHdTd2NMODNTMDBIVmpNQlhHU0phNjd5Qlo1S2Vo
        SkFQOUowRm9oUk05ZCtwd3A2ekZsUjRyMWh2S2VSWnRQOXk5NHZ2alZua1hQSDQ2
        M0pLemhuT3UrVFZYNng1WXUxYVZ5SzRXWmVBWWtEd3JnM0p5SVdManYzTTc5ZDRY
        N2MvMUdkWFFDcVUwRDIyMWJBdGRzNnV6dUhtQ0cwZ2w2UEVCUGFqZ2JLV3Y2S3Bh
        QUJOdlRkRHNTNjV5N3dRZE1KRzMyMjBCUEdsS1UwUXIwamNJbjY3OU1jeUMyMVZX
        b2ExcGJZNEtzZUllbGUxdXRFd0Z2M29mQ0pUcHZaOGJpR0pkSzU2UjlLdXpZc0JC
        bWhENzBPUGl2U1k5Q1A3c3lFZCtyRnQ0Y0lFWXg3UU8yMkhJM29WTGR6VGRrMU9M
        NlpJVEZabWpKdVFhaUdSS0dJZWpDeXcwVVliUjdvRUJhVzNDVFJyYU1nSjV2OWtu
        TGNwQk13YTJ2YS9HczdDM1R1TGxQVFIyQUtTL3IyQ0h1NDZLV1U0ZGQvLzNGQU5C
        M2UrUVNWVEhLYmU2dnpld2x1dnpQWUNqb1RoeWNMSW1zWmwvcTZJRDVzeEg5cEpJ
        b1pjNk1ldmFwOTRHNENoL05oZVhtejJnOStZa2dJdkdXSnhNS3lFN2M3SnZFRUxG
        RnVtU2xKdFZ4ZFByTFFjZjZpMHhTbzRaRXlwTUtPVEl4YkpjT2tYa291Vld1MXZj
        MnFid0U2TVpTekU4eitJMWNCbnFOanFwVFFvNXdpWUpjTUtCdzBEdDdjbmJvRzVR
        eGZTYjloZlYveGs1SHI3dGxoSDBwUmtlSmtLczE2bkkvcG9WalpFUTZLcUR5V1lh
        U1YyeWc5WTlyeXRybmRKeW9xWEF2NzR0NlhqYUlKMW8zelZPYlRIbUI5ZU1XSGNU
        NmhoamlYb0lGSXdwYXlMQW4xMHNuZEZXcXZJSEk4NGlBNitsSjlJbU4rQ2t0VGNW
        KzNmSDgyMmdFSzJHOXlMSWxINVl4QUVuQmJIVStaSUlBRTU0c0h2NlpPZmRzbjFH
        ZVVvWHYyREcvZkZ2aktTZnd1b0tNcDBTTkJWVFdvMjFpeFo1b0NGNGVXMUJaQQpk
        b2MvZnkvZ3plbkhtSXlCdU9DSGl4U0lqM0ozRmhjVVRWU3gwZm95RmxjCi0tLSBF
        ZFNPSW5reU5zMitxT0toVHdHRUMyNXJxYmwyZC9XSGRxOWdmRmJpb2ZzCnSclKMv
        t0bu2DUHWHeDhAVAHFqcJWnd4vUWoq4Mihsj+eWx6F5zjvKutpD3fId/02dby1Mx
        XWTwSV1iLbpxUkg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:27:43Z"
  mac: ENC[AES256_GCM,data:x99opGe/7OJKzE4+Rfx6tifsgObb9DozQE0zDqAKsF9sUB5feX2SHkscIBj4BZYcP3KVTTXC1DZJjGEngI8WgfJ/IYfse4QYQyJZJtMc0AtWyPMK5uQthjpxh62PuGeZXONYCAKr2e8jWHTj3hqZWbwcBhEyvI4xdAbqznAa6Ns=,iv:dVhIkjO3eH0zjZEqmuyrV/OvnkMOH+VUIt0Mo9MoOPE=,tag:igs/IgsZanR1gxfS1y2Aeg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
