---

- hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "Run k3s-killall.sh"
      command: k3s-killall.sh

    - name: "Run k3s-uninstall.sh"
      command:
        cmd: k3s-uninstall.sh
        removes: /usr/local/bin/k3s-uninstall.sh

    - name: "Run k3s-agent-uninstall.sh"
      command:
        cmd: k3s-agent-uninstall.sh
        removes: /usr/local/bin/k3s-agent-uninstall.sh