apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.${SECRET_DOMAIN}
      recordType: CNAME
      targets:
        - 82a675b2-425d-4816-965e-b81fa9053660.cfargotunnel.com
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFE2OFo3a0ZW
        UTBNTmtybjNhdURNQWtIWEYxVVo4Z0dqZVU2bWtla2JMaW02S21tU2N3SG1WeWZs
        V1ZNQWRHVk5qMkJXVHdtK0dNWEU1cGpqU0gvK3lWSFJuTWFZWS9vd1pyTi9jdEVZ
        T1FtWmhyemx5bmNBNlZzcTJYcUc3VVBxR0JrSENud2ZPaHMrTmZSQ2IzeGJ3dCsv
        ZGtCVUl6K1Q5bkU0OXUxREJxRXBUbWZxdHkyeE1wZzVMODBHdTBwS1JCdGVyVVZm
        S3NzcU9pS2c4N3NqYVZVRCt2OGZJUjBwOFBCZjZZRkNiNENoRGJPdkNzUnlnNjhi
        NHZySll0SlpIZ3VXTFFtcVFUZU8zTnVrQUtKbXN3eUdrMjY0NmIxbzhya29tUm9S
        amFIb29FUU85K1YzYTNmaFpjV2N0QnhBQ3cvNTZORldKTkpaM1JlbWlnVHRvRDhx
        WlZwUU9LbEFUdXdGMjlFWE9yQUV2cmcxOXo1b2NqYno3SXN6SEpEL0syWWdnUlc3
        dER5aUtOV21PaHZNdm0vRDdkWVpuSTRkcjdLWEd0WlB6cjA0STJsRFFBQ3ZzVHRx
        THpBODBmckhZNE9hU0RMUno0ZnBUUnlBd3VXZGIrV1ZjWVg4Z2NkMmZkMThyWXJ6
        cjFjbHpKeGVmTFFsSGhxNkE0UGMwNGdhOEVFbE54cGttazc5Nmd5a0FnN2Fxekoy
        U0FaNEh6Mm45N0ppNGM1RkhQbGxDcnZ4ZHNMWVlJK043UGMya2NvWTA5VEFzOTZj
        OHlZdjZrQVlOejFxOW5mTkZoQW1GZktDNFVNeGF5aHQzdzBxMGVEZzhhUkJIbERw
        d0JBUzRiMHNRdUs0Qyt1OHRPMkFuaU15OHljOHpBQlh1WW9jSHAyUkZrUmlyalgw
        UmkvOTJVK2w5UG9hNG9vY2hJM2hXcTN3OS9ISUlhMWdmejlDUHRGSXNuVnlyZERy
        TFI3Z3BEQ0pRSGxXQnowODcyb2tndHpVcnBoQ1VaS1R4bkFNa0trZjNadS85Y28z
        amhxRHFzRWg1UERBZURGcTgzZzhDQ0t2OWZTRzVkZWEzd3d4T1BpMG1xdmc1TGhB
        U204d1RHT0tCcVoyS1BkRkl4cmFFc2VHRWlyVkV0cGhtWUZQUVFqTFl5UnlJQm5v
        enJnamFHc0M5T0JKcGk3TUZRSUhVQi8za2NmcWRqejZFZldqampub2JYV0FlYlVW
        OGNDbkJsclJaNDU1eElpdzFQQWsreUh6c1I5aW02L1hoTnBHa0ZkQWxjRkt1Y3RK
        eThnT1JQdEprMW1lQ3RPOFlQYUlMWG5yMm1qbTJBYlliek0vTGpuLy9CMmx5N2Ri
        SDNRNFVGcUM3Yi9DV3lYUXBIVXRBTlBIQ3ZCcDRxTS9yQnRJTGhjekNTWVBuMHht
        TnlJWjJYTW9UM081RVUxODJoVjNoYUxZeE5YQ2ZkaTZsblN0UWZqTWdUWDF1TCsx
        a3lZcjlMamtWTVNGNTd0cTdqZmFhOXdhd2hBWnZjaW9QVG5pcSthOE9yNC9yNjVP
        YjdZWUo3QnZIeE9ka2NhSjZPTkU1T1U3ZURwTGIwTVZTdFR4ZHJYdDB0T0tKV2k4
        UE00NGpwS1NEZ3E2ekp1SkdhSDh5VnhMd3MvSjBqNlkycVUxc3dwWEFLbTl6YkhM
        dGl5REpRQ1JLSUtMYk90VFFzcWVvQXFNaE1ZV0RiQUxYMXdsazl6ZFhiUWgvOWto
        VUQwODNjRkNPUTZPbmZxVUtEVU8xbVFWWHdkUkJYZEFheVkrMjZleUtzUHZFd3Ew
        WG1ReEkzVkh6U3R5MXhtbVgxKzVYNkZML0EvSnJPVXRXaE9JR2ZrRVM4cXlPMzJi
        YksvYW9OMk1EeU1EbTRLNUNyMUk4b1BWcExFZGlGS3pVclpVVktCRGNWeFRzQW1m
        Z292clB4QzZ1bzJ1N0hUVjlJNjJYYm9aNm45MHc1WXhFUEc5QUJMMUhkcDZBUQpz
        RnlCUnBFbEozYlBvbk1NMjRhVmNkTW9xUW5YN1hLWmJjQ0FhWXBCUCtrCi0tLSBo
        MTRiYWhDdUVmUU9CU2syUEhJN21ZbFp0K0gyV3JhQXBHQ2xOWXE2SExNCvXQKN8r
        OgD2RRUygvT7VGpBOGzuj4lzzl6TKdsvnChNkF/HT5eKP73k84RdbsL3AaTLCScr
        jZNrkF0AyEbq+nk=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-22T22:46:39Z"
  mac: ENC[AES256_GCM,data:ys1hc9sUd3KPjy2kJLyTuQCmxF6sAdT5VO0o2WQLOsaUeAlJyQT5WGiMIQIxw+K4Q8zveQU5hRkN7hUK2jP7Rsa1nHeljS4uW45iioqA57aaDib8ZGCkdWWdAufZCBNODOYvF24Ul4XCNtN+hyQKkgJQuj8BNhxZfjzKTtUShgs=,iv:AWqag73AgGMshsjsZCZ7fvvANx2aYsxfJt/hK9c7Lbg=,tag:dD1OF7mQscJCMaIf6pzBxA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
