apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.aknuk.dev
      recordType: CNAME
      targets:
        - 82a675b2-425d-4816-965e-b81fa9053660.cfargotunnel.com
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG5QcVBPT1Y3
        RWEwSWlHU21qU05uTjQvYmd1RE5VelFyY1N4SVh2YTBxY0J2MFBnSy96dzVyZENN
        REovZENoVUdHVWphQTZ0S0MvcFZIRHlHNTRQVC9iMnpYSCtaVERURzNMRUNIc21V
        b2RoelNGMG5WOW9qVm50cXlhOVA4eURhcFIvZllaRGRsVXBIbUNsbDJlRkVvdXNQ
        bG51MmNJd2Y5bTB2K1JHSXdrL3M4WisyOERSSXdWb1U0S0hXM2gvVExvK3J1ajB0
        dzliSHBJKy9la3pJUmUwMGVPdXJiTzZ3ZWNiK2pXenNtZGRWdEs5cmxadjQ3bGkv
        eVlXUGR6bzZDK2dNMkVLbEdXdTMxN0IzYnMwUExaTlZjbEpNOHhwZnpRejZSVjRw
        M1JXVi9JU2lMRjJBTWlRSFNxSENGR3Q0a1I4Y0VuT3o4a0JsUEp6MUZYcGUydnZl
        Sm44OGdJa0paL2g1NjBmY2VhOXY4UzcrZzFVZ2I3YUQ3bEs3T3JmMzFSREVrL2RJ
        MmVLRGk4QWNvaWNGVVZaanZDb1JEdmxZRktLUzZRelBNRkdSK1I3VnZXVEd2eUc1
        MEI4cVpuK2FRQmJUK281N01ENDBPM2RTaWd5NG1odzN1cktSU0gwUFB5UExTeDFq
        WUowNW1lZUFNQ3NkbHY5RnhDWVRod3Z6c0hrQit6aERJU0hYOWYxTlRVSHFuMEpK
        SUNoRzBtaHpUWlFjeVhjcnlHd1pNNG5tbHNNNEV2V1AwVnJRSFIrWWZtVTVJNEJx
        ejVxbjQrYjIxbWF6c2EwZlNsV2JFOXNHRkExMGdTSnQ5cFNlSll3L083OXJBLzJV
        NG1jUkV0OHdib2w0dTkwY2lrY1FFNmdPOU5oK1F2eDN0Qk1KTVdYUk5MUHV3dFFT
        UjltVUNpMGNwanJveVcwNkNCMXc1OVFBbWlsQ2NFY28wTzJHVm9JUWZhc2dPNllM
        VDNXa0gxejNJb0Fic3hlMHg2eHRoSnhmdEJ0MW1JR1NUUTVMOG5RUmR5UWkrcmM3
        M3N0aUlJOFRiN0hmVmRZMExnTmJWcUgvd3FpbWlHYWJwckUvUlp3MGhSZ04vNURx
        V2w2SVAvdU5CaXhFa1dGbG1GRnNRcVhqTE9DMERBOVE1SzUzZFFONlpDUlRuTW83
        a1BWUmR6T3IzUE55UFYrMHBHYUQrNi8rZmMzcVRJU3lWbDV5UWlkdHprYVZtNW81
        NTBPSWhGd0VMcXZOYlVLVGR1SFpjbjFySFprU2hpbDZXSGNOSndkbWYvY1JFMURV
        RytQSW5TRERQTFBMYi82am9BUEZKQU04ZnJMaUdIZGNVT3ZFSndteTJSTXpHQlhH
        a3RrY1FaRUhhaTdBMzErTm03ZG5rc28rQUtvYWxPYzAxRlBEVUV2Z0dmV3p5VDNz
        Mzcrc3JZdXg1WWVCenA4QkU0dWdNaThtYWUvTmZSR2xkcmlnOXk1UktUV1BVZzNz
        ckNPZkpQbHpkaVdTNC9JL3YvaXVGVjhDZWFQQmR3NUpiVC9YVURFYVZoM3ZTd2lU
        MWFnVVNWS2VLK3hRZWZWcVRZRVMwOERCS1hlTGJIZVZMZFRTVTh1dXdDRFYzOExR
        aEFTemZFd1pBb2pkZ2NBeW9TUU5NVG96ZFBEY1FFeEtMT3BLMExxZTBlMEpWYUpj
        SXlwZUk4SDJRR2lIMEkrYlNzaVhISFU4Y3I1ODdRNTJYYjBjZFlZVUJYQjlkK1pZ
        RllOY2Z6eklnNkNic3Z4VlhZKzk0TjN1Zk0vSm1jRHpDRU52aVUxa0NBYkhFZ2ND
        YTFmZlhQeU1qbWpablE2V2kwU3ZMUFdwRWZxNndxVW9KdG41VStmYWFZOXNMa3Nh
        Qms1YlhrcnVWU3BaclB4aWV5cHhFbUhubWNmLzY5cVZGVnNtTnhiOG80SGFtN1pM
        VGNCbXp3NzNmVmswaU9IclVKM09SOHRFeTZvL0VBSnJCZ1IxVmlHOFE1dXJkQQpv
        UnhDNDdEUWlUcHlWczIzck1DbkR3dlJTTGlFMkNvZDl0ODg2cXBGaHlvCi0tLSBW
        S1d2SGhLQktQY0twQnNPdm8rR0ZQM3J2bjY3VnNuYVFIakRYcWV0NWtNChGVRAWp
        Iaqe3ge2xdYv2yswngEYx1Xuefeevl9ZGS65BSA78wuG1LwZO1oAY5izRF8gghxJ
        BmiGIdttQIJ3LNY=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:14:28Z"
  mac: ENC[AES256_GCM,data:r2MaikMlHU4XRXCl8tkfhVEcteLWK6GdiEp3Ws11A1XAQKfvd3hn1VqFtCxfMphtD7PWpj4xY6BJzD0kJBN2Sd8ufMMibuAHMYw2H9QbDaYKTE2BrJYPta55nLYMQU70DypLsrCsZVdKaZ3378hRdGKFftNrqia6sTRi98aBCl8=,iv:KXPzP0NjUZXaF/A/U0thURmZ2j6ngU+3WMox01VXKwg=,tag:lx81/mJTvPOF5LH2Nbuxow==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
