apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:wlFcYbgsV00sylmNTPHpVU/5FE85k/kCzgD3yhCCCwBCS1fjuSsJrJ9BXDtSTzb/BaU9jb6/wPpLJDQBxejyE5aPSZ73adjVNRqzx+upaekRH7BAUNhJS49Ix/Vsldu3r+144ym4QDsEWpsILN9uSuhxA2pf/YO9g/t9Af1p39OyKxZyG7uZTxTV9UvcOAAHpRr+z6PGFTKvTGnmifaJ77y/VbDgCuWvDR1lWp0qyo927O30,iv:LxklM7kPa8o9t3S2VpLGvb0BZavtQ1rNY+wqpt6c9gQ=,tag:04qManO3JLS1yn2yvc7kaQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEd4Z0J1ZS9N
        UkRYaGx0UmN2alRIRmxxQy9pSVFNNWJUS1dDWWJINmtOdEQvSHBDV2hwNXQ3dkVi
        TmN3RzJubjhyZkNOd0xGc295WnYxUzUrbVgvbFcvVVV4NjNIZ1doclBVeUR2dys0
        TUs2TXpvTTAvQi96U0NITlYxbVZwT3BxYWk3MnM4eHFEc3lzNVg1UjRrcmQzang4
        akFkMGRNb0gvMTVCSFp0aS9UOEN6NkFDTzNMUHZGbktnRitXVklqNm9DKy9RQzNR
        MmpXVXhWWUFxdFMzNFRKdG9MMnZUVGV4ZGtvNWpiNWZuV3E2M0pKelVyeUZJOEs4
        NjdsUWY1Rlc4WEFGRUtuUnA4Z01GM01xcFMyUnA5akVUcjcrSkFvN1QycHFTR3FJ
        TG9HUEV4SjRFbENTcVZ3S2xGMVpBZ0VjaGg0VjlpWVpLb21kcFNxNThTSFdTckFH
        dEtFSUJyblh2SUZSNmxSZkdZQ0JtUWRHR0tRK3dpZkkvckllWVBrLzNEa2dreHF4
        THlha1Q5Q01Ub3Z4QmhvNXcwNDFmRXAvb1RyWmxpWTY1aHY5VGNPeVdQR0s2WUty
        ZHV2M1J5VTZSRzMxblN2V20rTSsxa2kvWFFVQzQrNW5sWktEb0JrYUJQV2pyK0My
        cHVwbjNaZG5wOC9kUGpzRjFhUXR3ZlRuSUN2NmlyM2lIcEJvZ0dEWlJsb24zL1o0
        M1N6akRIeW1iYnR4REQzRG9DdWRUK1YrL1BtN1hEbUN0d0ZzMWhFQlVaVDhNSXNH
        UWI4MHdCNk5EUnpRMVBxekIrdUFuRFRqeXJnU2w3RjY1TmlVdXBPU0JDVzdHQUE5
        TkRibEpUdVhsdlVFNmpUUE02OHI0bUdNWkZvOVVqeWRBb09xci9nUzF3THZRWUhZ
        eUxaL1pWNjdFY3VvRkMrSmRTV2NGc2p4STNDa2VPZUZpSERCb3l5MVprRTlLMTVw
        dElnRGdXelkyMlQ4REhoYllTQXpzdWJXR2g3eTBZRU1mSFhaWUNJdTUvR09QTEpL
        WnNkOFBvZ2FwcGk5SDh2THZxbFVITmplaGZDUGQxWm56YnFqUUhOaWJ2L0VTNW9S
        eGcvTDR0VTBoWE9xeTBMeVlidjc0NTU1MmNFTzhBd0hNTWt2d0pWL2dQWW5WSjly
        eVI1VWd5aEtqZWF6Mno1d04yNFV4MFhycmZTQm45OHorSzdhaU04OGJIWFprQjBX
        SFhpaXBkMHQ3SmF4VmhTbHF6ay9QaVM1TStGTTlOakx3Yk1GV1ZEMUJ4bTk4NFVz
        VG95WWFLdm9kNlAvOTJWaFBldFlFMjQ2clByT3FzdUZZSmxvRE5kd2pjUGt3K3Mr
        L0FrTlEyWEVLSUg5WVRoSERDcGlENE9ObndNb2p0b0gvQ1hScG5NREtjQnJpQmd0
        clpnNzBqaEVCenl3TmxuMk9DR0JpQVVEcytleWZpUXRKZEpqcXlUU3VvdjVYeUJS
        VlZsNSthWGQxZ0xXMUptZ0wvWkc3MmZtTUNGdm5GN3B6d24yWWc3WXlUaGY0NjND
        M2NFVy9OM1NKL0Q2d1BFdk9ZS21uaTA1VWhEZWJ3OEtqMFpTcnl3ZzF5b3F1dDIr
        dStWSVd1NXBZS0QrTkxpSkhGTmZKeUxUeHZJVGQ2R2dKWGNzMkxOa3pTMkRNZkg4
        MXREQTBTUzZ5eHVjT3RmYXYxQ1dRSzMxeDVsZ3R0TkJsWStNMUx6VGFSZ2hFZTBp
        ZHB0cDhSMms4VERQc24rUHdnZk1sMXVIWjBtdTlORkhvVHUwd2xtQWRQTE9DTTNU
        VkVZVlVCQ3V5Tm1nNGtCSFVNTU9TRnZ3ZDBhVlAzSVVvcGV3d0NKTUxTalZjWE1P
        cEw1YWZYSWUraVB0eEY5QUlwMHc4OC8vSkNteVJRTm90SThOR2JpejBYRERXNExB
        RTY5Sjg5ZnRBVWZKUk9MZks3K1VMV0NDT0FsUnFsNElRK1dUWm5qNFFWWXBCUQpv
        empvT0p3Q2VWcGdkazdaQUhVelV3WUJsZ3c2Z1FINTVwK2lVVXdlM0JNCi0tLSBX
        NFQrUFVHbXlWTjliZFl0RHh0YUo1K3VoY05FQzdFM1BZeU4rMm5lOU5BCi4avAX3
        MD+GEnG+m6PUBRj8grNnaPDQOegvVn8tJib910iFgy6urQcRGIAWQ+llskevhB3S
        s14udjeN4z7bMAI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:27:43Z"
  mac: ENC[AES256_GCM,data:QTkLVOaftsP/k2i6ExIgTLM3Czn5mQ4zOsqLIgXv5I8SCbNOUh5iPyu6NuaLMox/B0wUhh4/cRn5c0+Srm+u9YOnbyMaOlyhxjKbM0evD6NCdTMPN6lsbQ2XyTVl6em7ojlGHZzgXIuKBv4HBwoN2Cthj6BxRrFHLLtaTRa9QAQ=,iv:xffFaOJE2dfcAvjkHyqaWNuJaFeqfp6IGkSPuGB92ds=,tag:8jGuUFLcudhTkF7xgUk7CQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
