apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:BCGQP26JKub2+NStYHDaO+cvtt8JybLAJZ4pumgD+oceIpBZb4280ExjrNvqlPLOElFVIFqHK5INEvxlt/ytopyR1GbIQLPMY9ZhEitKn+/WEiYOUpawW8Zbc6kH/MPuHp7f2jJu8iB/nxY5c3zVOHYQuLS4GXgUku33/Tp8oT8bNSqxGst5hScariTP4tAA+zCxfizE0YGXMMlglKLfPQI8qqlzXtEcpFSfjZidMZO0IzVF,iv:bJdbEqKag5Kj42kZqGbSfYqEf5oRLpb0Tp+9MGNJqJc=,tag:UWnla5Y2fwm/Y0EDOOu4KA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDVldzRXUmxY
        VlJidVQydDZ5QmlXR2pMb2FKVDROdFFGSWY4dHRWNHRoK0oxUEtnNnFuSVFBME1P
        bmVTWmw4eEg3SjQ5YTZINXhQS0F2WEhWVHFrKzRLT2krUkR5VXV5T0ZpNnh2RlFt
        Ky8xQlorcysybElteDhzaVNneGE0UndMRjVsVUVBS0VqUUFqWk5DdzAxOTIvQzBJ
        MU4wWEErVDQ5OVRmSWl6NVJ6WG5CcWJ5TFFWMzZpWjNFYlZRYzZ2a2VmNTgraGxM
        aGNtT3hUV0x1RTZUamtrZC9jSmVKcW9HUXVmNjRJVUEzMXUrT1Y3anRSNjhMZlAx
        ZGM0UFduZzZrTnMxZzkwUzFiN0lhVUpaR3haenhIcTU0bDZCNmlxZHJqUkdPazdv
        RTd5RGR1L2pIYkRvMjVYT0tDa2gxMDlFc0hYc3A5OTRZUHJDRGJOc3EweXMrbmpD
        YktyVHFSRzM0ejQxdDEzNXFpYWRxUlR4d29iOE82YmgrUjNmOHAzSDQ1Yjl2SzRK
        Ky9LamxkSzZBZVlWekdlaVV5ald0WXR1RmxQa3loeFg0UTdPT051UkwrT2E1Ly9X
        ODYwdmNCaTA2MmVrR0FYS2x5ekt2N0tEb0xBMDkvY09pZC9IbEVWb3NMVlY0OWJZ
        Nzk0bXYrWlU2V0VPWm1SU3FYTlFIeVp1MTJMVUhMN25BS0ZqdDh1K0g3cVE1Y2Vp
        aUxZMVMwdzNtR1NWSHRjbVdLaU9uSXh3ZjhnV0NyclpBeFViV2E1OUFXd3kvNjl2
        NHhTS1FyRG1mUXJjNDYyNGVSWlJyMDJKS3AvT3NQRUdFMXY1eUQxeEZzNGxISXIz
        ekY0WkVrdzFGa1d2NkY0VG5KR29wK1YxSmVLenZSYU9nekdUYXFtenhGM3FZbFZ6
        WDJZOW5HaGRCK1JCV1c3bDBNM0JNU0R2OWsxK3ErMUJ5ZlFOd3ErdUR2NXUzT1Nm
        Z3dxQUE5cmR2RUVPM0RZSGR2b3MyTGJyaGxiamY0Q2IrQitPWEtiQ3kvR3RXekR6
        cU1TODNjZ0NFWWtEKzdjMW1hY0l1UU5vVjJOOWVsOFVLK2p6OFE3MXdXM1dkWEJr
        UUVrdm5vQk0yRXpHSHZWek1hbFY3MDRjVUo0NENkZUtsZGp0eGRRRE9DSisrRlJq
        NDl3MDVRanBIbXJCL3ZFWnR1Y1dxWWZ4OTNTc3FCVG1vM3dJUVBlbGVvWHgrS3Ns
        YzFOdXl1UjJYcitDWDFFRDdaOUVkeXdXRE4zaEpBQ2NLMU50alRoQmVXQ3hnV1NL
        d0lydlcyYjQ5ckJrRTdCbjlhVVAyOEpRZHZtT1hLR3pyeGNuR1dhYTFaYXc5L042
        MVozcUtwYWR4UHoxTkJWUitkOWF0dzJZb2IyRTRrR3VqdExkbTd3VmZ3eG0yQkJ6
        aUYxOEU2dU81d2ZONEd1TjRWMUx2WWpxcjh6aTZRa3ZtVE5OV1ZucWVFZzh3REt3
        UkQ4U01WU2hBOHlEa3d2SExvL1prZ0lEYVo1eFlNZVRYaE1lZnZTdCtIS3hLeHM2
        c2J1VERvRzRZaUlqYnh0c2l4ZWJTSE95NnhYSGdtL0NTL0tTamRMSmdvVE9RdkNX
        U2d1eFRVTVZ3R3dCZG1QUk0xU3VKY2ZoeUk5aStKVjFBQnVsMHFVQWtxTWNhOFl6
        SE91V2tGMVI2dGtIZ05iUHVRRk1UR0EweG9PajJZN2dJL2RyUFQzdG9XTFc3Mm0x
        dXNuTXV0R2FOdjZ2enNzMU5sRzl4LzcyekZUeCsrdllCYkl2YlBrWTdPYjViSzhI
        VGdlbWZTS3lnS3ZEcEdEdStlU01hc21wL1liLzNZbmY2aEZmbFhiWVJwWTUwU0Rh
        Q0l0YldQdTljZ1M4QXBKZEFDT2RFZUtRc3diRm5vY2pzSHhwL3FUOHUzMXFSRmUz
        V2l6Skc4UHdsQ0RtQkFRYnQ3RURLT2xPUkFSQ1FJbkNCQ01CR3JDMk1WVCtCQQpP
        c3hGRkZlYWg0UklQQ1lBNzFIdXJpaU5renZHcGtNUVZ3NDN3U1l6QkFNCi0tLSA3
        NW5CYzRRVWdVc20vNFlQTXlFU2pPc2RkcTRQZ3hJa0J0dzRpaXYvUk5jCsv3/LIh
        UiKKhh9aphazOt/OFA+xCvPMjj58k4Kxozz1SBzYQHIGQatUCbVCp2ROCmlnj4SF
        82HXVPKOFHsPcbM=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-09T15:30:58Z"
  mac: ENC[AES256_GCM,data:2ZjQhZ9Rp31pozJGZG4ZLDuMCoUz3MOFOTV7lhXz8wpJeFYvgMJj3Vou9WYi6Ul8ngcwh+9WL1Fd523yMIB/9oEcdW88/nAKrSfdbtywZo69RtmPvm1K5/lnHz1/CGvWtsGjiNmCbhtQIiDfyVFmZvIV5/ZxcEmD2733Apw+GqQ=,iv:ybHvZrIVwcA09XH1dJqQytbPgan+pOpUTws36sGBJTw=,tag:b3K7Bqb9LYvntZ9rucOBzQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
