apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tl+K6jmashY3SFkcHaBekMc57Tadls1aVx/kETyTdwdP9USW/TrIgECo8X3+uve3EOTdQKfcDcvamWDge76hJ8BOyu45tW7eK82jp7i+4s1nXif5KQK+nL+YUIdGDUt23jqfOWx/zd5X713V66jfFjPmIyKXpvIo5sHthGI1n7Q5ZWyYBhu43ieYW3fynGB/yWNnnPoca1EBFXa4UieD3J7CPJ32DMJTzTRp0GPD40+Hsrcy,iv:d6n7CXks4yJp1kHpbFdFaF1AXuKgFo7XKnBsRKJD8rs=,tag:2XD2ZF97utX0A/2RzpdDmA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFRjeHJTTTcr
        UE1wTVZleDM2N25FU2E0OGZoYWlDOUYreXZHQXNGTXYxR29PUTh6ZjNWUUpGakF3
        YXFTVHpxeUhXeENwRS9mbUVLUDh5Um9SOFVGUEJlMEZqS05lNEZpcGc1eElZNW54
        N3NLQ3RLYS9iZEtMZ1lwVWJVaGFhRU50c0ZJb2V6Q0ltM2t0djRVdmM4YVYwT2lX
        ZTVzeGRSVmVHNnorL2FaNDI0bWk2ZXJtVXVKemhwQUJTRldQSDZ1NXVJNlNoWDV6
        QVBkQ2QycjgwaW5GS3pES1NoMjhRZ0ZrZkVOUnI0YWMzN2M3aFZ4RlJyTitjMU13
        c0o4OTdMUTdkODYvcGxsdEZ1c0dTaUFmNnZpc3pSQTBKNXlDaERlU3J5RzI0K3Nn
        OTIzbDA2NW5nOWNoVmdSeHV4aUNJRmMzWjlOT01qbWw4V0pBTDdPUmp5OFM1bGJF
        cy92M0liVnNVYkVmOUdBM1RURU40OVdreE1UaTVOaXVIczhhRGthUzNUMjFjNGFn
        dGZzck9SSWQ4Umt6VnkrbytYU3lBTnJmUTkyQ1NTVTBOSG9wdkk3dldZN2dCWHZ4
        WVdJOXovK3BjT2J3Szh4YXdSbXlsaGRQY1VQYTMyT0lTczBXdkhUS0cvTW95RHdP
        U3RxTmFDcTNNRkFNUjFxZ1czbExJRUZvN0xzWFowREhVUFdPdXdWdEJmcld1L1lP
        bW5tcUx2TVpjTVlRaXprODEzNWpUMjRRVXo3c2RlRUtkTTdKckZjMlJXeGpqektC
        UTlLOExvajliWkRaeXJyMHQydnE2Z0d4ZVJkTENDdW55TDBqMElieXhzWUo4bG1i
        QkR6dEF1YVNVUTRYcEhPTFNtNnNyVkhkZnBOVFRlc1NyM3pSbU53WVZnaEdReGRU
        YW1XQ1VsUGhkd0N6RFVQbXdkL2tnd3Bodm9QRWFRcU82Zy9sLzgxcDdaTGZNZC83
        MlA3b0FDUzFLNFJrYzZMMUdMSUpwbW1Ubnl0N0NVNWl6MHR3Mm5VNDZVSGZwYVBo
        VTFQaFM4VmxEU202LzFkNHlkYmJneUtCTTBCZk9YMHdRMTJKQUR2VXhDL0pqUHhT
        OVA4QXprV28vdk50S0M3OGFkVW1CZzM4SURNWFpOSHptdkp0QUhNOWQ4dzFkSm5H
        S3R3MThsTit0dVZBemZ1VFlTRktBOE1pdFlmYzE3QTlrd1ZXTWhuNUJ0NVdvL0R2
        TmlONGsvd1RVYUE4ZlFoNjFsTEdEYTE4S05PbFhVdEFHVkFQTWsreTcwYU91c2g2
        c0duOHlFTUxmZ25rYjZSRVFiOFpQZEttcjBRcm9Nc0RaVnkzK29nY3Z0Y3NYSXVP
        U05hclk4TzZnL0xsSlhTOGh5R0hORm9WR2UrcEJFOHNWL1F5aVZiR0llVC9leEkw
        VlVLTEJRZGpLd0h0N1UxdnhSMm9ZeXFRaC9nK0w3K0lUZUsrazdaMWF2ZkozMFY5
        RWJqZHVrWHVmQ2U2ZE9FZjVlN0FpU2kzc3dQV1VsdGI2VE1RUys2MURVbENoaFNE
        bDgrRnFiN0Rnb0hSNVg3Q3BYSnlHMGh6VXpNNDgxRHkzYlp4cmNLZWlUSTlrRUZM
        Z3Bvb2JveFpZakZ3TFphOUd0eTh1N3VxaGRtWFdDY3g2NVptT3A0VktSS0lGRlZB
        aTJmTyt3bjZMa1d3eHppU1NaZ1NmTnRUek82S0Y2WmFvaGFMNnFYVmthMkVoZE5O
        UEZOZUhUL0JUYmNPby9KdkoxdDhxb1k5bElMTFovcFprb0NKQU04bTFocDB3WE1R
        VFBSZkxGckFvTmNpb1c5bVRITkRFSXJhdmNFR1BiS1d6VmhpKzhoS2daV3dWYUU0
        QjNzVllmQWtDNndmQ3prcXB2enJwbjRnUnc2cEN0RWFHQk9mditaVGFoMXQvTkph
        cG1vamNEUGI5azhyMk9IeUlBZWhFbHo2bjAxM2E1d3JlM3dSNTJzd1pmOFlUQQpP
        TStPUVZNSGdDRi9CVnpGYXVNc04xblZaaU5iNHo4cXVDSGdaOGdjTW5FCi0tLSBU
        bElsOEx5UUJvT2JwWU9uWlVYcUd0RTVWcUtESm04WVd4ek0xdnFJSUU0Cs40Up8U
        reClMlTdlu/KjUbgNMOwY3ArX6xYuhArQjWI1j0IVayEg1bmqZTwbtKs3ttpddba
        aSdKudYbIynMSJs=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:14:14Z"
  mac: ENC[AES256_GCM,data:N7B3hj5JMROEISAkqPDs1OhspT8Yc0T/Q5P+JbVGu0CYYYCHhTTMzM4/I3hLLTrRroG9pVrRQIo21V9uXVJQr3DJ48ZNqsdx8kNvpgsKvzw2rQlD40x0LyPSgYokYLKLBa3n5dM6e5RI7LddEO2nCosylBsNtVx7KyvLbfTXMLY=,iv:ylbIrLvTrbW69fTh1GyuZv2jg/88qzH/T74Xm0W2+z4=,tag:wEZjlHdfwsoWVSqZ9kdHMw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
