fullnameOverride: k8s-gateway
domain: aknuk.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    lbipam.cilium.io/ips: 192.168.49.202
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEE1RjhrQWVM
        RHpiNDNPbnNXVk5aWUx3anNzMy9aN2pHa2hBK01TaGh0dFEvY0w3Zm1QVGl4bmJM
        WVozV3JYSzlRRGVpNW9XbHNBMHltV3Fvdnc4TmEvQ2pEbUNlMTVwY1Jud2hubk1B
        cjFnWVNFQ3VKZUtGZTk2QkNueGEwc3lMSUF0TkE0d1JrSjN3WjhGV0FRRlBoc2xB
        RHdQM2pMNTNxVFExNHNtMDFpeHRCS24weHoxbzIxMlpVZEV6ZER5clBFRktYemVG
        aEswWXQyK1RMdCtvZ2VvRWxFbDB0eWZhZU5DN2hCTXlvVE1pR1paMFI4N3dYMjN2
        RHRGSlhpVFJsYUtHN3daRm9jYkppdkVMN1AvTzVBaWdkUzJRcGZkd2RjR0YzeFVM
        aW1zdFI2d3VhQlVQdnkvMi9HZksrN2hwWERwck5rTWxGd3RzMU1ZMFVwYUZHRC9O
        SVNZZk9MVy9uYW84aXozRXJvRy9XWk43VDJjSWFDOHE0UGxFdFpTRDlwZmxkNGJO
        REV1K0s1UXBlWnJZSkdpZlNzanVGMEQ1WWF5OWsrbVRURlIxRUVoU2NpeGwwMk9R
        bjl4YW5mUXpmTzhlNnY0UURCZGJvUjZiTTdQeEZmKzdoTDBjNUtCZjExUTVJb2Z5
        VStRWFVReVVuZzE0WWdRUFBWTUx3TElpck1OMlZXdjFMcDZCOXIyUExsYS9LTFpa
        ODdWcGNWSHUzcXpKN2tXem5DYkloczdPSHhIWEw5UnhFTFMzWlIrTE5tSXloQUg0
        MWtjZ1BMUEI0WkJoWlRucThCTS94SFMvTTJXQzF0eE0rOFA4UnVjMExoQWE5Njkr
        b3FsSVhiRjlhd1JWVS9HWWgzZXFZUmtKZEh6YTFETGpnS0dUckp5ZS9yU3NZQWE2
        ZDh3NkhJY3lOSENjTlM5Vkk1cUFRZk1Ia3JkR0l1NUNIeThZZU92RjhZMXc1c2hP
        VkRjeFBpZldreTJYby9wdUNVN0NmOEl1NnNFK2tBYTFlSlFxblA5TXpJQStIVTlP
        QjJHaGpmRXlmaUk1YWwyTUczOGx4aXUvM0lXNkFMQkJmN3Jzak5GV2YxRGkwZzFG
        bjQ2MVhJTDZYT1NaTWZ5MldPUFlZcm4ySk11TkFWYlhVdVpJQzNBTmIxeHZPNDJq
        SUJZWlVyNjlHSXRCc3pRK25WNVB3aUxGemY5Nm44YWh0NEd3UU9iVXdIQ1IvZVdF
        S3ZEK2VKSzhyUVNzaWp2L29BTm9uVkg3c0FKRWhnNDQ5c0JTNDFjNnQ3MWozeDZK
        ZE9RSExLYVpENzFldGI3Zld5NXpjaE9HUW1MRk5hc0VybVplQ1gvT1IwMGdoalpD
        OTYySHJ5MGFsQmRJdUJvajBLMlZrZStsMXQ5N0V2d1phZzRnU21BVnFLaWpqWGxS
        amViZjNyWnkwTVdCM3h4YTJxNC9PRC83NWlQckxTQkxCNXhtRXVJamw0Q1lxMS9z
        M0lMclo1TDN6REdhZS9QV1RwWUZDUDQvTVNxZVY1c2VZSFlBS3loL1BqdjlBbUNu
        cllwZUo3eFAzWVpzVnBmeTE0NUNXYTBTMklFZml5VGFVVXBUUENEQnRUVFN6bjZZ
        N281UVlSSHJXZ2MxdXI4Mk9qTWtib21VOXNYbGNEQlBKVUtza21ic1Q2ZkROUzJX
        Zzh2M2hudG02WGZhekNjb05oeGhVOTY1dmNwWXFvSVJ6Tzk2elFYV0dGY2p6L2Zy
        MmZCUG0vcTJUWmh5MVN5anQ4U3Ztb0liT2FXUVl2RUxKdktXcSsvazhKT1hkVGlM
        VlNoZTlRK2UyRnpXS04weDAxQ0pHdDVYVktwVlp6TXlJYkRsVTFrLzBmK2xJdEc1
        QlV6dlZ5WS96dWVSZEZSL0h2eFdGZkNmbVIzSDNtWElUdlh6WmcxeXByZHVvYjlO
        WVhMTy9QMGdRN0tIek1Fdi9OZUhFK3pRaGdNa081QVJLYmIyRnU0amdxNU9OQQpu
        MGZwTC92elpDUlg0aEZwZ2dqNWkydHN5SVp2QktESVV0T0dtNURPaURzCi0tLSB3
        MmNIR0pESmpmWlQwa2QzZFZXZ2EzSyt3citlMHlRMjB2OTQ2bUJBZVFrCpaHxuk5
        GO+SIOszcoMRErsgHQwYyQ25gP+qSZG0wVjYOnBMK/HVVHKfqSn1XNOeBOGM5DLO
        b64SQfIPqk6nH8A=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:14:14Z"
  mac: ENC[AES256_GCM,data:6PFme4L3ROZZuWM58XWbnPPZzxknM/kDJbHceW7HEayWyuEqQhm/Ga/xT/K3Wbr3tdJWRmfN6ZStDJSIG9otUkqP9aojC9Pj/zRwhUDm7MO+TLh3TVpG5jgPdFmQdDnbDb3mkdJ8RdtiLWUdKwPgnZ1B3KHKn331Z7PXOB5cZUU=,iv:TkVkp3X/fT+EFb4uPg6tfZT4+bXCxgpqypVWKjRKLpA=,tag:CQPhc3XuYKFWzie5YbF8gw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
