fullnameOverride: k8s-gateway
domain: aknuk.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    lbipam.cilium.io/ips: 192.168.49.202
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEEyN1VETHVl
        TVFjQW5OSkFtVFNTTDRzdGN3Z2M4V3E2SFgwallMbmU1OHJjMytnT1J4RXhKUm5Q
        K0pnSWIxQi90L0VhbE5Pd2pHSTFycEJGc0xiQ1ZKTXBBNCtjQTlOTkRLUUxna3lz
        UUZFQ2xuUUpuVURYdkNLNzRTa1VXbWtENXkxQjVQM0lCN2hTdjNRbjA5V0VjaUdE
        aHVQUHVvemc5eG9Ob0dKR1FRYTdkNjRuamY5NDBSK3U5bHU3dm41QzlFeUVkVXBz
        eGVCT3hVeVZXM2VrODdGV25HTEE3QmZDQ3JuSGNTUDN2WWp0NTFWcUJwRW84WWFz
        U3pTVVVzVlZYYXBIZmt6V04wK3NKQ1p3enAzV2RFZGVEK0tMSVhhWmdCZmZ4RTQ2
        NkRNN2xoY3BDWVBKdnI2SlQ0SDlPMXBsQi9jcElhRmF2WmpmVFdjbVl1M1FHK1A3
        c3NKazJYRUNDQlUvMTNsQnV2M0tySU4xbWhmL01QRXpFZzdpYmVZTVAyNUw5Q2JU
        Z3M4NnkvdEVXU3F5bUI2QUJjc3c1KzJnOG9xSlFodU10dDUzWE80aHlQaEJMU1h1
        dDhFQWlhWHVVN25VaU5rYjliaCtiVlNtT1Y1OVRVM1RCcVVFYm9vRzlZMzlGQ2k2
        V2dILzBBOElxSG9xaXYwdWV2TWlYUHdYcHJORjlKRHV3UnB5aTVPZVdTK3laZThX
        aHZDV1FHWCtFWGdpclZvc01VaGxlUXZpT1d3ZVp6ZUluY0lJeDV6K3g5MHNlTmx1
        QUZsRTd6UE1aRXR1bnZ2QksrL2t3NXZ0NEswSEd0T0xuWFJhOWlWeHlXUUZkVFZv
        SXpzSWtiNEErUWV4Njd3TXREVnhtbnB2RkMxM2xXZWtNaXczQ3pYeWRNWExnaUoz
        ejVKTkhUN2NrMXZuRmp4M0Y4ZFowZVhuY2IvdzllWjBjb0NPYzFBM1pTWm5CNVJP
        TDQvYVYrNDdUeGdTVHhwcnJzM1VFLzhra1VyekJHSEEyTnZNTkhjSHNjYVVqUTE2
        RUU2UjdWNUhXTHlwZ29NeGN4ZlRZU0NLWXZqc3c2NXhzb3lVRm1sMlRpdXR3R1I2
        dHhwQ0Z1VDNqSkwvWFl2cGx1NEdmNWxUYVBZd3Q1Vk0zWWJuTHlhQU1XdHlnUmFE
        Zjd6V2NvdndEVU9rcXV3SDV6SXdMSTJ0ekY2ZkdEMDkrQXVLc3JPenozbVFYc2pV
        WXF3S3FCVEJFNXRuU0E1VG9UYkkwaWRheGo5TDE0UHcybmQwV1hOZDdKL3NIRTFQ
        Rm1lK0NhREZNUWNoVVh0Rk81MHBXY0FWMzV1aW11MFBhYThVRDJvSHBNNERHTlIx
        Um5QdTd3MHRscEx6TkVDRUxOMUFaMllzeklPVWx0bWx5SGtqOVdNdndDQWJlbkl0
        M09LVWJmVWtBaW5waTlRZExiSytyc0lXZEx6M2thQlJSeTd2dmlUODVoRzBndmZX
        c0lHMm9qWngzczhYUXpORmRNN0VzYUFTdWJsV0x2SHJDbWd4NVJyTEx4WVZsc0hL
        b1FTUTRkV1ZmQnRTTkR6bFZma3NBQ1lpbkQ2ZTh2emNKZHE5MHNIRzNPc0ErUVhG
        NkRCb0Z3VmNLeHE2YjVCZlpwSW5pVlUveWVjM212eGRVOUlNUTBvUmpjOE1GK2N3
        YUdJcnMwVHNuczlNSmNUQ0NYeVdwdkR3b01TVVVrVGJlSUxLckVacWJHcjBKbmZw
        NENRWEhlLzZmdHRva2VDL3hKNWdrYUc3NXlIUjl4VDJ6Vm9mUjl3YW5mYzUyWWFE
        WThWS2w3M0p2ZElqSEJWazJCbzRPazMrZW5RNXprTDIyWFdJMEV0ZFZLaGxkdjRB
        NDQyMzR2ZVc3OWE4L1Z6UUpqajBkWUs5VFJVdzJTbkZlUVFESUtkamgwVzNVZHli
        UVZuam5oREptVWV6MW1tSDFSL1EzeXF6dVkzcHB6a21yQnBiS1dNbkxpNUlIZwp3
        QThaVHFRNkU2d0hWaTlhVysycWxRSDZmbEljdXpBTC9rNG5ZaXFjaEN3Ci0tLSA3
        SEpFSXZOdlNSY0VpbE9lekFLdEVITlA4V2ZZRm1sbmN1WXZiVmMzOHRRCmg6S8p1
        fH7rSl4Xx3iMriZgt+ZZlCyK/o1qI1F029im0CHV2fHzHXh37uPHsGWRDJwmXTkp
        4Kxv3ZkvCYMzhxg=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:27:43Z"
  mac: ENC[AES256_GCM,data:08i92Fo/8dNuKeG6bj7bdQaSyaeOVWFAITsTVg+y/IyxoHaRLd33eF1JO0hvSbnNIcj1buc9G2vjsfwC7t4VjavIG8qiEmSsYtO0q7tr9UiNol0NgivK4HOzZfdbHQUWeWkJ2a5Oek5l8JcDUL8SXT34ItO5l71Ii/2hNe47mYM=,iv:CBppnUspyH7oEl5wFNCMVVxJenJuOncbjw2BTLXbLis=,tag:EkyQ3AmBSmiQ3z3VYXVMrQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
