---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helm-operator
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: helm-operator
  chart:
    repository: https://charts.fluxcd.io/
    name: helm-operator
    version: 0.4.0
  valuesFrom:
  - externalSourceRef:
      url: https://raw.githubusercontent.com/onedr0p/my-awesome-k3s-cluster/master/deployments/flux/helm-operator/helm-operator-values.yaml
