createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
image:
  repository: docker.io/fluxcd/helm-operator
  tag: 1.0.0-rc5
  pullPolicy: IfNotPresent
chartsSyncInterval: "10m"
statusUpdateInterval: "10m"
helm:
  versions: "v3"
prometheus:
  enabled: true