apiVersion: v1
kind: Secret
metadata:
  name: renovate-secret
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:B1+Illrk7oNuNsjJc5q+Wo2eHk7e6mvjWmuiVO1FRZV08r+g3UUyUZbPFy4p4Od6VDJmN1LVsqv8Ix70jgebmo3nQQC0fQ6MKfH1B9VyV/RtFL9Mm63VfRimkaXx,iv:qlqQbLc8FjlU+jC49jcnR35fch+9uu8agCPJ3vizMoQ=,tag:bzjzgHoNF9SAHb2szK47+A==,type:str]
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:ZTpI53J9XjkAvqJDio5rr0XRKXs+MAeUjiySUWGhGLKwgU0iS2oUUuEvOovXWCzGpbNKteXLTcq8TZbGuwWfBbcEymOJBpkHRFWSGQfsTz3ljGiI8wtB0DTGmqlD,iv:AaI19rwUU9BSbRa59UrwA7QMEjhuU0tE4+Ror0ZDOCI=,tag:61Z/EnoDPgaVKfnOCiK6lg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDhRelZXOVJ4
        RzhHMzNYZFg4bFI3UDNzZjhRYjRnYzgxUHBIZXEvTnkrNTRNa1JpR2ZoTy9nTWU4
        SDMzY3VqYlRQenlmZHNuTWdoMkpNVkdLOXhUdVZzZ0syamtIc1Bsa3BKRlg3QmI2
        UlVsOVVmMm5GNXVFYjl5TFFYNlNRaW01NWFFd1BOWXNDVkNKOHV6aEZYMEY5WVR4
        cHRyL1pyYUFBS0p0Zk82aktsTDhTMHdJelJ1VDY2Y1RBWmlKOCtsVnJISk1qbVlS
        R05weUh0cmlXSHdXRHdIVm01UlBjdmZrVlRsN3ArRWhhOFk4amFTdlE3YXdIclI2
        cGlGcGlsenFROWFQbVh2dUw5clhRWXBJc05yQXNYVThRS0pkOUxac1VIZi9SQWxJ
        WU45TFhDUjJaT3paT2Q4bDkxTFByRTJRd1BoRDRPendiSHdpbHhweDdGZzVVY1dy
        eTRlQjVGUzVMbmRUOWQ2cFNBSnd2dVhlaG5CZ01XVFQwM0FZZm50M3FwM0R0VGRw
        VUw5RnMvY3Nob3lHdlN3eFZ2TTVyT1NJeVNyT1VCNTZQb0o3K2dHZEFmbXdzbUY3
        RDVrb2plL0dUUUIrOVBkeWJrWmtpeW5GS2I1VWZlYTdaWUpya2RLTEhMd050Tkpi
        OUpzZFAxdVRIeVk2S0MrUVBzdklNRkM4cXQrbjRIWTZmWTlobHQyclhUUzREa2pY
        WWJWSjNwRW4zeW43U1pPMTI5U2hXcGtFdnA2SmlQKy9nRWhBNXhPbUFKN2ZEYzM5
        c2FGY0VoU3cxS0pPbGs3aWVMY0drTHFNbWZTNDRVRjRleCtoOWlGR0VFQzhGZkxI
        M2xrZHVFY3pSdVhDN2gySUtNOW5KUDFKbWNJOVc1RDBhU1phY016VTE3dGxWL3Uw
        VWtVTGVaek5pMDlGRHovQi9Sc1M2azNmMkVaQVR2cHRXRHptUlBxOUZ4VFg0TmVK
        R2FYcDU4a2h4UGsva2Fjcmx5RUY0WjdlcTQ3UmYwLzlEOWs1a0JZL0FqWHNqVUJi
        eXNDMDBRK2drSEdXaklDcnFkSW5vZWZCRUxoaFBxL0swMG93UlgzZHBXTVN2c3Vx
        cGlYVlZFYW1IU1V3NWtPdm90Z2VuQVIxSGJ2bEUreXJrdDc1Z1dqNnlCT1Q1WE12
        WUJnNTNDNU1Fd1FVeEdTTlJ0T3d0OEZOUVljRkZFZDY0WmxGTjBIazNIbktWNDU0
        SnhqeURXRmtMYkN4c2lUbm5SaHY1QzRIN2dlZTRsWHVmYjY5S3ZuS3VlZHEwSjRW
        K3FXc3N2b3YvMktRWGJxTFo4a2NRU1pKTEVwNDZnMVp6aXJycXM2RFFkQldBT25Z
        UlNoZlhXcGZEcVdTVDA2ZW9oKzN6UThLOVVkZnZnQ2VwNFBmN2I1ejBOQzVXVTlX
        OS9ORUJTNXZvWUpOV0J1LzBwekgzcnNHa0Ziall0OHlFbzdrMWdPUUQ2MmZZaGRH
        M2RQbUwrWEJCc1R4UktGMHpSOTFzUWZOR2tVR09RV2JZTzFScldEcjFRSlFwOXlr
        UDNRdVBKV2kwMjIxMk9xTlFmeDVSSktNdFJTOENkQmZMQVZraTNLdm1QNGhIOC80
        VW82RXpRcG9aa0xSSnJuR0sxQStnTnJhWEZ5VTFZK3dic2J6aXNGK0VHdHNmUXhz
        dlA0U0ZnY2p1QVQ0dTFINjlVem9DZXpyd1JDeXNucGdOeVZBeWhHVTJ3MGc5Z2lj
        NjB0N0ZtZndHQ3V3UjNiWlpGbXljTmc1ZlBTN3J4N1BiKzZXYmFxdERhblE1MHFO
        YU91cHora2dIL3JsZmdrckpZY3lJMXY5NHZONThwdHFhYUZsUkZReVFLQ0J1SGRJ
        NW9mU1M5bjF3OXozQktVeDJJZWV2L0dkc2VsTTVVU2tCc0xXNGpwZUV4VEhBOS9C
        dmJWTFV2NWFRbDYvNVlLejhmZlFxRmNKWUx6OW5jRXQ3aEIvNkdSVTJwMDdBQQo5
        OW5lNkphUmhCVjdEdm1SeG5pTVJPN0JFejFMUFltc1RyRTNONnRVdEtzCi0tLSBI
        NFMrR05jaVhaaU8vaXQyc2xPSVlpL0YvRDRrZmRFRERzSHE3OXZLQVIwCiT/RzjZ
        kddBDy19iDaaZT8xvP/HKHSmovVy2fe0QwYlsQiNSqtC2d6FYq8rb9R/C564jzUx
        nkg9bSJvJFxHQkI=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-11T19:54:18Z"
  mac: ENC[AES256_GCM,data:+lIstF+PdOoYwon3mDKRavKbdQc6wlh49Vadr8/lCwQrfk4PbLn8ymWflFP6Nh3/CA10MuBdh1K9OnYAnTIe0RkaeLOG4n2YSdCF1QszFaR927a+6Ab82TMm2BhY6H71fdVutZp2RSrALvO2suF072Xkn8NUyp1lKNmEKNH+q3o=,iv:XekQUHG1niZ76XqDIQgEbTgT+Z7veOGzPTxEvJtkPiY=,tag:KXQ8e4nY9Ora4L8xFoYnVg==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
