apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:XfS9uOnmlMz3tjYPDaAZ1wU5h2bbg4sThSDEyTsFranWN6AC0dx5/g==,iv:322iCefFPTxcI0v6/PuhT+WNBp4wHc8zgGTgvYrozfU=,tag:EYsLL/YMvQz/1eE9IuJMDw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHBJWjJaYysy
        QnZuMjh5Ny9TUjEzZXpXVEtvZ251eEI0emYwUzEwWUd1L0hHYTFLOVEwa25ZeFNt
        Zkgvck43ZkZ1TGZub0d0MkxpS1pqUEt1RzR4azhReWxSNnFwL1NTem0rbS9KenE5
        YU1JV0tGNkhaTmNHcTFpSEsvV2xRd3RsQkpuenhGL0pJOGpLaFdJeXNoOG50cElP
        dWRIWElxT3lyQi9tWjB4RlJGaVpQcWR1Sk1jNm9LNjljM1lvYnlBc1kybTNkS1Bs
        UW1lQldNMHMyR0pZSFFUZVBuTTJTVGFtQjRORkhTQWtuVHl3ZHIvdG9kTVZJbWp0
        MjY4OVVZd2QxdUF1d0NQWHBEWU9ZVzZXelNXOW9mbGQyZmh6YVBZaXVTdlBaeDBo
        RmMya2laUnJLWDArTHVLdXhjeU5MbW96b0pWekE1anZxTHZpUTJDR3lNVGFhL3BX
        MVdkc1BWaWRESmpjekxoME1GaXdIdEcyYzkyYmlSc2JNaFdZc3MvU1NsMTRCa05Z
        NWdUNzdybElVZThBbU51RzBJYmN4bTc4UUxvQVMzQ3czRXpKM0JGUmI1WlErR0lP
        UnRyMUd2MU00SERaQ2xWaUExV0JDdUVRZjc4Tkgxb0pNc3ptY3ZvK1JQMGpuVmdn
        R2hFWHRBa0hVVWhkK1RpMGxlMm5uN21RUjFXM0JUancxdEVKbllBRFJNWWlGZUs5
        UEJ2WmtVQVhQYTZldkxSci9IU0NMclNsTDF5dHBzcThhUXNXbXE3M01DOEt1dGxX
        NkZKMDFhSy9QYzhHZ2dwT3RMeXpXWDQ5MmRMY3I0R3BHbUtPZjNWZURXa1d4WkYw
        blNpaHJvanhYdElNQ1pJTWF4WXM0cmNJb2YyanY5Nk90blJOdExWMWw3VUl5S3JH
        cFY2eXFwNldyY1RBU091cmE0TjZoR1E1a1I1eW1VampmWUJUcDRaUVA4S1MrQ2ov
        UDM4eE1QWGc1SklWWTBCenFvYk9lbTFPMzNQT3ZmS3RUY2xtanhzOWtnRzdiVElx
        cUVod01jd0t4bGNudk9ML1VtRGVIbUNSL2xvbGtLWE9LSXRxM2t5SjFQT0lMVS9i
        UWJzb2xBS2FFdklwU2hQNW84MERJYWRrWVFoai9Ka1ovdVREa0RyNlhvOWNNMnZz
        emdsdHFqNGlZRHY2RFhzNEErSXorVzkvcEE2NkhEQ0krMVE5TU1jWmN2d2pGQmtn
        MzVNN0lmdWF4R3BXYmtJUVNCT2NuRENRNjhmektEWm1CTzRTU2Y0ZjlwMFYwcDMz
        OEtWRDhzY3g0VE95NG5hcEEvUzlRdU1XQkFyY3p1aFAvdk0vS0d0a3VvbE0zYmFB
        MldCYk1CVFlSY2NMYW5wYnd0TGdwelVGU3hZZGt4eXlwSms4TXZESTJpSTN5TnpD
        cW9LQUZsSG5mNnQ4V3ZuM3ZscTFsL2paUHE1M29yejI5T2U0UGFKV2tkMUpDaWMw
        SEJvZ3h2eVFIdmorWkZ6SHVrRjZXWHZ5cUJzSkY3YzYzUzZZSHp6MXdRS0xWSFU1
        YlZHZGIwZDJBQzVicHpWWkVmN3FXcjRNc0NxMmFaK2d5a3NYNWN2NzRHVGcrUWVW
        dkZTWFhWZUlKeTh5N2FLOHNCa3pYUDBqZVVBbWM3WExCd1hNblJWS21oa29mak8z
        ZW9qSVRyc0ZpemlGZi9yVjhLSTJ1eFBOWGloMnZDbHBjYndUcVpIZndLVGRTS0tX
        aXc1UXpYZ1NxbnJ1ZHhac2g3eXlkTmZSUnBDM29LRk1sRFVFY0lBc05hc3B0L3Mr
        TitZRUVWTXl4eHZ6ODBJSUJEemNWbVNRQ1dBYW5xTXRaMWxrNFRjdENKU0paNVZk
        NDRCV3RsYVZBVXA5RFV6eXM2cmF3QW83bVhXaUVFdXF5VUpiWDA4WE5zcWdTNUht
        NGV5R2M4ak5VUUJZVXJRQktXalVubW9KQUVRNWlmaFFIaTJUZHYrNVpZS0VCUQpU
        VFB0WldsVlYyc1JTNy9uenZNaVB0cTVobHBBSDJzQ3FwMm0yQ25WZWNzCi0tLSBL
        MEh3TnNubUdicVpRL0krYk5lRTdMR0hUQTBNTlBWYVNFckt4VFBVTFA0CjUUcPY5
        0OciA4cpyhD/3c76JLIzz+p2vYiHt4KGt5neBCwaHRn9DNMsPCy6V7hF4rdbHHDw
        oWGzROrp0w9uzVA=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-03T13:20:27Z"
  mac: ENC[AES256_GCM,data:flN8uWzhmg72b7Zugv7aUdEwOuk42Eqx4to6A4l7mjw3dEzIrKvv+bwwwNBfDhMXcAOu/TBtTfBcNIrv+/601QP+xLgbgMQCzDxBk9xBtv094Bh1D/jaLogxfaHMq1bDj98+K3pfGyzaCEQZP1vLUJFS3/JOHuLbywKPy7+Q0uQ=,iv:QSjlXrNM19jk/vWJ3iKp6KHyR6xTQbwzzmAqICk0V84=,tag:zjrtIum4Lm+Hxq3IoBzI2w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
