apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:R4Cq3+6atXGFgCieP6OU0v8mkQA8TWw/e9+mzJ/rPBx5HBrMggRoCw==,iv:DkiwMtcJNriRW1QsWnWl5Sf03hpADzTrG7NBHYqKHXQ=,tag:Sggd7NAlB9W3QGLRNq/+ew==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE9pbThGb2xq
        Sm5iR0l4SklYUnhicWs3SHloNkl5TDhvbXdqWnUrWGxyZytSRWdBQVEvVnlvUVpy
        UG1iNmhnTHBjN0hiZHhyVXA2ZDgzMEk2TUptdStYcSt5aEhwSE9XRHlNR2RWb3l5
        T1o3M0pUdnRQTjhyUXo2QzFQYU5NYU1QUzBLbzdaUmZFajhFQ1pUcmZiWHJEWVor
        QW1TL1lPVEhqeG1JRWpLVDZJdUZLQUE2R0N3aHhWTHRYdVdlOG5rMkVLMTkzeHlV
        bGdlcWlod2plam84Y2xKSlJNNHlrVUxHNTdSREszR0lmZUxYWUFZQmhjbytHbTFH
        S2tMcldwSS8zb3JsU0UrTXdkL2lFaXlVaUx0NzRCMWl3aUNBcXg1dlA2cm9zNWtL
        Vk5TNWpFeUphTzBkSlNiWXMyeDhnWWNKcS83a2tjSGxUTzA0Q0MyaHJBRUVJRHY3
        by84djRpZnBGSGxXQlAzQWU4R2NCSW52M2lOV2liclZnRDNRbWllQkJvb3hKVXlx
        NExWdEJ6LzYrOXNtdUVSdThrSTNmYk11cHpqR2xJVXE2OWN5aVpwVStJQWR2WDNr
        K0hCWFdJUWdlaGFKemFiTDA2d05wMXdTSHRDOVE5d3p3d2JYNnlTK1VLaTQ0Q3dl
        WmhZQTR3ODBZc0xGY2FXRFU4SXV1TllWdmlHMW1JYUpER083MHMxNXFER1BzeFBO
        c2ZxaGJqRjYrMTc2VVR3cTVaQmdBeXdmR0xaL0FiWW1pbGFDbTRGUGgzV2tsT1M1
        TVpaTkVsSGxhdFpWc0YxdUVPbVpIOFo2QmxSOFlaV0Z5R3c1MzIySUV1WWpCTUNC
        R05FeG1RY0NFZzVJZzRXcDBNN1FjdWh2V3l5Si9nci9PeVRBcTU5Skp3QUN2M3pT
        VktObUFvMVE0bEJQTkRCMFBwdVlVR3R3Qm1OWFdkT1BBZVBVV2t3b0E2dTgrYXdq
        K3JndFNjQXpzelJtZFJyNlB2SVpCa2JnUVV0MWNFWVRUV3h5b0Jtc2UzTEFnRUw0
        U1hRcHpKQ0g0eHFmVzhObk1XT2Zvd1NUczduQnF4UktqUDNTV1RRYjdyK2dBVXBS
        ZWt0Vk5ZbkUzVmc1dHA5N2prT0plREhiY3N6VDJxeE5HV3hEbmxjaWJiVS9PNkY0
        TndJT2ZFQ3dzbUZacFcwckMwQ2JLWDZKWWVIVGFGaUFLT2FMOGJxMkU2b1hIWGxU
        TzRlVzNMQUVyc1JZUUdHNmxXQi9hZ0hBWWZraXVLWC9SdW54S094Vld3RjgvRXRC
        anprdFlUdGpQUm80TVpoM1VmTTRDNmFWWWh4V1FWUmZGYSs2QXBsYUdqbktVclpU
        YmR6dEQ0VlF6Ry95ZmRYZFdIYnloREJ6SzJuUDFwdzN5czZ0SGpBVG45VXpGMEZw
        akVDUk90aE5QUjcwcVErSWcvRmEwaVlWUTRnWmhkL0FCSTE1cytKY2RjNHpIY2Zy
        cFpHVVMvV2o2QVpLNFhBSjdCUjFJc0hHQW43UjhQeHJoNTdkZUV4dFFTVngyYVJr
        bndqQTVOUFZVbHo4cUVIdGhwVUJDM01iS1VJekl2bVh6Sy9HN0E4RzlRdExKYlZV
        Yjh2N2dRNEI1dDcrQlJIeTFBa3YyWEFYUmVwQk1nWGZVcHcyS3ErVkpoRVFlVzBt
        ZU9DMlFzUDZNdnRiaE90WVNOMmxFenZDU2Q0cnNzYUovWU12ZWMzR0M1bmhUZWZP
        cVd0NFJsNEFLQno3NEkxN1ZJQlZXZXBDeEFESUtHWERzb3YvcVJLMjl1NENuUjJl
        SkU1VlQ2WWh3WlNIYVZzcVJjZ3FVSjhjZW43aW56RTFvYnpvV2dPc2RoWWtQSlZN
        UU4waVpNV1dHUFkxMG8yUmN3eEE0N1llSU5TSXJNNXArbTlnOFdKTWxhUDdvUmxR
        S3J6dWRrSElQSmRGTktIQkRHMG5XNkpCTVFWekJFUkFSajJucDRqNXJBWGVPdwo1
        SkRPMS8raXNNTHd3eUlZWWZRSXNJNENNTVp1Sk4xMVRUOXdyM2Zpa3ZzCi0tLSAy
        d1dDd0hFa092VjU4VW43ZkxHcFcrT2QvdVBjTk0vZ1B2MjNTV2FxaDVJCuRZ1hSj
        W2JVEKep0ZWly8WfFJM107WFxL19ZPN99++qSaBP8wJSpKuCKJhtRi53uv4l3saJ
        PrwOqD8gTmuUr+I=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq16lc4qceptkgy8sytmpxr8ksgxfvn8sfp4lhlwzfmgugce0ypfs4h2chksfyvxrlzvp9eps7yrn39p5433dkuhduv6j82k62c8nv3e4vqgedmvxafk7sxldpr0ld586h2xpe7j5kgqhqfn7rjaa583dqmn2d6dzdmz2mtvac7deuz5n8cp4n2t9wzes2ev2t5tefra2jspkn05m6a4qgwskr6erch6fz20a9lrjd3ewey4avrrkyht7t38n02edcupgdkfudjf9yux29stdfgpw7y02lxetqw9ntxle09e65ekkj4uyuhd9eepw2z6wruceuldy05rt9duquuy5f87jekr5tve9rfsfzrezmvksv3een4nsk4v4ryupxe39chgygfzd2rrneydrxs9phr8wtzn4mgyvgv5gn8k662wq9t04784cajy9ly2z3jqt55s9uudyt6j392lqqphd3c39jkue63vvz2mp4844355kunqa4nhglyt4kqzcm6s3mrtntw9vv9e9lgffktgxwvepnmfyjgxmmf4trrgvsqxprnxanzj02cpfhlyszqhxuuvdqvkfkyp0aewcjqr3hfcurfrc2qpl0fnh025eztp2s9zmy5fyc4yte89cjutrr525enqmxxqjuumk8hnps6xn665fc29vu6aq9t623jnkkw00ls8yg8q2q2767qdg7mg0fwcjlllpxmjr9ty8e8xqduszks2gpxssmlteygydmtuam5jfgdv06rfyd69cvt9qen7fmrwn3tkysfg946wcequqps9es96rmzj54qv7whp3tu2a5jjqat42xz9z7wrxjxdpeg5haedn725s7ttghfge0whjtt4y2j0kgsppat8zrpn0xrmktlejzhn9fj8ymp3f82uqffyvu0j6vs0zugdd9az26rgwr8m3mga7dufyjskuagzjgu24auktz304ypyq9krhnzv9xzf92qc5y98tx2x6j43cfzxz4kmjquvymezk95ulk3enfxqhu82j64uszt6hggaxn5fskuqv9nz4w0g2jdg24zt9dfcfueku2j0zkq7zym6qa3ngtecfqdv5vq7cqehwggn8vc7788tfg0qc6u9wwhnwm92vq2upup9c3qp9ymejeyz3eg7fpcr483dqqcq6kndwxgxcs8nfpsrcendcph5q4v4d9dcvr8czr954men57sg34dcenu9qzgk52ucww2n406qk0xc7nxhn97e0vryewqr3v44r7rcs8vkz9ag4g60s63elqrs83z7lpravxvmacxmakkf8jwsjpdjlzeyeyes85zrf6qg5n94934hpz329kprumte90yprwver95mz2c2yyt2lnsqsjk406zqy93w8q3ne3qsmgjak0kkqf3kechsseyxpetfgjhxd5pycyq0tgt53tjs5vnz4urzukhhe5udyfncwvxya6t763x37fg35xywutl5d0pcqj6vazy9xzc5z7ztglkg3c39f5fqpj59sy4yhpcrgz0ycl3meyrxsv9s4ksx87tt9jx690dwk6hgj4287833glu80lh0sqjted8r53ym2ygxsnnhxx323m8czgzfqtv3lmmh6d7wrv6kcc4k7yg4ceka58cgwecks3faj9kzwcvxle62vhs9cagpgeac57fhxekxh2vdmn3e8sf3r8kefe5n4202qafz8zgzm0f3rmr7x8avj58vnjyvm6ft89vw8yntvyntsfh8rygv8mxsenzzgl9wn9lzvpcv0qznd058332y2rmephncsftpx6c2w09qpr9rjmvafvfxlzmfeetljvj3xdyj5k079epdxqcukd4md5cvvcd2xwmeu0kgye06uxhs0mjlfkpt6rnuf493m3h3w79htcc8cllg76nkzc9ea7vq4hdejvm33aq7ffvzk5hk05k9gtnhfmk
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-10T15:14:14Z"
  mac: ENC[AES256_GCM,data:1A/9OuEv3/ErsIyDIwnQCeYYyemZ+/4VWHvOm6kcd0qkecFMHPtGV5ZUEZRP9vDyDCtW6P3W0Yw6zGOZtYUI2LKgH/owej3Zuu5mUmOWfF198CiuJa/eVbG3GW4MDyY/bezg52fnOsSoxYUbFzCSj37/FAD/J8i6PnVfAwvy1NU=,iv:jL9hQ9sZDGuPHF1+3ZTnaJ1Uj9HKARRM4szzL/vASDc=,tag:rVZDGbTw4m6EwhO+oKPsHA==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
