apiVersion: ENC[AES256_GCM,data:uv4=,iv:pcz8sw57QuNdP1popCdZceRInE9BnHqkPmBOKE5IigU=,tag:44x89cW366m50BZPGOt1Rw==,type:str]
kind: ENC[AES256_GCM,data:iKrw81cT,iv:o2Kj/wy9I0sEu0JAoI544gb9fwNK55m1tsuLXQt3Aro=,tag:mkRx6iwqyXBo1e5R+2OItw==,type:str]
metadata:
  name: ENC[AES256_GCM,data:7BaOyrdlo6/DAH+7DO1OD2r+c8Pg,iv:O/oMozK6mcOssYXA0unZT3P0FTh0QDxYWryyD+cwrm4=,tag:bJPR0F9dhqDAQ70gkIjKOA==,type:str]
stringData:
  api-token: ENC[AES256_GCM,data:QbJ9hOc3xoTbysRUCZyHcZZ6DOQJTdGcwjnCSQev7WOxOiGd0+jlaA==,iv:NAi4/mS7G28KNZ561BIXdiAcEguL+BX1Ww/r3nxo1FI=,tag:eWrJ9nJb9U+eBZ744RyaMA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHFoT2NCdjl0
        NHNjeXVOSEdWbDFCMlRSMllpOFFBQ1ZMZ3duYWEvdlJkT2VGdHV2K3RFQnBzMlNi
        SDZlWlRHS0ErTUxGK3FnQnZKSW01TUhpS1ozbFErUFVTaUpPaEpBWTBjVjlWdloz
        TVc4cjNHNEkyWXY2RFRXSHJvUzc5Q3UrbzkyOXBONjdFc3FwaXVhVTBtMEhFa0E2
        ZlpkUXpwK2pqWlJUdDlsK0V6aTg2SWJrU1cvYXQwbjU4d3IrRFRKNnQzQWlaT1dH
        eHRMWG5GSnZ5RWJadGpVRnZkTkNDcTlqeXRzKzF3dm9pNGZCZkJTV2FLQTlUOTNk
        cXJCY05TM1V5L2ZqMzVGWFVUdGtKajJYbFFONjdCaWhxc1NTL1NuVkRxa0lnR1Bz
        SVo3cC9TN01IRkZCUmNMV0ROaWRmVzZuZmFKY05KNGdtOStCbE9EYmlSWVlCRE0v
        Ynl1bkRxaDh5dzZzTU80bjcrNjBjM0pNb1A1SkI5bTl6d05HeVhta0t6UEI5Z3Ey
        cjlmNTNSNmdJWVVBWlVqam1vdW96bkJsV0kvTUFKR1d1K2NidXlac2F2aVdkUUZT
        ZDNPRzBMTFcwaUdPY0FPV0V6RGt5Um1peUlhL0MvS2xWWWFsbVE3RmV6TlI5OVdN
        R0NORGdsb3hEK1VMYnFqZTJ4dUpFOHA5dnZzMWt3L2tkbElSUHN3TTJtc1VnVXVq
        a2tYM2xSUWpwa3dJeWQ4Q0xjYUtPMkVKaklzSVNiUnY1RDBvbFllczREQ05iN2Vv
        VmlvWWZWK05VZE1NeFc0bmNDbDVQK2hyajNUenBUdmV4SnNISUZPMDBEZWNTVHZo
        aUtSOTZQMVQ2MjBiazhaRkpZeFE3OTFaZTlQSTFYcnRqeWQ1R2xNVk9PRU50STBZ
        YTRINU9ZL1FXUURBcDdKNG9ub2tucE54a0FHYk9iZEZOQ0FZTCtMb2dUQVpoL0lB
        enV3anhIMGNuTmd1RTJCak5mc2wvZFhFZFdEWnkxaFZoeUJZdnBtU2p6VFhIVlQ0
        Q1NJZEhhZjBsME9rY2E2Vno4SkZyUDZ1QUllWVRKTlVJRlRkaEVUbmc2VTJwM1Zr
        NVRMMUhQNlBVNXV0eHN6eDd4cTNILzhGL0I2TDRjNSs2SURMbWpMVE04YkFuOWhv
        RUtRVk5KVkFTcUtIODk3ZDUrb0VXUk5VM0JHY0ZFek9PWDhpSnBLaEJsS2ZXeGRB
        VnZLL3dFZzRxSUloNS9KaW1XTm96WU5LdlU3bWhncldvOHNNZDAwKzIrV0dZY2cv
        R2lPZDhPZmFNdWlpNXB0dmlSQnlPUDRwNStSeXoxRTNEN2hNZldDSVhXbjJscmtp
        RGgxYVZwYnhsVGhNN1JlVzVUZHBROS9NeDl3QWJxcW0vS01KU2QxN2ZRdUhUdGtz
        aFY0OWdGTDBnOUplY0UxdjhVMDdRVlpxZ0w0aVBQUFF2NTh2RE8yNmRYS2dYSjJX
        RDIzRVNyZFFLSHBYVGxKSnFTRlJWU0N1Zkw3UnNiTC9jbktLT08wQjZ3eEtpejkw
        MFZiNVlwa1R4SmhFSjhTMTNndFNhQ1VRV0p1V3B0VzN4Q2RmWVdpcmpNNFJHYnhR
        aHJFMkdQcTFGTTNMVEhkdGkvYjVhc3FqcERXQ2d0VjVFR0o1VW1KZWpMZVdCaUNU
        QUpvUWIzZTB2Tys2bkxzRGZ6ZSsvYW9tWXN4QktxM2JMdlE2d0lUZEliK3pIUlA0
        OWhvUjdST1dKSWliMW8zTXhmTTlERVBuMlNpSE4vRzVPaTVQcTlDcklKTjdRRTVH
        VDZ4Z0FpNERSMi9TUzlIeHh3Yk5PMExScjBqVTB0ZkFiNjBFNW15SktaamFwYXpW
        NEM4c3NGcngzTlBRUm1rajVlYkkyU1ZiNFV3UWNBMERyejJqZXFnS1Q0cTFYOVBq
        V0tnaDVOeWpOMDIrRS9ZWkM5bXlvWDhBL0hmS1NyZmNPek5OSldqVzVNU3BYdwo4
        V1U0RFpWSjFPeHdyT241ZUY5Tlh6ZmxSZXFST1FPSXRzdE1NeGJoRDBrCi0tLSA2
        WEwvSVNYR3dRRHVrUzJWSkYxR3JNc0RGUVc2cmtvT3d1VDJNWlYwZG44ChOA3Oud
        hEs7fLQd7Uc39kBWp2PdPbc1sku2XmviNUMZaeKX0GD+GMhh3NCi++RwSEVKmzRY
        K8LjRa8ZOKre2xU=
        -----END AGE ENCRYPTED FILE-----
      recipient: age1pq12rf2uz7mtzqsz9tauezfh9f7p8pyt2nec35w82epe94lfqpzmejhf0f9x0w7c6fn7g4deagwuwaem004eetzeyd63wjkgp5p8c5ev2yukyl8cr7cgjx70zk8dff5dt3rgec630rzj0y78fzejue2deppelwl4fzlq6ykvax99r4vefyp8frcdg6kyvv0q3temf7zctl83styqly3h9vlfjzkmrrumvax2l52fxrz6w28xgj9axe6mfpef79swa836dpsm3a05fmxt6txh0s6ew72xgzpq44czz3me97v4jz8gtptvn8x23jtg87pufkgh2pqpp60z9jmutpc4rs4zgdy8mvhnvdmyphj95quddapushyzdv4yd24pv7rye47asy5gzc84s9554lp0qfrucme6gv90ss3ezcw030z7fmaa7fgcl5twvyuyu04f8kt9q0fme4xf2m3nfn9hgqcysxthg0nzjeuvysk3gcv97mwesvc733a8j4h3nx2hfxs2xc9qtjvfflj59exgwyj3ja5es76erv4rzcl8pc2d8ge2zevv8t32xnsuj8fq8yemzyqexvcfuuzpdr9ckqpy4w23s6n3x632l9r20kgy5fscyucake37g42ygmrqu0g8gtcmadk3uq3yz4s2gr8v83fuykp9f7treyu0xl4j2t700xcvvllk593v24nzxl4c2e5vjzhy4mfcyjy8tmrcg2ked03tyruk76d0pry98s9n0ev3a50ym2vdgm05pv3ajegjsm9jcqwesrkzy5pqu2xes332ngyqfepc2zv25ll25vvnvr8ap544xzuedvxpwr0ksjh0amry2ary7rt9pe3x9e4ajzrf64sdz2pee77dd0e0qpy2pzxts6nd5phv8qv5dms8jl57ykgrw42zg9eqne8wmqg2z5jaj4lyhgjpdjsr8k4klfl57cawzdyftatppaycl52sgfavfvhdwgt4c7vekx58y5ev6l6eqrsfxy8d2t8gktq38uwqj2kkx9vew3r2l48hh85fhlfhsag2s3t0enhpjppdfduktrlvsgvv6l6vw25ud54f993434yjma7ryrd8fsqwymsapr333r3jf6qegsql2a0mddu6xxxfapeqlkn5dxsp5fy5acgrk6c4ng9dffpxpwev4r7zydsup993mvd2nytjeel6m9vtxq9qnmr4ycnz4kjkjwmsvgf03agf4an07l6slxkh3z556956wfsm7ym88v2308jskkc3crvhsajqsq5sjjrkx28739me5n3rzs6tnrh30855ey0awgcye44vxyhawaeykfxdvq6vx9xj8repyygz6utvu7agg7c6darmu6rqh3fmj33sf5d5t33xkf03m9shw3mlfj5yy0rga7s2xdn5234az32lhl63c8gznw4nzerlc5625fh927f28fus25k8pla68rhp3vfexljte04cgay6g9cjc5d4rx2pp6frmgehqqj2s98fu4jyud3uhmpg08fyy5m3yu3lpqn0vnkyxt2j0amwcdwy5kr22tcfmcqqpn657ln9y4tt34ax5vv9dyf88vfnjq9hdsfv4r0lu42lmzsxkjm5pg6e3fw8v6s52fn79uznt9ppymcd083uwywnqczma4m98yzsmt0e9dpwec33256sh6v8kvhq2k5wd32u23tqvteysxpw6y2x022x409qv22m5459e64fphq4qj8ze9dyv90cxn4z9neuxry5cr3wmx86v8g5cymhmdpfuqcquqq4vrte957rycxngqx9vvhdnwx8sh27at9ndd6zznprmw826r74tk7qumt8sdpw8w0t5430zxdxgljn49rhnevstsvyzn5ru54g7h3xwpz0c6a8jmews5d8yat4jl2cv9mqd4kszwfm56da07k3ax0cxcns3lttca8jdfr
  lastmodified: "2026-09-22T22:18:59Z"
  mac: ENC[AES256_GCM,data:WXALLftcS/a4eokLuclfC83DyIDhhA90UqnNasgNPiPI8sEetcB0dsgJCUHNdZnZ9JMGFOGM0sz1sZTGfce/CCW3OJEF43aq/QerJJbzK5N1mSDHqIkEMHeN09g7dd448cr+OtN9yz9PelogX7N3kgbDRndFbAuJASkMPg4wZ6I=,iv:L0H1EVTQ6D3peuJ49wY6k31PA9QxDoPWTr45d0POpq8=,tag:rOo9j9MgBJ+K/bH+BbalZQ==,type:str]
  mac_only_encrypted: true
  unencrypted_suffix: _unencrypted
  version: 3.13.3
